<?php
/**
 * Copyright (c) 2017-2024 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists('m4is_pms8y') || die();
 m4is_gkbluj::m4is_x6wv();
 final 
class m4is_gkbluj { private static $m4is_bnd6ti, $m4is_bh12zy, $m4is_o3m_c5, $m4is_n3zlk ;
  static 
function m4is_x6wv() { self::$m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 self::$m4is_bh12zy = m4is_w0enbm::m4is_e5l8a9();
 self::$m4is_o3m_c5 = ! m4is_u68pu::m4is_u6mkaw();
 self::$m4is_n3zlk = 'memberium';
 }  static 
function m4is_fn5m3( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '',  'not' => '', 'output' => '', 'membership' => '', 'memberships' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_wd8fkq = ! empty($m4is_qnjfv['not']);
 $m4is_qh8p6 = $m4is_qnjfv['membership'] . ',' . $m4is_qnjfv['memberships'];
 $m4is_qh8p6 = array_filter( explode( ',', strtolower( trim( $m4is_qh8p6 ) ) ) );
 $m4is_bvtw = empty( $_SESSION['memb_user']['membership_names'] ) ? [] : array_filter( explode( ',', strtolower( $_SESSION['memb_user']['membership_names'] ) ) );
 $m4is__8htld = false;
 if ( empty( $m4is_qnjfv['memberships'] ) && empty( $m4is_qnjfv['except_memberships'] ) ) { $m4is__8htld = false;
 } elseif ( ! is_user_logged_in() ) { $m4is__8htld = false;
 } elseif ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { $m4is__8htld = true;
 } else { $m4is__8htld = (bool) count( array_intersect( $m4is_bvtw, $m4is_qh8p6 ) );
 } $m4is__8htld = $m4is_wd8fkq ? ! $m4is__8htld : $m4is__8htld;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_d3wdti( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return 'n/a';
 } $m4is_tz42r0 = ! is_feed();
 return m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_tz42r0 );
 }  static 
function m4is_qhtyn( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'not' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_wd8fkq = ! empty( $m4is_qnjfv['not'] );
 $m4is_wd8fkq = $m4is_carw7y == 'memb_is_not_admin' ? true : $m4is_wd8fkq;
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 $m4is_zts3 = $m4is_wd8fkq ? ! $m4is_zts3 : $m4is_zts3;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_zts3 );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], '', '', '' );
 return $m4is_z50f;
 }  static 
function m4is_cx5n7( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is__8htld = is_single();
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_hmw_( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'fields' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is__8htld = false;
 $m4is_w_8g = array_filter( explode( ',', $m4is_qnjfv['fields'] ) );
 if ( empty( $m4is_w_8g ) ) { return false;
 } foreach ( $m4is_w_8g as $m4is_g1ru50 ) { if ( isset( $_GET[$m4is_g1ru50] ) ) { $m4is__8htld = true;
 break;
 } } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_n1pb6( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
  } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'capture' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_z50f = m4is_w0enbm::m4is_e5l8a9()->m4is_cw_2qo( $m4is_z50f, $m4is_carw7y );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_f0d1q2( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'not' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_oa_z = is_user_logged_in();
 $m4is_wd8fkq = ! empty( $m4is_qnjfv['not'] );
 $m4is_oa_z = $m4is_wd8fkq ? ! $m4is_oa_z : $m4is_oa_z;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_oa_z );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], '', '', '' );
 return $m4is_z50f;
 }  static 
function m4is_kxa9( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'debug' => false, 'not' => '', 'txtfmt' => '', 'user_id' => 0, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_ig9p6 = empty( $m4is_qnjfv['user_id'] ) ? get_current_user_id() : $m4is_qnjfv['user_id'];
 $m4is_qnjfv['debug'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['debug'] );
 if ( empty( $m4is_ig9p6 ) ) { return '';
 } $m4is_wd8fkq = ! empty( $m4is_qnjfv['not'] );
 $m4is_j5p3w = (int) get_user_meta( $m4is_ig9p6, 'login_count', true);
 $m4is_niyk = 2 > $m4is_j5p3w;
 $m4is_niyk = $m4is_wd8fkq ? ! $m4is_niyk : $m4is_niyk;
 if ( $m4is_qnjfv['debug'] ) { echo 'Login Count: ' . $m4is_j5p3w . '<br>';
 return '';
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_niyk );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_j5hes1( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } global $post;
 $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_v6fdv4 = (bool) $post->excerpt_only == 1;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_v6fdv4 );
 $m4is_z50f = m4is_crqo::m4is__go6j(false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture']);
 return $m4is_z50f;
 }  static 
function m4is_lz2o( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'htmlattr' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $languages = m4is_ss2_7::m4is_pphwds();
 $m4is_z50f = m4is_crqo::m4is_t9dq( $m4is_z50f, $languages, $m4is_carw7y );
 $m4is_z50f = m4is_crqo::m4is__go6j( true, $m4is_z50f, $m4is_oju3a2, $m4is_nbu4n, $m4is_wlico_ );
 return $m4is_z50f;
 }  static 
function m4is_vl08k( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '') : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'htmlattr' => '', 'txtfmt' => '', 'until' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 if ( empty( $m4is_qnjfv['until'] ) ) { return do_shortcode( $m4is_z50f );
 } if ( strtotime( $m4is_qnjfv['until'] ) > time() ) { $m4is_z50f = do_shortcode($m4is_z50f);
 } $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after'] );
 return $m4is_z50f;
 }  static 
function m4is_qxp7z( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_bq_t = 0;
 $m4is_bq_t++;
 $m4is_r6nh_b = [ 'class' => '', 'delayhide_function' => '', 'delayhide' => 0, 'delayshow_function' => '', 'delayshow' => 0, 'fadehide' => 0, 'fadeout_function' => '', 'fadeout' => 0, 'fadeshow' => 0, 'id' => 'memberium_fader_' . $m4is_bq_t, 'style' => '', 'target_class' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_tjg_9 = '';
 $m4is_en2ve = '';
 $m4is_xmzol = '';
 $m4is_p4izs = '#' . $m4is_qnjfv['id'];
 $m4is_z50f = do_shortcode( $m4is_z50f );
 $m4is_qnjfv['delayshow'] = (int) ( $m4is_qnjfv['delayshow'] * 1000 );
 $m4is_qnjfv['delayhide'] = (int) ( $m4is_qnjfv['delayhide'] * 1000 );
 $m4is_qnjfv['fadeout'] = (int) ( $m4is_qnjfv['fadeout'] * 1000 );
 $m4is_qnjfv['fadeshow'] = (int) ( $m4is_qnjfv['fadeshow'] * 1000 );
 $m4is_qnjfv['fadehide'] = (int) ( $m4is_qnjfv['fadehide'] * 1000 );
 $m4is_qnjfv['delayhide_function'] = ! empty( $m4is_qnjfv['delayhide_function'] ) ? ', ' . $m4is_qnjfv['delayhide_function'] : '';
 $m4is_qnjfv['delayshow_function'] = ! empty( $m4is_qnjfv['delayshow_function'] ) ? ', ' . $m4is_qnjfv['delayshow_function'] : '';
 $m4is_qnjfv['fadeout_function'] = ! empty( $m4is_qnjfv['fadeout_function'] ) ? ', ' . $m4is_qnjfv['fadeout_function'] : '';
 if ( $m4is_qnjfv['fadeout'] < 1 ) { $m4is_xmzol = 'display:none;';
 } if ( $m4is_qnjfv['style'] > '' ) { $m4is_xmzol .= $m4is_qnjfv['style'];
 } if ( $m4is_qnjfv['target_class'] > '' ) { $m4is_p4izs = $m4is_qnjfv['target_class'];
 } if ( trim( $m4is_z50f ) > '' ) { $m4is_tjg_9 = sprintf( '<div id="%s" class="%s" style="%s">%s</div>', $m4is_qnjfv['id'], $m4is_qnjfv['class'], $m4is_xmzol, $m4is_z50f );
  } $m4is_en2ve .= '<script type="text/javascript">';
 $m4is_en2ve .= 'jQuery(document).ready(function() { ';
 $m4is_en2ve .= '   jQuery("' . $m4is_p4izs . '")';
 if ($m4is_qnjfv['fadeout'] > 0) { $m4is_en2ve .= '.delay(' . $m4is_qnjfv['fadeout'] .')';
 $m4is_en2ve .= '.fadeOut(' . $m4is_qnjfv['fadehide'] . $m4is_qnjfv['fadeout_function'] . ')';
 } if ($m4is_qnjfv['delayshow'] > 0) { $m4is_en2ve .= '.delay(' . $m4is_qnjfv['delayshow'] . ')';
 $m4is_en2ve .= '.fadeIn(' . $m4is_qnjfv['fadeshow'] . $m4is_qnjfv['delayshow_function'] . ')' ;
 } if ($m4is_qnjfv['delayhide'] > 0) { $m4is_en2ve .= '.delay(' . $m4is_qnjfv['delayhide'] . ')';
 $m4is_en2ve .= '.fadeOut(' . $m4is_qnjfv['fadehide'] . $m4is_qnjfv['delayhide_function'] . ')' ;
 } $m4is_en2ve .= ";\n";
 $m4is_en2ve .= '});';
 $m4is_en2ve .= '</script>';
  return $m4is_en2ve . $m4is_tjg_9;
 }  static 
function m4is_iw46e( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return 'n/a';
 } return '';
 }  static 
function m4is_c8ij7( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return 'n/a';
 } $m4is__9dgw = isset( $_SESSION['memb_user']['autologin'] ) ? (bool) $_SESSION['memb_user']['autologin'] : false;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__9dgw );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f );
 return $m4is_z50f;
 }  static 
function m4is_gevb( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'txtfmt' => '', 'types' => '', 'not' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_cd8k = get_the_id();
 $m4is__v508 = array_filter( explode( ',', strtolower( $m4is_qnjfv['types'] ) ) );
 $m4is_a_hn = strtolower( get_post_type( $m4is_cd8k ) );
 if ( empty( $m4is__v508 ) ) { return $m4is_a_hn;
 } $m4is_oa_z = in_array( $m4is_a_hn, $m4is__v508 );
 $m4is_oa_z = empty( $m4is_qnjfv['not'] ) ? $m4is_oa_z : ! $m4is_oa_z;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_oa_z );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], '', '', '' );
 return $m4is_z50f;
 }  static 
function m4is_dmzxyv( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'htmlattr' => '', 'not' => '', 'post_id' => 0, 'postid' => 0, 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_qjy8 = false;
 if ( $m4is_qnjfv['post_id'] > 0 ) { $m4is_qnjfv['postid'] = $m4is_qnjfv['post_id'];
 } $m4is_qnjfv['postid'] = empty( $m4is_qnjfv['postid'] ) ? (int) get_the_ID() : (int) $m4is_qnjfv['postid'];
 $m4is_qnjfv['not'] = ! empty( $m4is_qnjfv['not'] );
 if ( stripos( $m4is_carw7y, '_not_' ) ) { $m4is_qnjfv['not'] = true;
 } if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { $m4is_qjy8 = true;
 } else { if ( $m4is_qnjfv['postid'] ) { $m4is_qjy8 = apply_filters( 'memberium_has_post_access', null, $m4is_qnjfv['postid'] );
 } } if ( $m4is_qnjfv['not'] ) { $m4is_qjy8 = ! $m4is_qjy8;
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_qjy8 );
 $m4is_z50f = m4is_crqo::m4is__go6j( true, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after'] );
 return $m4is_z50f;
 }  static 
function m4is_jn4rg7( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '') : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'contact_id' => 0, 'days' => '', 'debug' => false, 'hours' => '', 'htmlattr' => '', 'interval' => '', 'months' => '', 'tag_id' => '', 'txtfmt' => '', 'weeks' => '', 'years' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_mdz7 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'sync_tag_details' );
 if ( empty( $m4is_mdz7 ) ) { return '';
 } global $wpdb;
 $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is__8htld = false;
 $m4is_qnjfv['interval'] = empty( $m4is_qnjfv['hours'] ) ? $m4is_qnjfv['interval'] : $m4is_qnjfv['interval'] . " {$m4is_qnjfv['hours']} hours ";
 $m4is_qnjfv['interval'] = empty( $m4is_qnjfv['days'] ) ? $m4is_qnjfv['interval'] : $m4is_qnjfv['interval'] . " {$m4is_qnjfv['days']} days ";
 $m4is_qnjfv['interval'] = empty( $m4is_qnjfv['weeks'] ) ? $m4is_qnjfv['interval'] : $m4is_qnjfv['interval'] . " {$m4is_qnjfv['weeks']} weeks ";
 $m4is_qnjfv['interval'] = empty( $m4is_qnjfv['months'] ) ? $m4is_qnjfv['interval'] : $m4is_qnjfv['interval'] . " {$m4is_qnjfv['months']} months ";
 $m4is_qnjfv['interval'] = empty( $m4is_qnjfv['years'] ) ? $m4is_qnjfv['interval'] : $m4is_qnjfv['interval'] . " {$m4is_qnjfv['years']} years ";
 if ( empty( $m4is_qnjfv['contact_id'] ) || empty( $m4is_qnjfv['tag_id'] ) ||empty( $m4is_qnjfv['interval'] ) ) { return '';
 }  $m4is_e2kg = empty( $m4is_qnjfv['contact_id'] ) ? (int) m4is_wbc8os::m4is_jjgo() : (int) $m4is_qnjfv['contact_id'];
 $m4is_mb6gy = time();
 $m4is_zq0k = self::$m4is_bnd6ti->m4is_d14zr( 'appname' );
 $m4is_tovizk = 'SELECT `created` FROM %s WHERE `appname` = %s AND `contactid` = %d AND `tagid` = %d ;';
 $m4is_tovizk = $wpdb->prepare( $m4is_tovizk, MEMBERIUM_DB_CONTACTTAGS, $m4is_zq0k, $m4is_e2kg, $m4is_qnjfv['tag_id'] );
 $m4is_n7m21w = strtotime( $wpdb->get_var( $m4is_tovizk ) . ' + ' . $m4is_qnjfv['interval'] );
 if ( empty( $m4is_n7m21w ) ) { return '';
 } $m4is__8htld = $m4is_mb6gy >= $m4is_n7m21w;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( true, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after'] );
 return $m4is_z50f;
 }  static 
function m4is_t1m7( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'except_roles' => '', 'not' => '', 'roles' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_qnjfv['not'] = ! empty( $m4is_qnjfv['not'] );
 if ( stripos( $m4is_carw7y, '_not_' ) ) { $m4is_qnjfv['not'] = true;
 } $m4is_qnjfv['except_roles'] = array_filter( explode( ',', strtolower( trim( $m4is_qnjfv['except_roles'] ) ) ) );
 $m4is_qnjfv['roles'] = array_filter( explode( ',', strtolower( trim( $m4is_qnjfv['roles'] ) ) ) );
 $m4is_x0_hk = get_userdata( get_current_user_id() );
 $m4is_hj1v = is_a( $m4is_x0_hk, 'WP_User' ) ? $m4is_x0_hk->roles : [];
 $m4is_uwdfj = false;
 if ( empty( $m4is_qnjfv['roles'] ) && empty( $m4is_qnjfv['except_roles'] ) ) { return '';
 } if ( is_user_logged_in() ) { if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { $m4is_uwdfj = true;
 } else { $m4is_uwdfj = (boolean) ( count( array_intersect( $m4is_qnjfv['roles'], $m4is_hj1v ) ) == count( $m4is_qnjfv['roles'] ) );
 if ( $m4is_uwdfj ) { $m4is_uwdfj = ! (boolean) ( count( array_intersect( $m4is_qnjfv['except_roles'], $m4is_hj1v ) ) > 0 );
 } if ( $m4is_qnjfv['not'] ) { $m4is_uwdfj = ! $m4is_uwdfj;
 } } } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_l92l48( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'except_roles' => '', 'not' => '', 'roles' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_qnjfv['not'] = ! empty( $m4is_qnjfv['not'] );
 $m4is_qnjfv['not'] = stripos($m4is_carw7y, '_not_') ? true : $m4is_qnjfv['not'];
 $m4is_qnjfv['except_roles'] = array_filter( explode( ',', strtolower( trim( $m4is_qnjfv['except_roles'] ) ) ) );
 $m4is_qnjfv['roles'] = array_filter( explode( ',', strtolower( trim( $m4is_qnjfv['roles'] ) ) ) );
 $m4is_x0_hk = wp_get_current_user();
 $m4is_hj1v = ( is_a( $m4is_x0_hk, 'WP_User' ) ) ? $m4is_x0_hk->roles : [];
 $m4is_uwdfj = false;
 if ( empty( $m4is_qnjfv['roles'] ) && empty( $m4is_qnjfv['except_roles'] ) ) { return '';
 } if ( is_user_logged_in() ) { if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { $m4is_uwdfj = true;
 } else { $m4is_uwdfj = (boolean) ( count( array_intersect( $m4is_qnjfv['roles'], $m4is_hj1v ) ) > 0 );
 if ( $m4is_uwdfj ) { $m4is_uwdfj = ! (boolean) ( count( array_intersect( $m4is_qnjfv['except_roles'], $m4is_hj1v ) ) > 0 );
 } if ( $m4is_qnjfv['not'] ) { $m4is_uwdfj = ! $m4is_uwdfj;
 } } } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_v9jbft( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'contact_id' => 0, 'except_contact_ids' => '', 'not' => '', 'output' => '', 'tagid' => '', 'tagids' => '', 'tag_ids' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_e2kg = empty( $m4is_qnjfv['contact_id'] ) ? self::$m4is_bnd6ti->m4is_dpuy9() : $m4is_qnjfv['contact_id'];
 $m4is_iystd2 = array_filter( explode( ',', trim( $m4is_qnjfv['tagid'] . ',' . $m4is_qnjfv['tagids'] . ',' . $m4is_qnjfv['tag_ids'], ',' ) ) );
 $m4is_wd8fkq = ! empty( $m4is_qnjfv['not'] );
 $m4is_wd8fkq = stripos( $m4is_carw7y, '_not_' ) ? ! $m4is_wd8fkq : $m4is_wd8fkq;
 $m4is_qqlvtw = array_filter( explode( ',', $m4is_qnjfv['except_contact_ids'] ) );
 $m4is_uwdfj = false;
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 if ( ! $m4is_zts3 ) { if ( ! count( $m4is_iystd2 ) ) { return '';
 } if ( ! in_array( $m4is_e2kg, $m4is_qqlvtw ) ) { $m4is_uwdfj = $m4is_e2kg > 0 ? self::$m4is_bnd6ti->m4is_mhx6( $m4is_iystd2, $m4is_e2kg ) : false;
 } } $m4is_uwdfj = $m4is_zts3 ? true : $m4is_uwdfj;
 $m4is_uwdfj = $m4is_wd8fkq ? ! $m4is_uwdfj : $m4is_uwdfj;
 $m4is_z50f = empty( $m4is_qnjfv['output'] ) ? $m4is_z50f : $m4is_qnjfv['output'];
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_zziqp( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'category_id' => '', 'contact_id' => 0, 'debug' => false, 'except_contact_ids' => '', 'except_contactid' => '', 'except_tag_ids' => '', 'except_tagid' => '', 'min' => 1, 'not' => '', 'output' => '', 'tag_id' => '', 'tag_ids' => '', 'tagid' => '', 'tagids' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 $m4is_h7k8j = self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_wd8fkq = ! empty( $m4is_qnjfv['not'] );
 $m4is_wd8fkq = stripos( $m4is_carw7y, '_not_' ) ? ! $m4is_wd8fkq : $m4is_wd8fkq;
 $m4is_osi9 = trim( $m4is_qnjfv['tag_id'] . ',' . $m4is_qnjfv['tag_ids'] . ',' . $m4is_qnjfv['tagid'] . ',' . $m4is_qnjfv['tagids'] );
 $m4is_aqho2g = trim( $m4is_qnjfv['except_tagid'] . ',' . $m4is_qnjfv['except_tag_ids'] );
 $m4is_qqlvtw = trim( $m4is_qnjfv['except_contactid'] . ',' . $m4is_qnjfv['except_contact_ids'] );
 $m4is_e2kg = empty( $m4is_qnjfv['contact_id'] ) ? $m4is_h7k8j : $m4is_qnjfv['contact_id'];
 $m4is_uwdfj = $m4is_zts3;
 if ( $m4is_h7k8j == $m4is_e2kg ) { $m4is_mdqgk = isset( $_SESSION['keap'] ) ? $_SESSION : [];
 } else { $m4is_ig9p6 = m4is_bnrdbo::m4is_d3na( $m4is_e2kg );
 $m4is_mdqgk = $m4is_ig9p6 ? self::$m4is_bnd6ti->m4is_akz3( $m4is_ig9p6 ) : [];
 } if ( ! $m4is_zts3 ) { $m4is_qgrf = true;
 $m4is_td10bm = true;
 $m4is_crix3 = true;
 $m4is_r2vafp = true;
 if ( ! empty( $m4is_osi9 ) ) { $m4is_qgrf = self::$m4is_bnd6ti->m4is_sjmzx( $m4is_osi9, $m4is_mdqgk );
 } if ( ! empty( $m4is_aqho2g ) ) { $m4is_td10bm = ! self::$m4is_bnd6ti->m4is_sjmzx( $m4is_aqho2g, $m4is_mdqgk );
 } if ( ! empty( $m4is_qqlvtw ) ) { $m4is_qnjfv['except_contactids'] = array_filter( explode( ',', $m4is_qqlvtw) );
 if ( count( $m4is_qnjfv['except_contactids'] ) && in_array( $m4is_qnjfv['contact_id'], $m4is_qnjfv['except_contactids'] ) ) { $m4is_crix3 = false;
 } } if ( ! empty( $m4is_qnjfv['category_id'] ) ) { $m4is_r2vafp = self::$m4is_bnd6ti->m4is_f80gv3( $m4is_qnjfv['category_id'], $m4is_mdqgk );
 } $m4is_uwdfj = ( $m4is_qgrf === true ) && ( $m4is_td10bm === true ) && ( $m4is_crix3 === true ) && ( $m4is_r2vafp === true );
 if ( $m4is_uwdfj && $m4is_qnjfv['min'] > 1 ) { $m4is_qetrg = array_filter( explode( ',', $m4is_osi9 ) );
 $m4is_vwdb4 = array_filter( explode( ',', m4is_wbc8os::m4is_sfnmc( 'groups' ) ) );
 $m4is_idce = array_filter( $m4is_vwdb4 );
 $m4is_v64e = 0;
 foreach( $m4is_idce as $m4is_d6whb ) { if ( in_array( $m4is_d6whb, $m4is_qetrg ) ) { $m4is_v64e++;
 } } if ( $m4is_v64e < $m4is_qnjfv['min'] ) { $m4is_uwdfj = false;
 } } $m4is_uwdfj = $m4is_wd8fkq ? ! $m4is_uwdfj : $m4is_uwdfj;
 } $m4is_z50f = empty( $m4is_qnjfv['output'] ) ? $m4is_z50f : $m4is_qnjfv['output'];
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_u2mf0( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'caseinsensitive' => 'yes', 'not' => '', 'test' => '=', 'output' => '', 'txtfmt' => '', 'value1' => '', 'value2' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_wd8fkq = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['not'], false );
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 $m4is_k0_k6o = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['caseinsensitive'], true );
 $m4is_z50f = empty( $m4is_qnjfv['output'] ) ? $m4is_z50f : $m4is_qnjfv['output'];
 $m4is__8htld = m4is_crqo::m4is_l0cy( $m4is_qnjfv['value1'], $m4is_qnjfv['test'], $m4is_qnjfv['value2'], $m4is_k0_k6o );
 $m4is__8htld = $m4is_zts3 ? true : $m4is__8htld;
 $m4is__8htld = $m4is_wd8fkq ? ! $m4is__8htld : $m4is__8htld;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( true, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_oz4c( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'not' => '', 'output' => '', 'tokens' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_wd8fkq = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['not'], false );
 $m4is_zc_qlk = trim( $m4is_qnjfv['tokens'], ',' );
 $m4is_ig9p6 = get_current_user_id();
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 $m4is_wd8fkq = stripos( $m4is_carw7y, '_not_' ) ? ! $m4is_wd8fkq : $m4is_wd8fkq;
 $m4is_uwdfj = false;
 if ( $m4is_zts3 ) { $m4is_uwdfj = true;
 } elseif ($m4is_ig9p6 < 1) { $m4is_uwdfj = false;
 } elseif ( empty( $m4is_zc_qlk ) ) { $m4is_uwdfj = false;
 } else { $m4is_uwdfj = self::$m4is_bnd6ti->m4is_w3ilk( $m4is_zc_qlk, $m4is_ig9p6 );
 } $m4is_uwdfj = $m4is_wd8fkq ? ! $m4is_uwdfj : $m4is_uwdfj;
 $m4is_z50f = empty( $m4is_qnjfv['output'] ) ? $m4is_z50f : $m4is_qnjfv['output'];
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_k7v4( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '') : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'levels' => '', 'strict' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_uwdfj = false;
 $m4is_nqoin = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['strict'], false );
 $m4is_e2kg = self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 if ( $m4is_zts3 ) { $m4is_uwdfj = true;
 } if ( $m4is_e2kg ) { $m4is_uwdfj = self::$m4is_bh12zy->m4is_lp275a( $m4is_qnjfv['strict'], $m4is_qnjfv['levels'] );
 } $m4is_uwdfj = $m4is_zts3 ? true : $m4is_uwdfj;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_lnj8ob( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'except_contact_ids' => '', 'except_contactid' => '', 'except_tag_ids' => '', 'except_tagid' => '', 'tagid' => '', 'tag_ids' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_e2kg = self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 $m4is_aqho2g = $m4is_qnjfv['except_tagid'] = trim( $m4is_qnjfv['except_tagid'] . ',' . $m4is_qnjfv['except_tag_ids'], ', ' );
 $m4is_qqlvtw = $m4is_qnjfv['except_contactid'] = trim( $m4is_qnjfv['except_contactid'] . ',' . $m4is_qnjfv['except_contact_ids'], ', ' );
 $m4is_osi9 = $m4is_qnjfv['tagid'] = trim( $m4is_qnjfv['tagid'] . ',' . $m4is_qnjfv['tag_ids'], ', ' );
 if ( empty( $m4is_osi9 ) ) { return '';
 } $m4is_uwdfj = $m4is_e2kg ? self::$m4is_bnd6ti->m4is_sjmzx( $m4is_osi9 ) : false;
 if ( $m4is_uwdfj ) { $m4is_qqlvtw = array_filter( explode( ',', $m4is_qqlvtw ) );
 if ( count( $m4is_qqlvtw ) && in_array( $m4is_e2kg, $m4is_qqlvtw ) ) { $m4is_uwdfj = false;
 } } if ( $m4is_uwdfj ) { if ( $m4is_aqho2g > '' && self::$m4is_bnd6ti->m4is_sjmzx( $m4is_aqho2g ) ) { $m4is_uwdfj = false;
 } } $m4is_uwdfj = $m4is_zts3 ? true : $m4is_uwdfj;
 $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, ! $m4is_uwdfj );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_av12wm( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'caseinsensitive' => true, 'key' => '', 'test' => '=', 'txtfmt' => '', 'value' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_k0_k6o = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['caseinsensitive'], false );
 $m4is_s2ge5 = trim( $m4is_qnjfv['key'] );
 $m4is_lixqnk = trim( $m4is_qnjfv['test'] );
 $m4is_w_o7al = trim( $m4is_qnjfv['value'] );
 if ( empty( $m4is_s2ge5 ) ) { return '';
 } if ( empty( $m4is_w_o7al ) && $m4is_qnjfv['test'] == '=' ) { $m4is__8htld = isset( $_COOKIE[$m4is_s2ge5] );
 } else { $m4is_p2fls7 = isset( $_COOKIE[$m4is_s2ge5] ) ? trim( $_COOKIE[$m4is_s2ge5] ) : '';
 $m4is__8htld = m4is_crqo::m4is_l0cy( $m4is_p2fls7, $m4is_lixqnk, $m4is_w_o7al, $m4is_k0_k6o );
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_jkgc_( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'caseinsensitive' => true, 'key' => '', 'test' => '=', 'txtfmt' => '', 'value' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_k0_k6o = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['caseinsensitive'], false );
 $m4is_s2ge5 = trim( $m4is_qnjfv['key'] );
 $m4is_lixqnk = trim( $m4is_qnjfv['test'] );
 $m4is_w_o7al = trim( $m4is_qnjfv['value'] );
 if ( empty( $m4is_s2ge5 ) ) { return '';
 } if ( empty( $m4is_w_o7al ) && $m4is_lixqnk == '=') { $m4is__8htld = isset( $_GET[$m4is_s2ge5] );
 } else { $m4is_eosu = isset( $_GET[$m4is_s2ge5] ) ? trim( $_GET[$m4is_s2ge5] ) : '';
 $m4is__8htld = m4is_crqo::m4is_l0cy( $m4is_eosu, $m4is_lixqnk, $m4is_w_o7al, $m4is_k0_k6o );
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, TRUE, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_elkg( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'caseinsensitive' => true, 'key' => '', 'test' => '=', 'txtfmt' => '', 'value' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_k0_k6o = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['caseinsensitive'], false );
 $m4is_s2ge5 = trim( $m4is_qnjfv['key'] );
 $m4is_lixqnk = trim( $m4is_qnjfv['test'] );
 $m4is_w_o7al = trim( $m4is_qnjfv['value'] );
 if ( empty( $m4is_s2ge5 ) ) { return '';
 } if ( empty( $m4is_w_o7al ) && $m4is_lixqnk == '=' ) { $m4is__8htld = isset( $_POST[$m4is_s2ge5] );
 } else { $m4is_bx586 = isset( $_POST[$m4is_s2ge5] ) ? trim( $_POST[$m4is_s2ge5] ) : '';
 $m4is__8htld = m4is_crqo::m4is_l0cy( $m4is_bx586, $m4is_lixqnk, $m4is_w_o7al, $m4is_k0_k6o );
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, TRUE, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_y457bn( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'caseinsensitive' => true, 'key' => '', 'test' => '=', 'txtfmt' => '', 'value' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_k0_k6o = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['caseinsensitive'], false );
 $m4is_s2ge5 = trim( $m4is_qnjfv['key'] );
 $m4is_lixqnk = trim( $m4is_qnjfv['test'] );
 $m4is_w_o7al = trim( $m4is_qnjfv['value'] );
 if ( empty( $m4is_s2ge5 ) ) { return '';
 } if ( empty( $m4is_w_o7al ) && $m4is_lixqnk == '=' ) { $m4is__8htld = isset( $_REQUEST[$m4is_s2ge5] );
 } else { $m4is_zdzl4t = isset( $_REQUEST[$m4is_s2ge5] ) ? $_REQUEST[$m4is_s2ge5] : '';
 $m4is__8htld = m4is_crqo::m4is_l0cy( $m4is_zdzl4t, $m4is_lixqnk, $m4is_w_o7al, $m4is_k0_k6o );
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, TRUE, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is__n1vep( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'name' => '', 'test' => 'show', 'txtfmt' => '', 'val' => 0, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_ig9p6 = get_current_user_id();
 if ( empty( $m4is_ig9p6 ) ) { return '';
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_t5ot4 = strtolower( trim( $m4is_qnjfv['name'] ) );
 $m4is_lixqnk = strtolower( trim( $m4is_qnjfv['test'] ) );
 $m4is_w_o7al = (float) $m4is_qnjfv['val'];
 $m4is_glto1 = (float) self::$m4is_bh12zy->m4is_kxc1( $m4is_t5ot4 );
 $m4is__8htld = FALSE;
 if ( in_array( $m4is_lixqnk, ['eq', '=', '==', '==='] ) ) { $m4is__8htld = ( $m4is_glto1 === $m4is_w_o7al );
 } elseif ( $m4is_lixqnk == 'gt' ) { $m4is__8htld = $m4is_glto1 > $m4is_w_o7al;
 } elseif ($m4is_lixqnk == 'lt') { $m4is__8htld = $m4is_glto1 < $m4is_w_o7al;
 } elseif ($m4is_lixqnk == 'le') { $m4is__8htld = $m4is_glto1 <= $m4is_w_o7al;
 } elseif ($m4is_lixqnk == 'ge') { $m4is__8htld = $m4is_glto1 >= $m4is_w_o7al;
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, TRUE, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_nr4jys( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'browser' => '', 'capture' => '', 'os' => '', 'txtfmt' => '', 'type' => '', 'user' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_tz42r0 = true;
 $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_pkr8a = m4is_w0enbm::m4is_e5l8a9()->m4is_blxh( $_SERVER['HTTP_USER_AGENT'] );
 $m4is_u6_yx = $m4is_qnjfv['browser'] = strtolower( trim( $m4is_qnjfv['browser'] ) );
 $m4is_jf7m2 = $m4is_qnjfv['os'] = strtolower( trim( $m4is_qnjfv['os'] ) );
 $m4is_u23rl = $m4is_qnjfv['type'] = strtolower( trim( $m4is_qnjfv['type'] ) );
 $m4is_x0_hk = $m4is_qnjfv['user'] = strtolower( trim( $m4is_qnjfv['user'] ) );
 if ( ! empty( $m4is_u6_yx ) && $m4is_u6_yx !== $m4is_pkr8a['browser'] ) { $m4is_tz42r0 = false;
 } if ( ! empty( $m4is_jf7m2 ) && $m4is_jf7m2 !== $m4is_pkr8a['os' ]) { $m4is_tz42r0 = false;
 } if ( ! empty( $m4is_u23rl ) && $m4is_u23rl != $m4is_pkr8a['type'] ) { $m4is_tz42r0 = false;
 } if ( ! empty( $m4is_x0_hk ) && $m4is_qnjfv['user'] != $m4is_pkr8a['user']) { $m4is_tz42r0 = false;
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_tz42r0 );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_tx3r5( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return;
 } $m4is_r6nh_b = [ 'capture' => '', 'date_format' => 'F jS, Y', 'date' => '', 'days' => 0, 'months' => 0, 'tagids' => '', 'txtfmt' => '', 'weeks' => 0, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is__8htld = false;
 $m4is_zts3 = self::$m4is_bnd6ti->m4is_lvmz1b();
 $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_iystd2 = array_filter( explode( ',', trim( $m4is_qnjfv['tagids'] ) ) );
 $m4is_vx9i7 = $m4is_qnjfv['date'];
 $m4is_dckze = (int) $m4is_qnjfv['days'];
 $m4is_z1ne = (int) $m4is_qnjfv['weeks'];
 $m4is_ebqp = (int) $m4is_qnjfv['months'];
 $m4is_dckze = $m4is_dckze + ( $m4is_z1ne * 7 ) + ( $m4is_ebqp * 30 );
 if ( $m4is_dckze < 1 && empty( $m4is_qnjfv['date'] ) ) { return;
 } if ( $m4is_zts3 ) { $m4is__8htld = true;
 } else { if ( empty( $m4is_vx9i7 ) ) { $m4is_vx9i7 = get_userdata( get_current_user_id() )->user_registered;
 } if ( $m4is_dckze ) { $m4is_ip2xt = strtotime( sprintf( '%s + %s days', $m4is_vx9i7, $m4is_dckze ) );
 } else { $m4is_ip2xt = strtotime( $m4is_vx9i7 );
 } if ( $m4is_ip2xt < time() ) { $m4is__8htld = true;
 if ( ! empty( $m4is_iystd2 ) ) { if ( ! self::$m4is_bnd6ti->m4is_sjmzx( $m4is_iystd2 ) ) { $m4is__8htld = false;
 } } } else { $m4is__8htld = false;
 } } if ( $m4is__8htld ) { $m4is_z50f = str_ireplace( '{{:date:}}', date( $m4is_qnjfv['date_format'], $m4is_ip2xt ), $m4is_z50f );
 $m4is_wgj6i = (int) ( ($m4is_ip2xt - time() ) / 86400 );
 $m4is_wgj6i .= $m4is_wgj6i > 1 ? ' days' : ' day';
 $m4is_z50f = str_ireplace( '{{:days:}}', $m4is_wgj6i, $m4is_z50f );
 $m4is_kj3vs1 = (int) ( ($m4is_ip2xt - time() ) / ( 7 * 86400 ) );
 $m4is_kj3vs1 .= $m4is_kj3vs1 > 1 ? ' weeks' : ' week';
 $m4is_z50f = str_ireplace( '{{:weeks:}}', $m4is_kj3vs1, $m4is_z50f );
 $m4is_uu082 = (int) ( ($m4is_ip2xt - time() ) / ( 30 * 86400 ) );
 $m4is_uu082 .= $m4is_uu082 > 1 ? ' months' : ' month';
 $m4is_z50f = str_ireplace( '{{:months:}}', $m4is_uu082, $m4is_z50f );
 $m4is_wgj6i = intval( ( $m4is_ip2xt - time() - ( 7 * 86400 * $m4is_kj3vs1 ) ) / 86400 );
 $m4is_wgj6i .= $m4is_wgj6i > 1 ? ' days' : ' day';
 $m4is_z50f = str_ireplace('{{:compoundtime:}}', $m4is_kj3vs1 . ' and ' . $m4is_wgj6i, $m4is_z50f);
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, TRUE, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_o_aeq5( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'date_format' => 'F jS, Y', 'end' => '', 'start' => '', 'tagids' => '', 'txtfmt' => '', 'tz' => get_option( 'timezone_string' ), ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_e06y = $m4is_qnjfv['start'];
 $m4is_gdyr = $m4is_qnjfv['end'];
 $m4is_iystd2 = array_filter( explode( ',', trim( $m4is_qnjfv['tagids'] ) ) );
 $m4is_vo3u = in_array( $m4is_qnjfv['tz'], timezone_identifiers_list() ) ? $m4is_qnjfv['tz'] : get_option( 'timezone_string' );
 $m4is_l58i1o = date_default_timezone_get();
 $m4is_mb6gy = time();
 $m4is__8htld = false;
 if ( ! empty( $m4is_vo3u ) ) { date_default_timezone_set( $m4is_vo3u );
 } $m4is_pjkx2b = (int) strtotime( $m4is_e06y );
 $m4is_gjlo8 = strtotime( $m4is_gdyr ) ? (int) strtotime( $m4is_gdyr ) : $m4is_mb6gy + 1;
 date_default_timezone_set( $m4is_l58i1o );
 $m4is__8htld = ( $m4is_mb6gy > $m4is_pjkx2b && $m4is_mb6gy < $m4is_gjlo8 );
  if ( ! empty( $m4is_iystd2 ) ) { $m4is__8htld = $m4is__8htld && self::$m4is_bnd6ti->m4is_sjmzx( $m4is_iystd2 );
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, TRUE, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 }  static 
function m4is_k1do( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'date_format' => 'F jS, Y', 'date' => '', 'days' => 0, 'months' => 0, 'tagids' => '', 'txtfmt' => '', 'weeks' => 0, 'years' => 0, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is__8htld = false;
 $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_vx9i7 = trim( $m4is_qnjfv['date'] );
 $m4is_iystd2 = array_filter( explode( ',', trim( $m4is_qnjfv['tagids'] ) ) );
 $m4is_dckze = (int) $m4is_qnjfv['days'];
 $m4is_ebqp = (int) $m4is_qnjfv['months'];
 $m4is_z1ne = (int) $m4is_qnjfv['weeks'];
 $m4is_hhn_ = (int) $m4is_qnjfv['years'];
 $m4is_dckze = $m4is_dckze + ( $m4is_z1ne * 7 ) + ( $m4is_ebqp * 30) + ( $m4is_hhn_ * 365 );
 if ( empty( $m4is_vx9i7 ) ) { $m4is_vx9i7 = get_userdata( get_current_user_id() )->user_registered;
 $m4is_ip2xt = strtotime( sprintf( '% + %s days', $m4is_vx9i7, $m4is_dckze ) );
 } else { $m4is_ip2xt = strtotime( $m4is_vx9i7 );
 } $m4is__8htld = ( $m4is_ip2xt > time() );
 if (! empty( $m4is_iystd2 ) ) { $m4is__8htld = $m4is__8htld && self::$m4is_bnd6ti->m4is_sjmzx( $m4is_iystd2 );
 } if ( $m4is__8htld ) { $m4is_z50f = str_ireplace( '{{:date:}}', date( $m4is_qnjfv['date_format'], $m4is_ip2xt ), $m4is_z50f );
 $m4is_wgj6i = (int) ( ( $m4is_ip2xt - time() ) / DAY_IN_SECONDS );
 $m4is_wgj6i .= $m4is_wgj6i > 1 ? ' days' : ' day';
 $m4is_z50f = str_ireplace( '{{:days:}}', $m4is_wgj6i, $m4is_z50f );
 $m4is_kj3vs1 = (int) ( ( $m4is_ip2xt - time() ) / ( WEEK_IN_SECONDS ) );
 $m4is_kj3vs1 .= $m4is_kj3vs1 > 1 ? ' weeks' : ' week';
 $m4is_z50f = str_ireplace( '{{:weeks:}}', $m4is_kj3vs1, $m4is_z50f );
 $m4is_uu082 = (int) ( ( $m4is_ip2xt - time() ) / ( 30 * DAY_IN_SECONDS ) );
 $m4is_uu082 .= $m4is_uu082 > 1 ? ' months' : ' month';
 $m4is_z50f = str_ireplace('{{:months:}}', $m4is_uu082, $m4is_z50f);
 $m4is_kj3vs1 = intval( ( $m4is_ip2xt - time() - (7 * DAY_IN_SECONDS * $m4is_kj3vs1) ) / 86400 );
 $m4is_kj3vs1 .= $m4is_kj3vs1 > 1 ? ' days' : ' day';
 $m4is_z50f = str_ireplace( '{{:compoundtime:}}', $m4is_kj3vs1 . ' and ' . $m4is_wgj6i, $m4is_z50f );
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is__8htld );
 $m4is_z50f = m4is_crqo::m4is__go6j( false, $m4is_z50f, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 return $m4is_z50f;
 } }

