<?php
/**
 * Copyright (c) 2017-2024 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists('m4is_pms8y') || die();
 m4is_eo51::m4is_ju94();
 final 
class m4is_eo51 { private static $m4is_wo48;
 private static $m4is_bnd6ti;
 private static $m4is_toz0;
  static 
function m4is_ju94() { self::$m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 self::$m4is_wo48 = 4;
 }    public static 
function m4is_o41l0b( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string { if (! m4is_u68pu::m4is_u6mkaw() ) { return '';
 }  $m4is__8lax = $m4is_qnjfv;
 $m4is_qnjfv['profile'] = isset($m4is_qnjfv['profile']) ? strtolower(trim($m4is_qnjfv['profile'])) : 'us-east-1';
 $m4is_jpmo8l = self::m4is_y4lkf($m4is_qnjfv['profile']);
  if ($m4is_jpmo8l) { $m4is_gvpi6 = $m4is_qnjfv['profile'];
 $m4is_rn2wuj = $m4is_jpmo8l['bucket'];
 $m4is_x8ile = (int) $m4is_jpmo8l['expiration'];
 $m4is_nymjfo = $m4is_jpmo8l['host'];
 $m4is_hng4z = empty($m4is_jpmo8l['region']) ? '' : $m4is_jpmo8l['region'];
 $m4is_s8owzt = $m4is_jpmo8l['access_key'];
 $m4is__nzp = $m4is_jpmo8l['secret_key'];
 } else { $m4is_gvpi6 = '';
 $m4is_rn2wuj = '';
 $m4is_x8ile = 5;
 $m4is_hng4z = 'us-east-1';
 $m4is_nymjfo = '';
 $m4is_s8owzt = '';
 $m4is__nzp = '';
 } $m4is_r6nh_b = [ 'action_ids' => '',  'after' => '', 'before' => '', 'bucket' => $m4is_rn2wuj, 'debug' => 0, 'direct_link' => 'no',  'expiring' => $m4is_x8ile, 'fus_ids' => '',  'goals' => '', 'htmlattr' => '', 'object' => '', 'profile' => $m4is_gvpi6, 'protocol' => 'https', 'region' => $m4is_hng4z, 'require_login' => 'no',  'tag_ids' => '', 'tokens' => '', 'version' => self::$m4is_wo48,  'class' => '', 'download' => '', 'id' => '', 'rel' => '', 'style' => '', 'target' => '', 'type' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_uzfw8j = '';
  if ( strtolower( trim( $m4is_qnjfv['direct_link']) ) == 'no' ) { $m4is_z3nrs5 = empty($_SERVER['REQUEST_URI']) ? '' : $_SERVER['REQUEST_URI'];
 $m4is_v6fdv4 = [];
 $m4is_v6fdv4['actionset'] = $m4is_qnjfv['action_ids'];
 $m4is_v6fdv4['debug'] = $m4is_qnjfv['debug'];
 $m4is_v6fdv4['expiring'] = $m4is_qnjfv['expiring'];
 $m4is_v6fdv4['fus'] = $m4is_qnjfv['fus_ids'];
 $m4is_v6fdv4['goals'] = $m4is_qnjfv['goals'];
 $m4is_v6fdv4['object'] = $m4is_qnjfv['object'];
 $m4is_v6fdv4['profile'] = $m4is_qnjfv['profile'];
 $m4is_v6fdv4['protocol'] = $m4is_qnjfv['protocol'];
 $m4is_v6fdv4['region'] = $m4is_qnjfv['region'];
 $m4is_v6fdv4['require_login'] = $m4is_qnjfv['require_login'];
 $m4is_v6fdv4['tags'] = $m4is_qnjfv['tag_ids'];
 $m4is_v6fdv4['tokens'] = $m4is_qnjfv['tokens'];
 $m4is_v6fdv4['version'] = $m4is_qnjfv['version'];
 if (strpos($m4is_z3nrs5, '?') === false) { $m4is_z3nrs5 .= '?';
 } else { $m4is_z3nrs5 .= '&';
 } $m4is_rbwn1z = base64_encode( serialize( $m4is_v6fdv4 ) );
 $m4is_imdo6 = 'memb_s3link=' . $m4is_rbwn1z;
  $m4is_t5ot4 = 'verification';
 $m4is_v6fdv4 = $m4is_rbwn1z;
 $action_url = wp_nonce_url($m4is_imdo6, $m4is_v6fdv4, $m4is_t5ot4);
   $m4is_rlp0 = $m4is_z3nrs5 . $action_url;
 } else { if ($m4is_qnjfv['version'] == 3) { $m4is_rlp0 = self::m4is_ljq65i($m4is_s8owzt, $m4is__nzp, $m4is_qnjfv['protocol'], $m4is_nymjfo, $m4is_qnjfv['bucket'], $m4is_qnjfv['object'], $m4is_qnjfv['expiring']);
 } elseif ($m4is_qnjfv['version'] == 4) {  $m4is_rlp0 = self::m4is_fqvu($m4is_s8owzt, $m4is__nzp, $m4is_qnjfv['bucket'], $m4is_qnjfv['object'], $m4is_qnjfv['expiring'], $m4is_qnjfv['region']);
 } } if (strtolower($m4is_qnjfv['htmlattr']) == 'all') { $m4is_g7fr = [ 'action_ids', 'after', 'before', 'bucket', 'debug', 'direct_link', 'expiring', 'fus_ids', 'goals', 'htmlattr', 'object', 'profile', 'protocol', 'require_login', 'tag_ids', 'tokens', ];
 $m4is_uzfw8j = '<a href="' . $m4is_rlp0 . '"';
 foreach($m4is__8lax as $m4is_c5zg => $m4is_g0wy) { if (! empty($m4is__8lax[$m4is_c5zg]) && ! in_array($m4is_c5zg, $m4is_g7fr) ) { $m4is_uzfw8j .= ' ' . $m4is_c5zg . '="' . $m4is_g0wy . '" ';
 } } $m4is_uzfw8j .= '>' . $m4is_z50f . '</a>';
 $m4is_qnjfv['htmlattr'] = '';
 } else { $m4is_uzfw8j = $m4is_rlp0;
 } return m4is_crqo::m4is__go6j( false, $m4is_uzfw8j, '', '', $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after'] );
 } public static 
function m4is_wndx($m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string { if ( ! m4is_u68pu::m4is_u6mkaw() ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 if ( is_feed() ) { return '';
 } $m4is__8lax = $m4is_qnjfv;
 $m4is_qnjfv['profile'] = isset($m4is_qnjfv['profile']) ? strtolower(trim($m4is_qnjfv['profile'])) : 'us-east-1';
 $m4is_jpmo8l = self::m4is_y4lkf($m4is_qnjfv['profile']);
  if ($m4is_jpmo8l) { $m4is_gvpi6 = $m4is_qnjfv['profile'];
 $m4is_rn2wuj = $m4is_jpmo8l['bucket'];
 $m4is_x8ile = (int) $m4is_jpmo8l['expiration'];
 $m4is_nymjfo = $m4is_jpmo8l['host'];
 $m4is_hng4z = $m4is_jpmo8l['region'];
 $m4is_s8owzt = $m4is_jpmo8l['access_key'];
 $m4is__nzp = $m4is_jpmo8l['secret_key'];
 } else { $m4is_gvpi6 = '';
 $m4is_rn2wuj = '';
 $m4is_x8ile = 5;
 $m4is_hng4z = 'us-east-1';
 $m4is_nymjfo = '';
 $m4is_s8owzt = '';
 $m4is__nzp = '';
 } static $m4is_bq_t = 0;
 $m4is_bq_t++;
 $m4is_r6nh_b = [ 'autoplay' => '', 'bucket' => $m4is_rn2wuj, 'controls' => '', 'direct_link' => 'no',  'download' => 0, 'expiring' => $m4is_x8ile, 'height' => 0, 'loop' => '', 'muted' => '', 'object' => '', 'poster' => '', 'preload' => '', 'profile' => $m4is_gvpi6, 'protocol' => 'https', 'region' => $m4is_hng4z, 'require_login' => 'no',  'version' => 3,  'src' => '', 'width' => 0, ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_kjxmq = '';
 $m4is_tjg_9 = '';
 if ($m4is_qnjfv['version'] == 3) { $m4is_imdo6 = self::m4is_ljq65i($m4is_s8owzt, $m4is__nzp, $m4is_qnjfv['protocol'], $m4is_nymjfo, $m4is_qnjfv['bucket'], $m4is_qnjfv['object'], $m4is_qnjfv['expiring']);
 } elseif ($m4is_qnjfv['version'] == 4) {  $m4is_imdo6 = self::m4is_fqvu($m4is_s8owzt, $m4is__nzp, $m4is_rn2wuj, $m4is_zuyvpd, $m4is_qg0b9n = 0, $m4is_hng4z, $m4is_vrw6c = [] );
 } $m4is_x05f = ($m4is_qnjfv['width'] > 0) ? ' style="width:' . $m4is_qnjfv['width'] . 'px;" ': '';
 $m4is_tjg_9 .= '<div '. $m4is_x05f .' class="wp-video">';
 $m4is_tjg_9 .= '<audio class="wp-audio-shortcode" id="secureaudio-' . $m4is_bq_t . '" ';
 if ($m4is_qnjfv['width'] > 0) { $m4is_tjg_9 .= ' width="' . $m4is_qnjfv['width'] . '" ';
 } if ($m4is_qnjfv['height'] > 0) { $m4is_tjg_9 .= ' height="' . $m4is_qnjfv['height'] . '" ';
 } if ($m4is_qnjfv['preload'] > '') { $m4is_tjg_9 .= ' autobuffer="autobuffer" preload="' . $m4is_qnjfv['preload'] . '" ';
 } if ($m4is_qnjfv['controls'] > '') { $m4is_tjg_9 .= ' controls="controls" ';
 } if ($m4is_qnjfv['autoplay'] > '') { $m4is_tjg_9 .= ' autoplay="autoplay" ';
 } if ($m4is_qnjfv['muted'] > '') { $m4is_tjg_9 .= ' muted="muted" ';
 } if ($m4is_qnjfv['poster'] > '') { $m4is_tjg_9 .= ' poster="' . $m4is_qnjfv['poster'] . '" ';
 } if (! empty($m4is_qnjfv['loop']) ) { $m4is_tjg_9 .= ' loop="' . $m4is_qnjfv['loop'] . '" ';
 } if (! $m4is_qnjfv['download']) { $m4is_tjg_9 .= ' controlsList="nodownload" ';
 } $m4is_tjg_9 .= '>';
 $m4is_tjg_9 .= '<source src="' . $m4is_imdo6 .'" />';
 $m4is_tjg_9 .= '</audio></div>';
 return $m4is_tjg_9;
 } public static 
function m4is_vy0w($m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string { if (! m4is_u68pu::m4is_u6mkaw() ) { return '';
 } if (is_feed() ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 static $m4is_bq_t = 0;
 $m4is_bq_t++;
 $m4is_qnjfv['profile'] = isset($m4is_qnjfv['profile']) ? strtolower(trim($m4is_qnjfv['profile'])) : 'us-east-1';
 $m4is_jpmo8l = self::m4is_y4lkf($m4is_qnjfv['profile']);
 $m4is_x05f = '';
 if ($m4is_jpmo8l) { $m4is_gvpi6 = $m4is_qnjfv['profile'];
 $m4is_rn2wuj = $m4is_jpmo8l['bucket'];
 $m4is_x8ile = (int) $m4is_jpmo8l['expiration'];
 $m4is_nymjfo = $m4is_jpmo8l['host'];
 $m4is_hng4z = $m4is_jpmo8l['region'];
 $m4is_s8owzt = $m4is_jpmo8l['access_key'];
 $m4is__nzp = $m4is_jpmo8l['secret_key'];
 } else { $m4is_gvpi6 = '';
 $m4is_rn2wuj = '';
 $m4is_x8ile = 5;
 $m4is_hng4z = 'us-east-1';
 $m4is_nymjfo = '';
 $m4is_s8owzt = '';
 $m4is__nzp = '';
 } $m4is_r6nh_b = [ 'autoplay' => '', 'bucket' => $m4is_rn2wuj, 'controls' => '', 'direct_link' => 'no',  'expiring' => $m4is_x8ile, 'height' => 0, 'loop' => '', 'muted' => '', 'object' => '', 'poster' => '', 'preload' => '', 'profile' => $m4is_gvpi6, 'protocol' => 'https', 'require_login' => 'no',  'src' => '', 'version' => 3,  'width' => 0, ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
  $m4is_kjxmq = '';
 $m4is_tjg_9 = '';
   if (false && strtolower(trim($m4is_qnjfv['direct_link']) ) == 'no') {  } else { if ($m4is_qnjfv['version'] == 3) { $m4is_imdo6 = self::m4is_ljq65i($m4is_s8owzt, $m4is__nzp, $m4is_qnjfv['protocol'], $m4is_nymjfo, $m4is_qnjfv['bucket'], $m4is_qnjfv['object'], $m4is_qnjfv['expiring']);
 } elseif ($m4is_qnjfv['version'] == 4) {  $m4is_imdo6 = self::m4is_fqvu($m4is_s8owzt, $m4is__nzp, $m4is_rn2wuj, $m4is_zuyvpd, $m4is_qg0b9n = 0, $m4is_hng4z = 'us-east-1', $m4is_vrw6c = [] );
 } } if ($m4is_qnjfv['width'] > 0) { $m4is_x05f = ' style="width:' . $m4is_qnjfv['width'] . 'px;" ';
 } $m4is_tjg_9 .= '<div '. $m4is_x05f .' class="wp-video">';
 $m4is_tjg_9 .= '<video class="wp-video-shortcode" id="securevideo-' . $m4is_bq_t . '" ';
 if ($m4is_qnjfv['width'] > 0) { $m4is_tjg_9 .= ' width="' . $m4is_qnjfv['width'] . '" ';
 } if ($m4is_qnjfv['height'] > 0) { $m4is_tjg_9 .= ' height="' . $m4is_qnjfv['height'] . '" ';
 } if ($m4is_qnjfv['preload'] > '') { $m4is_tjg_9 .= ' autobuffer="autobuffer" preload="' . $m4is_qnjfv['preload'] . '" ';
 } if ($m4is_qnjfv['controls'] > '') { $m4is_tjg_9 .= ' controls="controls" ';
 } if ($m4is_qnjfv['autoplay'] > '') { $m4is_tjg_9 .= ' autoplay="autoplay" ';
 } if ($m4is_qnjfv['muted'] > '') { $m4is_tjg_9 .= ' muted="muted" ';
 } if ($m4is_qnjfv['poster'] > '') { $m4is_tjg_9 .= ' poster="' . $m4is_qnjfv['poster'] . '" ';
 } if ($m4is_qnjfv['loop'] > '') { $m4is_tjg_9 .= ' loop="' . $m4is_qnjfv['loop'] . '" ';
 } $m4is_tjg_9 .= '>';
 $m4is_tjg_9 .= '<source src="' . $m4is_imdo6 .'" />';
 $m4is_tjg_9 .= '</video></div>';
 return $m4is_tjg_9;
 }    public static 
function m4is_t1i6w() : void { m4is_aoxw::m4is_djr4nd();
 if ( ! wp_verify_nonce( $_GET['verification'], $_GET['memb_s3link'] ) ) { return;
 } if ( is_feed() ) { return;
 } $m4is_i9a1gn = function_exists( 'is_user_logged_in' ) && is_user_logged_in();
 $m4is_ig9p6 = $m4is_i9a1gn ? get_current_user_id() : 0;
 $m4is_v6fdv4 = unserialize( base64_decode( $_GET['memb_s3link'] ) );
 $m4is_yh5y = (boolean) $m4is_v6fdv4['debug'] == 1;
 if ( $m4is_yh5y ) { self::m4is_qjcma();
 } if ( $m4is_v6fdv4['require_login'] == 'yes' && ! $m4is_i9a1gn ) { if ( $m4is_yh5y ) { echo __LINE__, " - Login Required, returning to referring page";
 echo '<a href="', $_SERVER['HTTP_REFERER'], '">Continue</a>';
 exit;
 } m4is_aoxw::m4is_g7bv();
 wp_redirect( $_SERVER['HTTP_REFERER'] );
 exit;
 } $m4is_e2kg = self::$m4is_bnd6ti->m4is_dpuy9();
 if ( $m4is_e2kg ) { self::$m4is_bnd6ti->m4is_u86vzq( $m4is_v6fdv4['actionset'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_rldxj3( $m4is_v6fdv4['fus'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_cqe6_( $m4is_v6fdv4['goals'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_v6fdv4['tags'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_lrtqe8( $m4is_v6fdv4['tokens'] );
 } $m4is_imt3e = self::$m4is_bnd6ti->m4is_oiewvu( 'remote_files' );
 $m4is_gvpi6 = strtolower( trim( $m4is_v6fdv4['profile'] ) );
 if ( isset( $m4is_imt3e[$m4is_gvpi6] ) ) { $m4is_rn2wuj = $m4is_imt3e[$m4is_gvpi6]['bucket'];
 $m4is_nymjfo = $m4is_imt3e[$m4is_gvpi6]['host'];
 $m4is_s8owzt = $m4is_imt3e[$m4is_gvpi6]['access_key'];
 $m4is__nzp = $m4is_imt3e[$m4is_gvpi6]['secret_key'];
 if ($m4is_yh5y) { echo __LINE__, ' - Host: ', $m4is_nymjfo, '<br />';
 echo __LINE__, ' - Bucket: ', $m4is_rn2wuj, '<br />';
 } } $m4is_x8ile = $m4is_v6fdv4['expiring'];
 $m4is_pqvw = $m4is_v6fdv4['protocol'];
 $m4is_bmhi = $m4is_v6fdv4['object'];
 $m4is_hng4z = $m4is_v6fdv4['region'];
 if ( $m4is_v6fdv4['version'] == 3 ) { $m4is_imdo6 = self::m4is_ljq65i( $m4is_s8owzt, $m4is__nzp, $m4is_pqvw, $m4is_nymjfo, $m4is_rn2wuj, $m4is_bmhi, $m4is_x8ile );
 } elseif ($m4is_v6fdv4['version'] == 4) {  $m4is_imdo6 = self::m4is_fqvu( $m4is_s8owzt, $m4is__nzp, $m4is_rn2wuj, $m4is_bmhi, $m4is_x8ile, $m4is_hng4z );
 } do_action( 'memberium/s3/link/viewed', $m4is_rn2wuj, $m4is_bmhi, $m4is_ig9p6, $m4is_e2kg );
 if ($m4is_yh5y) { echo __LINE__, ' - URL: <a href="', $m4is_imdo6, '">', $m4is_imdo6, '</a><br />';
 exit;
 } else { m4is_aoxw::m4is_g7bv();
 wp_redirect( $m4is_imdo6, 302, 'Memberium Secure S3 Link' );
 exit;
 } }     private static 
function m4is_qjcma( array $m4is_v6fdv4 ) : void { echo __LINE__, ' - Region:                 ', $m4is_v6fdv4['region'], '<br />';
 echo __LINE__, ' - Version:                ', $m4is_v6fdv4['version'], '<br />';
 echo __LINE__, ' - Protocol:               ', $m4is_v6fdv4['protocol'], '<br />';
 echo __LINE__, ' - Require Login?:         ', $m4is_v6fdv4['require_login'], '<br />';
 echo __LINE__, ' - Set Actionset:          ', $m4is_v6fdv4['actionset'], '<br />';
 echo __LINE__, ' - Set Debug:              ', $m4is_v6fdv4['debug'], '<br />';
 echo __LINE__, ' - Set Expiration:         ', $m4is_v6fdv4['expiring'], ' seconds<br />';
 echo __LINE__, ' - Set Follow Up Sequence: ', $m4is_v6fdv4['fus'], '<br />';
 echo __LINE__, ' - Set Goals:              ', $m4is_v6fdv4['goals'], '<br />';
 echo __LINE__, ' - Set Object:             ', $m4is_v6fdv4['object'], '<br />';
 echo __LINE__, ' - Set Profile:            ', $m4is_v6fdv4['profile'], '<br />';
 echo __LINE__, ' - Set Tags:               ', $m4is_v6fdv4['tags'], '<br />';
 echo __LINE__, ' - Tokens:                 ', $m4is_v6fdv4['tokens'], '<br />';
 }  private static 
function m4is_y4lkf( string $m4is_t5ot4 ) { $m4is_toz0 = m4is_pms8y::m4is_e5l8a9()->m4is_oiewvu('remote_files');
 return isset($m4is_toz0[$m4is_t5ot4]) ? $m4is_toz0[$m4is_t5ot4] : false;
 }  private static 
function m4is_f7t4lh( $m4is_s2ge5, $m4is_etj2, $m4is_p34mf = 64 ) { if (strlen($m4is_s2ge5) > $m4is_p34mf) { $m4is_s2ge5 = pack('H*', sha1($m4is_s2ge5) );
 } $m4is_s2ge5 = str_pad($m4is_s2ge5, $m4is_p34mf, chr(0x00) );
 $m4is_s_gd23 = str_repeat(chr(0x36), $m4is_p34mf);
 $m4is__2ifqv = str_repeat(chr(0x5c), $m4is_p34mf);
 $m4is_qr9h2 = pack('H*', sha1( ($m4is_s2ge5 ^ $m4is__2ifqv) . pack('H*', sha1( ($m4is_s2ge5 ^ $m4is_s_gd23) . $m4is_etj2) ) ) );
 return base64_encode($m4is_qr9h2);
 }  private static 
function m4is_ljq65i( $m4is_s8owzt, $m4is__nzp, $m4is_pqvw, $m4is_nymjfo, $m4is_rn2wuj, $m4is_ea6ksm, $m4is_numo = 30 ) { $m4is_qg0b9n = time() + (int) $m4is_numo;
 $m4is_ea6ksm = str_replace('%2F', '/', rawurlencode($m4is_ea6ksm = ltrim($m4is_ea6ksm, '/') ) );
 $m4is_ixr0 = '/'. $m4is_rn2wuj .'/'. $m4is_ea6ksm;
 $m4is_zvc9 = implode("\n", $pieces = ['GET', null, null, $m4is_qg0b9n, $m4is_ixr0]);
 $m4is_k1k7oj = self::m4is_f7t4lh( $m4is__nzp, $m4is_zvc9 );
  $url = sprintf('%s://%s.%s/%s', $m4is_pqvw, $m4is_rn2wuj, $m4is_nymjfo, $m4is_ea6ksm);
 $qs = http_build_query($pieces = ['AWSAccessKeyId' => $m4is_s8owzt, 'Expires' => $m4is_qg0b9n, 'Signature' => $m4is_k1k7oj,]);
 return $url . '?' . $qs;
 }  private static 
function m4is_o_x314( string $m4is_rn2wuj ) { $m4is_toz0 = self::$m4is_bnd6ti->m4is_oiewvu( 'remote_files' );
 $m4is_hng4z = '';
 $m4is_nymjfo = '';
 foreach($m4is_toz0 as $m4is_gvpi6) { if ($m4is_gvpi6['bucket'] == $m4is_rn2wuj) { $m4is_hng4z = empty($m4is_gvpi6['region']) ? '' : $m4is_gvpi6['region'];
 $m4is_nymjfo = empty($m4is_gvpi6['host']) ? '' : $m4is_gvpi6['host'];
 if ($m4is_nymjfo == 's3.amazonaws.com' && empty($m4is_hng4z) ) { $m4is_hng4z = 'us-east-1';
 } break;
 } } if (empty($m4is_hng4z) ) { if (substr($m4is_nymjfo, 0, 3) === 's3-') { $m4is_hng4z = substr($m4is_nymjfo, 3, strpos($m4is_nymjfo, '.', 3) - 3);
 } if (empty($m4is_hng4z)) { $m4is_hng4z = 'us-east-1';
 } } return $m4is_hng4z;
 }  private static 
function m4is_fqvu( $m4is_s8owzt, $m4is__nzp, $m4is_rn2wuj, $m4is_zuyvpd, $m4is_qg0b9n = 0, $m4is_hng4z = 'us-east-1', $m4is_vrw6c = [] ) { if ( substr( $m4is_zuyvpd, 0, 1 ) !== '/' ) { $m4is_zuyvpd = '/' . $m4is_zuyvpd;
 } if ( empty( $m4is_hng4z) ) { $m4is_hng4z = self::m4is_o_x314( $m4is_rn2wuj );
 } $m4is_skld = str_replace( '%2F', '/', rawurlencode( $m4is_zuyvpd ) );
 $m4is_g780hc = [];
 foreach ( $m4is_vrw6c as $m4is_s2ge5 => $m4is_w_o7al ) { $m4is_s2ge5 = strtolower( $m4is_s2ge5 );
 $m4is_g780hc[$m4is_s2ge5] = $m4is_w_o7al;
 } if ( ! array_key_exists( 'host', $m4is_g780hc ) ) { $m4is_hng4z = empty($m4is_hng4z) ? '' : $m4is_hng4z;
 $m4is_g780hc['host'] = ($m4is_hng4z == 'us-east-1') ? "{$m4is_rn2wuj}.s3.amazonaws.com" : "{$m4is_rn2wuj}.s3-{$m4is_hng4z}.amazonaws.com";
 } ksort($m4is_g780hc);
 $m4is_t8b6 = '';
 foreach ($m4is_g780hc as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_t8b6 .= $m4is_s2ge5 . ':' . trim($m4is_w_o7al) . "\n";
 } $m4is_al45 = implode(';', array_keys($m4is_g780hc) );
 $m4is_lq7v = time();
 $m4is_hw_y1f = gmdate('Ymd', $m4is_lq7v);
 $m4is_xov0yu = $m4is_hw_y1f . 'T000000Z';
 $m4is_xov0yu = $m4is_hw_y1f . 'T' . gmdate('His', $m4is_lq7v) . 'Z';
 $m4is_m_oc = 'AWS4-HMAC-SHA256';
 $m4is_mt7w59 = "$m4is_hw_y1f/$m4is_hng4z/s3/aws4_request";
 $m4is_pl0jsm = [ 'X-Amz-Algorithm' => $m4is_m_oc, 'X-Amz-Credential' => $m4is_s8owzt . '/' . $m4is_mt7w59, 'X-Amz-Date' => $m4is_xov0yu, 'X-Amz-SignedHeaders' => $m4is_al45 ];
 if ($m4is_qg0b9n > 0) { $m4is_pl0jsm['X-Amz-Expires'] = $m4is_qg0b9n;
 } ksort($m4is_pl0jsm);
 $m4is_iq_w = [];
 foreach ($m4is_pl0jsm as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_iq_w[] = rawurlencode($m4is_s2ge5) . '=' . rawurlencode($m4is_w_o7al);
 } $m4is_ikvc1h = implode('&', $m4is_iq_w);
 $m4is_u6tpl = "GET\n$m4is_skld\n$m4is_ikvc1h\n$m4is_t8b6\n$m4is_al45\nUNSIGNED-PAYLOAD";
 $m4is_wcvh = "$m4is_m_oc\n$m4is_xov0yu\n$m4is_mt7w59\n" . hash('sha256', $m4is_u6tpl, false);
 $m4is_n13edn = hash_hmac('sha256', 'aws4_request', hash_hmac('sha256', 's3', hash_hmac('sha256', $m4is_hng4z, hash_hmac('sha256', $m4is_hw_y1f, 'AWS4' . $m4is__nzp, true), true), true), true);
 $m4is_k1k7oj = hash_hmac('sha256', $m4is_wcvh, $m4is_n13edn);
 $m4is_imdo6 = 'https://' . $m4is_g780hc['host'] . $m4is_skld . '?' . $m4is_ikvc1h . '&X-Amz-Signature=' . $m4is_k1k7oj;
 return $m4is_imdo6;
 } }

