<?php
/**
 * Copyright (c) 2017-2024 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists( 'm4is_pms8y' ) || die();
 m4is__h0xmk::m4is_x6wv();
 final 
class m4is__h0xmk {      static private $m4is_bnd6ti, $m4is_zq0k, $m4is_e2kg, $m4is_j_xo4w, $m4is_o3m_c5, $m4is_n3zlk;
 static 
function m4is_x6wv() { self::$m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 self::$m4is_zq0k = self::$m4is_bnd6ti->m4is_d14zr('appname');
 self::$m4is_e2kg = self::$m4is_bnd6ti->m4is_dpuy9();
 self::$m4is_j_xo4w = self::$m4is_bnd6ti->m4is_zw_n();
 self::$m4is_o3m_c5 = ! m4is_u68pu::m4is_u6mkaw();
 self::$m4is_n3zlk = 'memberium';
 } static 
function m4is_etsg( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } if ( ! self::$m4is_e2kg ) { return '';
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 $m4is_l2waj = m4is_akcfiz::m4is_l9v0jb( $m4is_i3aq );
 $m4is_zd8v = 0;
 if ( is_array( $m4is_l2waj ) && count( $m4is_l2waj ) > 0) { $m4is_jl7j9 = strtotime( date( 'Y-m-d' ) );
 $m4is_numo = strtotime( date( $m4is_l2waj['ExpirationYear'] . '-' . ($m4is_l2waj['ExpirationMonth'] + 1) . '-01' ) );
 $m4is_zd8v = (int) ( ( $m4is_numo - $m4is_jl7j9 ) / 86400 );
 $m4is_zd8v = $m4is_zd8v < 0 ? 0 : $m4is_zd8v;
 } $m4is_uzfw8j = $m4is_zd8v;
 return m4is_crqo::m4is__go6j( false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'] );
 }  static 
function m4is_zo_gr( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '') : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'txtfmt' => '', 'not' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_uwdfj = false;
 $m4is_qnjfv['not'] = ! empty($m4is_qnjfv['not']);
 if (stripos($m4is_carw7y, '_no_') ) { $m4is_qnjfv['not'] = true;
 } if (! isset($_SESSION['memb_user']['has_credit_card']) || (isset($_SESSION['memb_user']['has_credit_card']) && $_SESSION['memb_user']['has_credit_card'] == 0) ) { m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 } if (isset($_SESSION['memb_user']['has_credit_card']) && $_SESSION['memb_user']['has_credit_card'] > 0) { $m4is_uwdfj = true;
 } if ($m4is_qnjfv['not']) { $m4is_uwdfj = ! $m4is_uwdfj;
 } $m4is_uzfw8j = m4is_crqo::m4is_mm2xd($m4is_z50f, $m4is_carw7y, true, $m4is_uwdfj);
 return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture']);
 } static 
function m4is_wr3dis( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'date_format' => '', 'default' => '', 'fields' => '', 'txtfmt' => '', 'separator' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! self::$m4is_e2kg ) { return '';
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
  $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 $m4is_l2waj = array_change_key_case(m4is_akcfiz::m4is_l9v0jb( $m4is_i3aq ), CASE_LOWER);
 $m4is_h_iu0 = array_filter(array_map('strtolower', explode(',', $m4is_qnjfv['fields']) ) );
 $m4is_l436 = count($m4is_h_iu0);
 $m4is_i7j9_a = 0;
 $m4is_uzfw8j = '';
 unset($m4is_i3aq);
  foreach ($m4is_h_iu0 as $m4is_yxwn) { $m4is_yxwn = strtolower(trim($m4is_yxwn) );
 if (isset($m4is_l2waj[$m4is_yxwn]) ) { $m4is_mb6gy = strtotime($m4is_l2waj[$m4is_yxwn]);
 if ($m4is_qnjfv['date_format'] == '' || $m4is_mb6gy == 0) { $m4is_n6yjk9 = $m4is_l2waj[$m4is_yxwn];
 } else { $m4is_n6yjk9 = date($m4is_qnjfv['date_format'], strtotime($m4is_l2waj[$m4is_yxwn]) );
 } } else { $m4is_n6yjk9 = $m4is_qnjfv['default'];
 } $m4is_uzfw8j .= $m4is_n6yjk9;
 if ($m4is_l436 > 1) { $m4is_uzfw8j .= $m4is_qnjfv['separator'];
 } } if ($m4is_l436 > 1 && strlen($m4is_qnjfv['separator']) > 0) { $m4is_uzfw8j = substr($m4is_uzfw8j, 0, -strlen($m4is_qnjfv['separator']) );
 } return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $txtfmt, $m4is_qnjfv['capture']);
 } static 
function m4is_x8ld( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'days' => 0, 'debug' => false, 'subscription_ids' => '', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! self::$m4is_e2kg ) { return '';
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['debug'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['debug'], false );
 $m4is_qnjfv['days'] = (int) $m4is_qnjfv['days'];
 $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 $m4is_l2waj = m4is_akcfiz::m4is_l9v0jb( $m4is_i3aq );
 if (! empty($m4is_qnjfv['subscription_ids']) ) { } else { unset($m4is_i3aq);
 $m4is_zd8v = 0;
 if (count($m4is_l2waj) > 0) { $m4is_jl7j9 = strtotime(date('Y-m-d') );
 $m4is_numo = strtotime(date($m4is_l2waj['ExpirationYear'] . '-' . $m4is_l2waj['ExpirationMonth'] . '-28') );
 $m4is_zd8v = (int) ( ($m4is_numo - $m4is_jl7j9) / 86400);
 if ($m4is_zd8v < 0) { $m4is_zd8v = 0;
 } } $m4is__8htld = (boolean) ($m4is_zd8v < $m4is_qnjfv['days']);
 } $m4is_uzfw8j = m4is_crqo::m4is_mm2xd($m4is_z50f, $m4is_carw7y, true, $m4is__8htld);
 if ($m4is_qnjfv['txtfmt'] > '') { $m4is_uzfw8j = m4is_crqo::m4is_mq57($m4is_uzfw8j, $m4is_qnjfv['txtfmt']);
 } if ($m4is_qnjfv['capture'] > '') { $m4is_uzfw8j = m4is_crqo::m4is_uyv45q($m4is_uzfw8j, $m4is_qnjfv['capture']);
 }  foreach($m4is_l2waj as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_uzfw8j = str_ireplace('%%' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_uzfw8j);
 } $m4is_uzfw8j = str_ireplace('%%days_left%%', $m4is_zd8v, $m4is_uzfw8j);
 return do_shortcode($m4is_uzfw8j);
 } static 
function m4is_r1a9( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'button_text' => 'Pay Now', 'date_format' => 'M d, Y', 'active' => TRUE, ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! self::$m4is_e2kg ) { return '';
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg);
 $m4is__32_p = 0;
 $m4is_uzfw8j = '';
 $m4is_tjg_9 = '';
 if (trim($m4is_z50f) == '') { $m4is_z50f .= '<tr>';
 $m4is_z50f .= '<td>%%card.type%%</td>';
 $m4is_z50f .= '<td>xxxxxxxxxxxx%%card.last4%%</td>';
 $m4is_z50f .= '<td>%%card.month.dropdown%% / ';
 $m4is_z50f .= '%%card.year.dropdown%%</td>';
  $m4is_z50f .= '</tr>';
 } if (is_array($m4is_i3aq) ) { foreach ($m4is_i3aq as $m4is_l2waj) { $m4is_rbwn1z = base64_encode(serialize(['creditcard_id' => (int) $m4is_l2waj['Id'],] ) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is__32_p++;
 $m4is_uzfw8j .= '<form method="post" action="">';
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"memb_form_type\" value=\"memb_list_creditcards_form\">";
 $m4is_uzfw8j .= '<input type="hidden" name="parameters" value="' . $m4is_rbwn1z . '">';
 $m4is_uzfw8j .= '<input type="hidden" name="signature" value="' . $m4is_k1k7oj . '">';
 $m4is_uzfw8j .= '<input type="hidden" name="Id" value="' . $m4is_l2waj['Id'] . '">';
 if ($m4is__32_p % 2) { $m4is_p5ehv = 'odd';
 } else { $m4is_p5ehv = 'even';
 } $m4is_wiqv3 = '<select name="ExpirationMonth">';
 for ($m4is_tiq5k6 = 1;
 $m4is_tiq5k6 < 13;
 $m4is_tiq5k6++ ) { $m4is_q_0px1 = str_pad($m4is_tiq5k6, 2, '0', STR_PAD_LEFT);
 $m4is_wiqv3 .= '<option value ="' . $m4is_q_0px1 . '" ' . ($m4is_q_0px1 == $m4is_l2waj['ExpirationMonth'] ? ' selected="selected" ' : '') . '>' . $m4is_q_0px1 . '</option>';
 } $m4is_wiqv3 .= '</select>';
 $m4is_q9nesu = '<select name="ExpirationYear">';
 for ($m4is_tiq5k6 = date('Y');
 $m4is_tiq5k6 < (date('Y') + 10);
 $m4is_tiq5k6++ ) { $m4is_q9nesu .= '<option value ="' . $m4is_tiq5k6 . '" ' . ($m4is_tiq5k6 == $m4is_l2waj['ExpirationYear'] ? ' selected="selected" ' : '') . '>' . $m4is_tiq5k6 . '</option>';
 } $m4is_q9nesu .= '</select>';
 $m4is_m8u1 = '<input type="submit" value="Delete" class="deletebutton">';
 $m4is_ks1fj2 = str_ireplace('%%card.id%%', $m4is_l2waj['Id'], $m4is_z50f);
 $m4is_ks1fj2 = str_ireplace('%%card.type%%', $m4is_l2waj['CardType'], $m4is_z50f);
 $m4is_ks1fj2 = str_ireplace('%%card.last4%%', $m4is_l2waj['Last4'], $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%card.year%%', $m4is_l2waj['ExpirationYear'], $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%card.month%%', $m4is_l2waj['ExpirationMonth'], $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%card.month.dropdown%%', $m4is_wiqv3, $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%card.year.dropdown%%', $m4is_q9nesu, $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%card.id%%', $m4is_l2waj['Id'], $m4is_ks1fj2);
  $m4is_uzfw8j .= $m4is_ks1fj2;
 $m4is_uzfw8j .= '</form>';
 } } return $m4is_uzfw8j;
 }  static 
function m4is_mnkv( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_su4qk = 0;
 $m4is_su4qk++;
 $m4is_r6nh_b = [ 'action_ids' => '', 'addonly' => 'no', 'backcharge' => 'no', 'cardtypes' => 'American Express,Discover,MasterCard,Visa', 'debug' => false, 'debug_ip' => '', 'failureurl' => $_SERVER['REQUEST_URI'], 'goals' => '', 'ignoressl' => 'no', 'plan_ids' => '', 'set_default' => 'yes', 'success_msg' => 'Your credit card was successfully updated.', 'successurl' => $_SERVER['REQUEST_URI'], 'tag_ids' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! MEMBERIUM_DEBUG) { if (! is_ssl() ) { if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '<p>Credit Card Update Form Disabled Due to Missing SSL.</p>';
 } return '';
 } } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['addonly'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['addonly'], false);
 $m4is_qnjfv['backcharge'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['backcharge'], true);
 $m4is_qnjfv['debug'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['debug'], false);
 $m4is_qnjfv['ignoressl'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['ignoressl'], false);
 $m4is_qnjfv['set_default'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['set_default'], true);
 if (! self::$m4is_bnd6ti->m4is_lvmz1b() ) { if ( self::$m4is_e2kg == 0) { return '';
 } if ( (! is_ssl() ) && (! $m4is_qnjfv['ignoressl']) ) { return '';
 } } $m4is_npof41 = 'memb_addupdate_creditcard-' . $m4is_su4qk;
 $m4is_uxc7v = 'Add Card';
 $m4is_qnjfv['cardtypes'] = array_filter(explode(',', $m4is_qnjfv['cardtypes']) );
 $m4is_l2waj['Id'] = 0;
 if ($m4is_qnjfv['addonly'] == false) {  $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 $m4is_l2waj = end( $m4is_i3aq );
 $m4is_l2waj = is_array( $m4is_l2waj ) ? $m4is_l2waj : [];
 $m4is_wk1bir = [ 'BillAddress1', 'BillAddress2', 'BillCity', 'BillCountry', 'BillState', 'BillZip', 'CardType', 'ExpirationMonth', 'ExpirationYear', 'FirstName', 'Id', 'Last4', 'LastName', 'NameOnCard', 'PhoneNumber', ];
 foreach ( $m4is_wk1bir as $m4is_s2ge5 ) { if ( empty( $m4is_l2waj[$m4is_s2ge5] ) ) { $m4is_l2waj[$m4is_s2ge5] = '';
 } } } if ($m4is_l2waj['Id'] > 0) {  $m4is__4en6o = $m4is_l2waj['Id'];
 $m4is_ujq5r1 = $m4is_l2waj['FirstName'];
 $m4is_bf5on = $m4is_l2waj['LastName'];
 $m4is_cfrc2l = '************' . $m4is_l2waj['Last4'];
 $m4is_nt1is2 = $m4is_l2waj['CardType'];
 $m4is_o3ph = $m4is_l2waj['ExpirationMonth'];
 $m4is_hpl5 = $m4is_l2waj['ExpirationYear'];
 $m4is_h4ap = trim($m4is_l2waj['NameOnCard']);
 $m4is__i4p_7 = $m4is_l2waj['PhoneNumber'];
 $m4is_mvfwr8 = $m4is_l2waj['BillAddress1'];
 $m4is_u3_5n = $m4is_l2waj['BillAddress2'];
 $m4is_wxbv = $m4is_l2waj['BillCity'];
 $m4is_qjai = $m4is_l2waj['BillState'];
 $m4is_uwmf = $m4is_l2waj['BillCountry'];
 $m4is__mk1f = $m4is_l2waj['BillZip'];
 $m4is_o24eri = isset($m4is_l2waj['CVV2']) ? (string) $m4is_l2waj['CVV2'] : '';
 $m4is_n3zt = 'update';
 $m4is__iju62 = ' disabled ';
 } else {  $m4is__4en6o = 0;
 $m4is_ujq5r1 = m4is_wbc8os::m4is_sfnmc('firstname');
 $m4is_bf5on = m4is_wbc8os::m4is_sfnmc('lastname');
 $m4is_cfrc2l = '';
 $m4is_nt1is2 = '';
 $m4is_o3ph = '';
 $m4is_hpl5 = '';
 $m4is_h4ap = trim($m4is_ujq5r1 . ' ' . $m4is_bf5on);
 $m4is__i4p_7 = m4is_wbc8os::m4is_sfnmc('phone1');
 $m4is_mvfwr8 = m4is_wbc8os::m4is_sfnmc('streetaddress1');
 $m4is_u3_5n = m4is_wbc8os::m4is_sfnmc('streetaddress2');
 $m4is_wxbv = m4is_wbc8os::m4is_sfnmc('city');
 $m4is_qjai = m4is_wbc8os::m4is_sfnmc('state');
 $m4is_uwmf = m4is_wbc8os::m4is_sfnmc('country');
 $m4is__mk1f = m4is_wbc8os::m4is_sfnmc('postalcode');
 $m4is_o24eri = '';
 $m4is_n3zt = 'add';
 $m4is__iju62 = ' ';
 } if (empty($m4is_l2waj['NameOnCard']) ) { $m4is_l2waj['NameOnCard'] = $m4is_ujq5r1 . ' ' . $m4is_bf5on;
 $m4is_h4ap = trim($m4is_l2waj['NameOnCard' ]);
 } $m4is_rbwn1z = base64_encode(serialize([ 'action_ids' => $m4is_qnjfv['action_ids'], 'backcharge' => $m4is_qnjfv['backcharge'], 'contact_id' => self::$m4is_e2kg, 'creditcard_id' => $m4is__4en6o, 'debug' => $m4is_qnjfv['debug'], 'debug_ip' => $m4is_qnjfv['debug_ip'], 'failureurl' => $m4is_qnjfv['failureurl'], 'goals' => $m4is_qnjfv['goals'], 'plan_ids' => $m4is_qnjfv['plan_ids'], 'set_default' => $m4is_qnjfv['set_default'], 'success_msg' => $m4is_qnjfv['success_msg'], 'successurl' => $m4is_qnjfv['successurl'], 'tag_ids' => $m4is_qnjfv['tag_ids'], ]) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is_etj2 = new stdClass;
 $m4is_etj2->form_name = $m4is_npof41;
 $m4is_etj2->form_id = $m4is_su4qk;
 $m4is_etj2->parameters = $m4is_rbwn1z;
 $m4is_etj2->signature = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is_etj2->nonce = wp_nonce_field('creditcard_add_' . $m4is_su4qk, '_wpnonce', true, false);
 $m4is_etj2->card_types = $m4is_qnjfv['cardtypes'];
 $m4is_etj2->creditcard_type = $m4is_nt1is2;
 $m4is_etj2->card_number = $m4is_cfrc2l;
 $m4is_etj2->disabled = $m4is__iju62;
 $m4is_etj2->expiration_month = $m4is_o3ph;
 $m4is_etj2->expiration_year = $m4is_hpl5;
 $m4is_etj2->name_on_card = $m4is_h4ap;
 $m4is_etj2->phone1 = $m4is__i4p_7;
 $m4is_etj2->address1 = $m4is_mvfwr8;
 $m4is_etj2->address2 = $m4is_u3_5n;
 $m4is_etj2->city = $m4is_wxbv;
 $m4is_etj2->postalcode = $m4is__mk1f;
 $m4is_etj2->state = $m4is_qjai;
 $m4is_etj2->country = $m4is_uwmf;
 $m4is_etj2->country_options_html = self::$m4is_bnd6ti->m4is_se2n8()->getCountryOptions( $m4is_etj2->country );
 $m4is_etj2->country_options = [];
 return m4is_crqo::m4is_yu7b1r($m4is_carw7y, $m4is_qnjfv, $m4is_z50f, $m4is_carw7y, $m4is_etj2);
 }    static 
function m4is_msey( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'default' => '', 'fields' => '', 'htmlattr' => '', 'id' => 0, 'separator' => ' ', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['id'] = (int) $m4is_qnjfv['id'];
 if (empty($m4is_qnjfv['fields']) || $m4is_qnjfv['id'] < 1) { return;
 } $m4is_h_iu0 = array_filter(explode(',', strtolower($m4is_qnjfv['fields']) ) );
 $m4is_l436 = count($m4is_h_iu0);
 $m4is_si73 = m4is_untczd::m4is_ut153j($m4is_qnjfv['id'], true);
 $m4is_uzfw8j = '';
 foreach ($m4is_h_iu0 as $m4is_yxwn) { $m4is_yxwn = trim($m4is_yxwn);
 $fieldvalue = isset($m4is_si73[$m4is_yxwn]) ? $m4is_si73[$m4is_yxwn] : $m4is_qnjfv['default'];
 if ($m4is_yxwn == 'productprice') { $fieldvalue = number_format( (double) $fieldvalue, 2);
 } elseif ($m4is_yxwn == 'image.url') { $fieldvalue = 'https://' . self::$m4is_zq0k . '.infusionsoft.com/cart/pimg.jsp?i=5&t=p&s=x&date=' . time();
 } $m4is_uzfw8j .= $fieldvalue;
 if ($m4is_l436 > 1) { $m4is_uzfw8j .= $m4is_qnjfv['separator'];
 } } if ($m4is_l436 > 1 && $m4is_qnjfv['separator']) { $m4is_uzfw8j = substr($m4is_uzfw8j, 0, -strlen($m4is_qnjfv['separator']) );
 } return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_keqr4($m4is_qnjfv, $m4is_z50f = NULL, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'default' => '', 'fields' => '', 'id' => 0, 'separator' => ' ', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['id'] = (int) $m4is_qnjfv['id'];
 if ($m4is_qnjfv['fields'] = '' || $m4is_qnjfv['id'] < 1) { return;
 } $m4is_h_iu0 = array_filter(explode(',', $m4is_qnjfv['fields']) );
 $m4is_l436 = count($m4is_h_iu0);
 $subscriptionplan = self::$m4is_bnd6ti->m4is_nign($m4is_qnjfv['id'], TRUE);
 $m4is_uzfw8j = '';
 foreach ($m4is_h_iu0 as $m4is_yxwn) { $m4is_yxwn = strtolower(trim($m4is_yxwn) );
 $fieldvalue = isset($subscriptionplan[$m4is_yxwn]) ? $subscriptionplan[$m4is_yxwn] : $m4is_qnjfv['default'];
 if (in_array($m4is_yxwn, ['planprice', 'preauthorizeamount']) ) { $fieldvalue = number_format( (double) $fieldvalue, 2);
 } $m4is_uzfw8j .= $fieldvalue;
 if ($m4is_l436 > 1) { $m4is_uzfw8j .= $m4is_qnjfv['separator'];
 } } $m4is_uzfw8j = substr($m4is_uzfw8j, 0, -strlen($m4is_qnjfv['separator']) );
 return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture']);
 }    static 
function m4is_lhvm5($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 }    $m4is_r6nh_b = [ 'invoice_id' => isset($_GET['invoice_id']) ? (int) $_GET['invoice_id'] : 0, 'contact_id' => m4is_wbc8os::m4is_jjgo(), 'date_format' => 'F j, Y', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_uzfw8j = '';
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_k4yeul = [ 'invoice_id' => $m4is_qnjfv['invoice_id'], 'contact_id' => $m4is_qnjfv['contact_id'], ];
 $m4is_kfsn9d = self::$m4is_bnd6ti->m4is_u3zvs( $m4is_k4yeul );
 if (is_array($m4is_kfsn9d) ) { $m4is_yao_0n = get_option('memberium_invoice_template', false);
 $m4is_uzfw8j .= '<div class="memberium-order-receipt">';
 if (! empty($m4is_yao_0n['header']) ) { $m4is_uzfw8j .= $m4is_yao_0n['header'];
 } if (isset($m4is_kfsn9d['orderitems']) && is_array($m4is_kfsn9d['orderitems']) ) { foreach($m4is_kfsn9d['orderitems'] as $m4is_f852) { $m4is_ks1fj2 = $m4is_yao_0n['items'];
 $m4is_ks1fj2 = str_ireplace('%%item.cpu%%', number_format($m4is_f852['cpu'], 2), $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%item.ppu%%', number_format($m4is_f852['ppu'], 2), $m4is_ks1fj2);
 foreach($m4is_f852 as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_ks1fj2 = str_ireplace('%%item.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_ks1fj2);
 } $m4is_ks1fj2 = str_ireplace('%%receipt.subtotal%%', number_format($m4is_f852['ppu'] * $m4is_f852['qty'], 2), $m4is_ks1fj2);
 $m4is_uzfw8j .= $m4is_ks1fj2;
 } } $m4is_uzfw8j .= $m4is_yao_0n['pre_payments'];
 foreach($m4is_kfsn9d['payments'] as $m4is_hgw8mf) { $m4is_ks1fj2 = $m4is_yao_0n['payments'];
 $m4is_ks1fj2 = str_ireplace('%%payment.paydate%%', date($m4is_qnjfv['date_format'], strtotime($m4is_hgw8mf['paydate']) ), $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%payment.payamt%%', number_format($m4is_hgw8mf['payamt'], 2), $m4is_ks1fj2);
 foreach($m4is_hgw8mf as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_ks1fj2 = str_ireplace('%%payment.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_ks1fj2);
 } $m4is_uzfw8j .= $m4is_ks1fj2;
 } $m4is_uzfw8j .= $m4is_yao_0n['pre_scheduled'];
  foreach($m4is_kfsn9d['paymentplanitems'] as $m4is_hgw8mf) { $m4is_ks1fj2 = $m4is_yao_0n['scheduled'];
 $m4is_ks1fj2 = str_ireplace('%%scheduled.datedue%%', date($m4is_qnjfv['date_format'], strtotime($m4is_hgw8mf['datedue']) ), $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%scheduled.amtdue%%', number_format($m4is_hgw8mf['amtdue'], 2), $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%scheduled.amtpaid%%', number_format($m4is_hgw8mf['amtpaid'], 2), $m4is_ks1fj2);
 foreach($m4is_hgw8mf as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_ks1fj2 = str_ireplace('%%scheduled.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_ks1fj2);
 } $m4is_uzfw8j .= $m4is_ks1fj2;
 } $m4is_uzfw8j .= $m4is_yao_0n['footer'];
 $m4is_uzfw8j .= '</div>';
 if (! empty($m4is_kfsn9d['job']) ) { $m4is_uzfw8j = str_ireplace('%%order.datecreated%%', date($m4is_qnjfv['date_format'], strtotime($m4is_kfsn9d['job']['datecreated']) ), $m4is_uzfw8j);
 $m4is_uzfw8j = str_ireplace('%%order.duedate%%', date($m4is_qnjfv['date_format'], strtotime($m4is_kfsn9d['job']['duedate']) ), $m4is_uzfw8j);
 } if (! empty($m4is_kfsn9d['invoice']) ) { $m4is_uzfw8j = str_ireplace('%%invoice.datecreated%%', date($m4is_qnjfv['date_format'], strtotime($m4is_kfsn9d['invoice']['datecreated']) ), $m4is_uzfw8j);
 $m4is_uzfw8j = str_ireplace('%%invoice.overdue%%', number_format($m4is_kfsn9d['invoice']['totaldue'] - $m4is_kfsn9d['invoice']['totalpaid'], 2), $m4is_uzfw8j);
 $m4is_uzfw8j = str_ireplace('%%invoice.invoicetotal%%', number_format($m4is_kfsn9d['invoice']['invoicetotal'], 2), $m4is_uzfw8j);
 $m4is_uzfw8j = str_ireplace('%%invoice.totalpaid%%', number_format($m4is_kfsn9d['invoice']['totalpaid'], 2), $m4is_uzfw8j);
 } if (is_array($m4is_kfsn9d['invoice']) ) { foreach($m4is_kfsn9d['invoice'] as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_uzfw8j = str_ireplace('%%invoice.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_uzfw8j);
 } } if (is_array($m4is_kfsn9d['contact']) ) { foreach($m4is_kfsn9d['contact'] as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_uzfw8j = str_ireplace('%%contact.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_uzfw8j);
 } } if (isset($m4is_kfsn9d['job']) && is_array($m4is_kfsn9d['job']) ) { foreach($m4is_kfsn9d['job'] as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_uzfw8j = str_ireplace('%%order.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_uzfw8j);
 } } $m4is_uzfw8j = apply_filters('memberium_show_receipt', $m4is_uzfw8j, $m4is_kfsn9d);
  $m4is_uzfw8j = preg_replace('/(%%\S+%%)/', '', $m4is_uzfw8j);
 } return do_shortcode($m4is_uzfw8j);
 }    static 
function m4is_yvchd9($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } global $wpdb;
 $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => false, 'contact_id' => self::$m4is_e2kg, 'days' => 0, 'htmlattr' => '', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_x1eq = '0.00';
 if (! empty($m4is_qnjfv['contact_id'])) { $m4is_tovizk = 'SELECT sum(`totalpaid`) FROM `' . MEMBERIUM_DB_INVOICES . '` WHERE `appname` = %s `contactid` = %d AND `payplanstatus` = 1 AND `paystatus` = 1; ';
 $m4is_tovizk = $wpdb->prepare($m4is_tovizk, self::$m4is_bnd6ti->m4is_d14zr('appname'), $m4is_qnjfv['contact_id']);
 $m4is_x1eq = $wpdb->get_var($m4is_tovizk);
 } return m4is_crqo::m4is__go6j(false, $tlv, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_w12j7x($m4is_qnjfv, $m4is_z50f = NULL, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'button_text' => 'Pay Now', 'contact_id' => self::$m4is_e2kg, 'date_format' => 'M d, Y', 'form_class' => 'invoiceline', 'goal' => '', 'limit' => 0, 'merchant_id' => self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'merchant_account_id' ), 'nocost' => true, 'only_prodids' => '', 'paid' => true, 'post' => '', 'pre' => '', 'redirect_url' => $_SERVER['REQUEST_URI'], 'reverse' => false, 'success_msg' => 'Your payment was successfully processed.', 'tag_id' => '', 'unpaid' => true,  ];
 if ( isset( $m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } if ( is_feed() || ! is_singular() ) { return;
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 if ( ! $m4is_qnjfv['contact_id'] ) { return;
 } $m4is_qnjfv['nocost'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['nocost'], false );
 $m4is_qnjfv['paid'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['paid'], false );
 $m4is_qnjfv['reverse'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['reverse'], false );
 $m4is_qnjfv['unpaid'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['unpaid'], false );
 if (trim($m4is_z50f) == '') { $m4is_z50f .= '<div><span>%%invoice.id%%</span>';
 $m4is_z50f .= '<span>%%description%%</span>';
 $m4is_z50f .= '<span>$%%invoice.total%%</span>';
 $m4is_z50f .= '<span>$%%total.paid%%</span>';
 $m4is_z50f .= '<span>$%%refund.status%%</span>';
 $m4is_z50f .= '<span>$%%amount.due%%</span>';
 $m4is_z50f .= '<span>%%date.due%%</span>';
 $m4is_z50f .= '<span>%%creditcard.dropdown%%</span>';
 $m4is_z50f .= '<span>%%submit%%</span></div>';
 } $m4is_zq0k = self::$m4is_zq0k;
 $m4is_z8sd = m4is_untczd::m4is_j68se();
 $m4is_craco = self::$m4is_bnd6ti->m4is_ow9yjk( $m4is_qnjfv['contact_id'], $m4is_qnjfv['paid'], $m4is_qnjfv['unpaid'] );
 if (is_array($m4is_craco) && ! $m4is_qnjfv['nocost']) { foreach($m4is_craco as $m4is_s2ge5 => $m4is_etwy_q) { if ($m4is_etwy_q['InvoiceTotal'] == 0) { unset($m4is_craco[$m4is_s2ge5]);
 } } } if ($m4is_qnjfv['reverse']) { $m4is_craco = array_reverse($m4is_craco, true);
 } $m4is_i3aq = [];
 $jobs = [];
 if (! empty($m4is_craco) ) { $m4is_i3aq = m4is_akcfiz::m4is_ms5b($m4is_qnjfv['contact_id']);
 }  if (empty($m4is_i3aq) ) { $m4is_z_mv = '';
 } else { $m4is_z_mv = '<select name="creditcard_id">';
 if (is_array($m4is_i3aq) ) { foreach ($m4is_i3aq as $m4is_l2waj) { $m4is_zg8z = isset($m4is_l2waj['Status']) ? $m4is_l2waj['Status'] : 0;
 if (in_array($m4is_l2waj['Status'], [1,3,4]) ) { $m4is_m5esw = isset($m4is_l2waj['CardType']) ? $m4is_l2waj['CardType'] : 'Unknown';
 $m4is_sgckmy = isset($m4is_l2waj['Last4']) ? $m4is_l2waj['Last4'] : '';
 $m4is_z_mv .= '<option value="'. $m4is_l2waj['Id'] . '">' . $m4is_m5esw . ' ' . $m4is_sgckmy . '</option>';
 } } } $m4is_z_mv .= '</select>';
 } $m4is_l8qxh = [ 0 => _x('No Credit', 'memb_list_invoices', self::$m4is_n3zlk ), 1 => _x('Partial Credit Applied', 'memb_list_invoices', self::$m4is_n3zlk ), 2 => _x('Full Credit Applied', 'memb_list_invoices', self::$m4is_n3zlk ), ];
 $m4is_jn89 = [ 0 => _x('Not Paid', 'memb_list_invoices', self::$m4is_n3zlk ), 1 => _x('Paid', 'memb_list_invoices', self::$m4is_n3zlk ), ];
 $m4is_mzci2 = [ 0 => _x('No Refund', 'memb_list_invoices', self::$m4is_n3zlk ), 1 => _x('Partial Refund', 'memb_list_invoices', self::$m4is_n3zlk ), 2 => _x('Full Refund', 'memb_list_invoices', self::$m4is_n3zlk ), 3 => _x('Full Write-Off', 'memb_list_invoices', self::$m4is_n3zlk ), 4 => _x('Partial Write-Off', 'memb_list_invoices', self::$m4is_n3zlk ), ];
 $m4is__32_p = 0;
 $m4is_uzfw8j = $m4is_qnjfv['pre'];
 if ( is_array( $m4is_craco ) ) { if ( count( $m4is_craco ) > $m4is_qnjfv['limit'] ) { } foreach ( $m4is_craco as $m4is_etwy_q ) {  if ( $m4is_qnjfv['only_prodids'] > '' ) { } $m4is__ql9vk = array_filter( explode( ',', $m4is_etwy_q['ProductSold'] ) );
 $m4is__6tg = count( $m4is__ql9vk );
 $m4is_yuvj = array_shift( $m4is__ql9vk );
 $m4is_k2v6d = $m4is_l8qxh[$m4is_etwy_q['CreditStatus']];
 $m4is_foih4 = $m4is_jn89[$m4is_etwy_q['PayStatus']];
 $m4is_vosc = $m4is_mzci2[$m4is_etwy_q['RefundStatus']];
 $m4is_r6nh_b = [ 'goal' => $m4is_qnjfv['goal'], 'invoice_id' => (int) $m4is_etwy_q['Id'], 'merchant_id' => (int) $m4is_qnjfv['merchant_id'], 'redirect_url' => $m4is_qnjfv['redirect_url'], 'success_msg' => $m4is_qnjfv['success_msg'], 'tag_id' => $m4is_qnjfv['tag_id'], ];
 $m4is_rbwn1z = base64_encode( serialize( $m4is_r6nh_b ) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6( $m4is_rbwn1z );
  $m4is__32_p++;
 if ( $m4is__32_p % 2 ) { $m4is_p5ehv = 'odd';
 } else { $m4is_p5ehv = 'even';
 }  if ( in_array( trim( $m4is_etwy_q['Description']), ['One-time:', 'Order Form', 'API Order'] ) ) { if ( isset( $m4is_z8sd[$m4is_yuvj]['ProductName'] ) ) { $m4is_etwy_q['Description'] = $m4is_z8sd[$m4is_yuvj]['ProductName'];
 if ( $m4is__6tg > 1 ) { $m4is_etwy_q['Description'] .= sprintf( _x(', and %d other items.', 'memb_list_invoices', self::$m4is_n3zlk ), ( $m4is__6tg - 1 ) );
 } } } $m4is_ks1fj2 = '<form method="post" action="">';
 $m4is_ks1fj2 .= wp_nonce_field( 'memb_payinvoice_' . $m4is_etwy_q['Id'], '_wpnonce', true, false );
 $m4is_ks1fj2 .= '<input type="hidden" name="memb_form_type" value="memb_pay_invoice">';
 $m4is_ks1fj2 .= '<input type="hidden" name="parameters" value="' . $m4is_rbwn1z . '">';
 $m4is_ks1fj2 .= '<input type="hidden" name="signature" value="' . $m4is_k1k7oj . '">';
 $m4is_ks1fj2 .= $m4is_z50f;
 $m4is_ks1fj2 .= '</form>';
 $m4is_ks1fj2 = str_ireplace( '%%credit.status%%', $m4is_k2v6d, $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%cycler%%', $m4is_p5ehv, $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%description%%', $m4is_etwy_q['Description'], $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%invoice.id%%', $m4is_etwy_q['Id'], $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%invoice.total%%', sprintf('%0.2f', $m4is_etwy_q['InvoiceTotal']), $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%line%%', $m4is__32_p, $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%pay.status%%', $m4is_foih4, $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%refund.status%%', $m4is_vosc, $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%total.paid%%', sprintf('%0.2f', $m4is_etwy_q['TotalPaid']), $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%date.created%%', date($m4is_qnjfv['date_format'], strtotime($m4is_etwy_q['DateCreated']) ), $m4is_ks1fj2 );
 if ( ! empty( $m4is_etwy_q['!payment_due'] ) ) { $m4is_ks1fj2 = str_ireplace('%%amount.due%%', sprintf( '%0.2f', $m4is_etwy_q['!payment_due'] ), $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%date.due%%', 'Past Due', $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%creditcard.dropdown%%', $m4is_z_mv, $m4is_ks1fj2);
 if ( $m4is_qnjfv['merchant_id'] > 0 && ( ! empty( $m4is_i3aq ) ) ) { $m4is_ks1fj2 = str_ireplace( '%%submit%%', '<input type="submit" class="memb_invoice_payment_button" value="' . $m4is_qnjfv['button_text'] . '">', $m4is_ks1fj2);
 } else { $m4is_ks1fj2 = str_ireplace('%%submit%%', '', $m4is_ks1fj2);
 } } else { $m4is_ks1fj2 = str_ireplace('%%amount.due%%', '0.00', $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%date.due%%', date($m4is_qnjfv['date_format'], strtotime($m4is_etwy_q['DateCreated']) ), $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%creditcard.dropdown%%', '', $m4is_ks1fj2);
 $m4is_ks1fj2 = str_ireplace('%%submit%%', '', $m4is_ks1fj2);
 } $m4is_uzfw8j .= $m4is_ks1fj2;
 } } $m4is_uzfw8j .= $m4is_qnjfv['post'];
 return do_shortcode($m4is_uzfw8j);
 } static 
function m4is_oaem($m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_i3aq = false;
 static $m4is_wb9f = false;
 $m4is_r6nh_b = [ 'cancel_text' => 'Cancel', 'confirm_button' => 'Yes, Stop Subscription', 'confirm_cancel' => 'Keep Subscription', 'confirm_title' => 'Cancel Subscription?', 'confirm' => 0, 'date_format' => 'M d, Y', 'immediate' => false,  'jqueryui' => 1, 'onlyids' => '', 'orderby' => 'StartDate', 'sort' => 'a',  'status' => 'all',  ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! self::$m4is_e2kg ) { return;
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['confirm'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['confirm'], true);
 $m4is_qnjfv['immediate'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['immediate'], false);
 $m4is_qnjfv['jqueryui'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['jqueryui'], true);
 $m4is_qnjfv['status'] = ucwords(trim($m4is_qnjfv['status']) );
 $m4is_qnjfv['sort'] = substr(strtolower(trim($m4is_qnjfv['sort']) ), 0, 1);
 $m4is_qnjfv['orderby'] = trim($m4is_qnjfv['orderby']);
 $m4is_f8qb1a = ($m4is_qnjfv['sort'] == 'a');
 $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 $m4is_z8sd = m4is_untczd::m4is_l1tycu();
 $m4is_jt5l9 = m4is_untczd::m4is_k896();
 $m4is_wb9f = self::$m4is_bnd6ti->m4is_ts0h3x( self::$m4is_e2kg );
 if (is_array($m4is_wb9f) ) { $m4is_qnjfv['onlyids'] = array_filter(explode(',', $m4is_qnjfv['onlyids']) );
 foreach ($m4is_wb9f as $m4is_s2ge5=>$m4is__oep) { if ($m4is_qnjfv['status'] <> 'All') { if (strtolower($m4is_qnjfv['status']) <> strtolower($m4is__oep['Status']) ) { unset($m4is_wb9f[$m4is_s2ge5]);
 } } } if (! empty($m4is_qnjfv['onlyids']) ) { foreach($m4is_wb9f as $m4is_s2ge5 => $m4is_ereh) { if (! in_array($m4is_ereh['ProgramId'], $m4is_qnjfv['onlyids']) ) { if (! in_array($m4is_ereh['SubscriptionPlanId'], $m4is_qnjfv['onlyids']) ) { unset($m4is_wb9f[$m4is_s2ge5]);
 } } } } usort($m4is_wb9f, function($a, $b) use ($m4is_qnjfv, $m4is_f8qb1a) { $orderby = $m4is_qnjfv['orderby'];
 if ($a[$orderby] == $b[$orderby]) { $order = 0;
 } if ($m4is_f8qb1a) { $order = $a[$orderby] < $b[$orderby] ? -1 : 1;
 } else { $order = $a[$orderby] > $b[$orderby] ? -1 : 1;
 } return $order;
 });
 } $m4is_wcal = ( is_array( $m4is_wb9f ) && ! empty( $m4is_wb9f ) );
 $m4is__32_p = 0;
 $m4is_uzfw8j = '';
 if ( $m4is_wcal && trim( $m4is_z50f ) == '' ) { $m4is_z50f = '<p>
			%%line%% - %%cycler%% -
			Subscription Name: %%subscription.name%%<br />
			Subscription Status:  %%subscription.status%%<br />
			Subscription Price: %%subscription.price%%<br />
			Subscription Billing Cycle:  %%subscription.billingcycle%%<br />
			Credit Card:  %%creditcard.last4%%<br />
			Card Type: %%creditcard.type%%<br />
			Card Expiration: %%creditcard.expmonth%% / %%creditcard.expyear%%<br />
			Subscription Start Date: %%subscription.startdate%%<br />
			Subscription Paid Through Date: %%subscription.paidthrough%%<br />
			Subscription Next Billing Date: %%subscription.nextbilling%%<br />
			Subscription Status: %%subscription.status%%<br />
			Keywords: %%subscription._keywords%%<br />
			%%cancel.button%%
			</p>';
 } $m4is_z50f = m4is_crqo::m4is_mm2xd( $m4is_z50f, $m4is_carw7y, true, $m4is_wcal );
 if ($m4is_wcal) { $m4is_w_8g = m4is_ho3l::m4is_kjedy2('RecurringOrder');
 foreach ( $m4is_wb9f as $m4is_s2ge5=>$m4is__oep) { $m4is__32_p++;
 $m4is_xk_cl = false;
 $m4is_zg8z = _x( $m4is__oep['Status'], 'memb_list_subscriptions', 'memberium' );
 switch ($m4is__oep['BillingCycle']) { case 6: $m4is__oep['BillingCycleWord1'] = _x('Daily', 'memb_list_subscriptions', 'memberium');
 $m4is__oep['BillingCycleWord2'] = _x('Days', 'memb_list_subscriptions', 'memberium');
 break;
 case 3: $m4is__oep['BillingCycleWord1'] = _x('Weekly', 'memb_list_subscriptions', 'memberium');
 $m4is__oep['BillingCycleWord2'] = _x('Weeks', 'memb_list_subscriptions', 'memberium');
 break;
 case 2: $m4is__oep['BillingCycleWord1'] = _x('Monthly', 'memb_list_subscriptions', 'memberium');
 $m4is__oep['BillingCycleWord2'] = _x('Months', 'memb_list_subscriptions', 'memberium');
 break;
 case 1: $m4is__oep['BillingCycleWord1'] = _x('Annually', 'memb_list_subscriptions', 'memberium');
 $m4is__oep['BillingCycleWord2'] = _x('Years', 'memb_list_subscriptions', 'memberium');
 break;
 } if (empty($m4is__oep['PaidThruDate']) ) { $m4is__oep['PaidThruDate'] = $m4is__oep['StartDate'];
 } $m4is_rbwn1z = base64_encode(serialize([ 'cancel_text' => $m4is_qnjfv['cancel_text'], 'immediate' => $m4is_qnjfv['immediate'], 'next_bill_date' => $m4is__oep['NextBillDate'], 'paid_through_date' => $m4is__oep['PaidThruDate'], 'recurringorder_id' => (int) $m4is__oep['Id'], 'subscriptionplan_id' => (int) $m4is__oep['SubscriptionPlanId'], ]) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is_ktg12s = '<form method="post" class="memberium-subscription-list" action="">';
 $m4is_ktg12s .= wp_nonce_field('memb_cancelsubscription_' . $m4is__oep['Id'], '_wpnonce', true, false);
 $m4is_ktg12s .= '<input type="hidden" name="memb_form_type" value="memb_cancel_subscription">';
 $m4is_ktg12s .= '<input type="hidden" name="parameters" value="' . $m4is_rbwn1z . '">';
 $m4is_ktg12s .= '<input type="hidden" name="signature" value="' . $m4is_k1k7oj . '">';
 $m4is_ktg12s .= $m4is_z50f;
 if ($m4is__oep['Frequency'] > 1) { $m4is_q6jh = 'Every ' . $m4is__oep['Frequency'] . ' ' . $m4is__oep['BillingCycleWord2'];
 } else { $m4is_q6jh = $m4is__oep['BillingCycleWord1'];
 } if ($m4is__32_p % 2) { $m4is_p5ehv = 'odd';
 } else { $m4is_p5ehv = 'even';
 } $m4is_sm5bg = empty( $m4is__oep['StartDate'] ) ? __('None') : date( $m4is_qnjfv['date_format'], strtotime($m4is__oep['StartDate'] ) );
 $m4is_xgbs = empty( $m4is__oep['NextBillDate'] ) ? __('None') : date( $m4is_qnjfv['date_format'], strtotime($m4is__oep['NextBillDate'] ) );
 $m4is_ktg12s = str_ireplace( '%%creditcard.expmonth%%', isset( $m4is_i3aq[$m4is__oep['CC1']]['ExpirationMonth']) ? $m4is_i3aq[$m4is__oep['CC1']]['ExpirationMonth'] : '', $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%creditcard.expyear%%', isset( $m4is_i3aq[$m4is__oep['CC1']]['ExpirationYear']) ? $m4is_i3aq[$m4is__oep['CC1']]['ExpirationYear'] : '', $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%creditcard.id%%', (isset( $m4is_i3aq['Id']) ? $m4is_i3aq['Id'] : ''), $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%creditcard.last4%%', isset( $m4is_i3aq[$m4is__oep['CC1'] ]['Last4']) ? 'XXXX-' . $m4is_i3aq[$m4is__oep['CC1'] ]['Last4'] : '', $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%creditcard.type%%', isset( $m4is_i3aq[ $m4is__oep['CC1'] ]['CardType']) ? $m4is_i3aq[ $m4is__oep['CC1'] ]['CardType'] : '', $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%cycler%%', $m4is_p5ehv, $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%line%%', $m4is__32_p, $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%subscription.billingcycle%%', $m4is_q6jh, $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%subscription.id%%', $m4is__oep['Id'], $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%subscription.name%%', $m4is_z8sd[ $m4is_jt5l9[ $m4is__oep['SubscriptionPlanId'] ]['ProductId'] ]['ProductName'], $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%subscription.nextbilling%%', $m4is_xgbs, $m4is_ktg12s);
 $m4is_ktg12s = str_ireplace( '%%subscription.paidthrough%%', date( $m4is_qnjfv['date_format'], strtotime( $m4is__oep['PaidThruDate'] ) ), $m4is_ktg12s );
 $m4is_ktg12s = str_ireplace( '%%subscription.price%%', number_format( $m4is__oep['BillingAmt'], 2 ), $m4is_ktg12s );
 $m4is_ktg12s = str_ireplace( '%%subscription.startdate%%', $m4is_sm5bg, $m4is_ktg12s );
 $m4is_ktg12s = str_ireplace( '%%subscription.status%%', $m4is_zg8z, $m4is_ktg12s );
 foreach($m4is_w_8g as $m4is_g1ru50) { if ($m4is_g1ru50[0] == '_' && isset($m4is__oep[$m4is_g1ru50]) ) {;
 $m4is_ktg12s = str_ireplace('%%subscription.' . $m4is_g1ru50 . '%%', $m4is__oep[$m4is_g1ru50], $m4is_ktg12s);
 } } if (! empty($m4is__oep['EndDate']) ) { $m4is_ktg12s = str_ireplace('%%subscription.enddate%%', date($m4is_qnjfv['date_format'], strtotime($m4is__oep['EndDate']) ), $m4is_ktg12s);
 } else { $m4is_ktg12s = str_ireplace('%%subscription.enddate%%', '', $m4is_ktg12s);
 } if (strtolower($m4is__oep['Status']) == 'active' && empty($m4is__oep['EndDate']) ) { $m4is_ktg12s = str_ireplace('%%cancel.button%%', '<input type="submit" class="memb_subscription_cancel_button" value="' . $m4is_qnjfv['cancel_text'] . '">', $m4is_ktg12s);
 } elseif (! empty($m4is__oep['EndDate']) ){ $m4is_ktg12s = str_ireplace('%%cancel.button%%', __('Cancelled', 'memberium'), $m4is_ktg12s);
 } else { $m4is_ktg12s = str_ireplace('%%cancel.button%%', '', $m4is_ktg12s);
 } $m4is_ktg12s .= '</form>';
 $m4is_uzfw8j .= do_shortcode($m4is_ktg12s);
 } unset($m4is_q6jh);
 } else { $m4is_uzfw8j .= $m4is_z50f;
 } if ( $m4is_qnjfv['confirm'] ) { $params = [ 'confirmTitle' => $m4is_qnjfv['confirm_title'], 'confirmButton' => $m4is_qnjfv['confirm_button'], 'confirmCancel' => $m4is_qnjfv['confirm_cancel'], ];
 if ( $m4is_qnjfv['jqueryui'] ) { $m4is_yclkvi = get_bloginfo( 'version' );
 if ( version_compare( $m4is_yclkvi, '5.6', 'ge' ) ) { wp_enqueue_script( 'jqueryui', '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js' );
 wp_enqueue_style( 'jqueryuitheme', '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css' );
 } else { wp_enqueue_script( 'jqueryui', '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js' );
 wp_enqueue_style( 'jqueryuitheme', '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/themes/smoothness/jquery-ui.css' );
 } } wp_enqueue_script( 'memberium-cancellation-confirmation', plugins_url( 'js/cancellation-confirm.js', MEMBERIUM_HOME ) );
 wp_localize_script( 'memberium-cancellation-confirmation', 'subscriptionCancelText', $params );
 }  $m4is_uzfw8j = preg_replace('/(%%\S+%%)/', '', $m4is_uzfw8j);
 return do_shortcode($m4is_uzfw8j);
 } static 
function m4is_k4o9($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'contact_id' => 0, 'invoice_id' => isset($_GET['invoice_id']) ? (int) $_GET['invoice_id'] : 0, 'product_ids' => '', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (is_feed() || ! is_singular() ) { return;
 } $m4is_uzfw8j = '';
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['contact_id'] = $m4is_qnjfv['contact_id'] ? $m4is_qnjfv['contact_id'] : m4is_wbc8os::m4is_jjgo();
 $m4is_qnjfv['product_ids'] = array_filter(explode(',', $m4is_qnjfv['product_ids']) );
 if (empty($m4is_qnjfv['contact_id']) || empty($m4is_qnjfv['product_ids']) ) { return;
 } $m4is_craco = self::$m4is_bnd6ti->m4is_ow9yjk($m4is_qnjfv['contact_id']);
 if ($m4is_qnjfv['invoice_id']) { $m4is_c4lk = $m4is_qnjfv['invoice_id'];
 $m4is_craco = isset($m4is_craco[$m4is_c4lk]) ? [$m4is_c4lk => $m4is_craco[$m4is_c4lk] ] : [];
 } foreach($m4is_craco as $m4is_etwy_q) { $m4is_z8sd = isset($m4is_etwy_q['ProductSold']) ? explode(',', $m4is_etwy_q['ProductSold']) : [];
 if (! empty( array_intersect($m4is_z8sd, $m4is_qnjfv['product_ids']) ) ) { $m4is_tryit6 = true;
 break;
 } } $m4is_uzfw8j = m4is_crqo::m4is_mm2xd($m4is_z50f, $m4is_carw7y, TRUE, $m4is_tryit6);
 return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture']);
 } static 
function m4is_hdrlm($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'capture' => '', 'contact_id' => 0, 'invoice_id' => isset($_GET['invoice_id']) ? (int) $_GET['invoice_id'] : 0, 'status' => 'Active', 'subscription_ids' => '', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (is_feed() || ! is_singular() ) { return;
 } $m4is_uzfw8j = '';
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['contact_id'] = $m4is_qnjfv['contact_id'] ? $m4is_qnjfv['contact_id'] : m4is_wbc8os::m4is_jjgo();
 $m4is_qnjfv['subscription_ids'] = array_filter(explode(',', $m4is_qnjfv['subscription_ids']) );
 $m4is_qnjfv['status'] = strtolower($m4is_qnjfv['status']);
 if (empty($m4is_qnjfv['contact_id']) || empty($m4is_qnjfv['subscription_ids']) ) { return;
 } $m4is_wb9f = self::$m4is_bnd6ti->m4is_ts0h3x($m4is_qnjfv['contact_id']);
 if ($m4is_qnjfv['invoice_id']) { $m4is_c4lk = $m4is_qnjfv['invoice_id'];
 $m4is_wb9f = isset($m4is_wb9f[$m4is_c4lk]) ? [$m4is_c4lk => $m4is_wb9f[$m4is_c4lk] ] : [];
 } if (! empty($m4is_qnjfv['status'])) { foreach($m4is_wb9f as $m4is_j5sy07 => $m4is__oep) { if (strtolower($m4is__oep['Status']) <> $m4is_qnjfv['status']) { unset($m4is_wb9f[$m4is_j5sy07]);
 } } } foreach($m4is_wb9f as $m4is__oep) { if (in_array($m4is__oep['SubscriptionPlanId'], $m4is_qnjfv['subscription_ids']) ) { $m4is_br3z = true;
 break;
 } } $m4is_uzfw8j = m4is_crqo::m4is_mm2xd($m4is_z50f, $m4is_carw7y, TRUE, $m4is_br3z);
 return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture']);
 }     static 
function m4is_fyatqi($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } if (is_feed() ) { return;
 } if (empty($_SERVER['HTTPS']) ) { if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '<p>Order Form Disabled Due to Missing SSL</p>';
 } return;
 } $m4is_r6nh_b = [ 'autofill' => 'n', 'branding' => 'n', 'button_url' => '', 'cache' => HOUR_IN_SECONDS * 24, 'capture' => '', 'form_id' => '', 'form_url' => '', 'remove_styles' => 'y', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 if (false !== strpos($m4is_qnjfv['form_url'], '.infusionsoft.com/saleform/') ) { $m4is_qnjfv['form_url'] = str_ireplace('.infusionsoft.com/', '.infusionsoft.app/', $m4is_qnjfv['form_url']);
 } if (false === strpos($m4is_qnjfv['form_url'], '.infusionsoft.app/saleform/') ) { return _x('Invalid Form Embed', 'memb_orderform', 'memberium');
 } if (false === stripos($m4is_qnjfv['form_url'], '?cookieSearchStarted=true&cookieStopSearch=true') ) { $m4is_qnjfv['form_url'] .= '?cookieSearchStarted=true&cookieStopSearch=true';
 } $m4is_qdks9n = $m4is_qnjfv['cache'];
 $m4is_rc0t = $m4is_qnjfv['form_url'];
 $m4is_qnjfv['branding'] = strtolower(substr($m4is_qnjfv['branding'], 0, 1) );
 $m4is_qnjfv['autofill'] = strtolower(substr($m4is_qnjfv['autofill'], 0, 1) );
 $m4is_qnjfv['remove_styles'] = strtolower(substr($m4is_qnjfv['remove_styles'], 0, 1) );
 $m4is_g8jqh = false;
 $m4is_zr29 = 'memberium_orderform_' . md5($m4is_rc0t);
 if ($m4is_qdks9n > 0) { $m4is_g8jqh = get_transient($m4is_zr29);
 }  if ($m4is_g8jqh == false) { $m4is_o9_6u = wp_remote_get($m4is_rc0t);
  if (is_array($m4is_o9_6u) ) { preg_match('/<body>(.*)<\/body>/sm', $m4is_o9_6u['body'], $m4is_oa_z);
 if (isset($m4is_oa_z[1]) ) { $m4is_g8jqh = $m4is_oa_z[1];
 set_transient($m4is_zr29, $m4is_g8jqh, $m4is_qdks9n);
 } } else { return $m4is_o9_6u->errors['http_request_failed'][0];
 } } if ($m4is_qnjfv['remove_styles'] == 'y') { $m4is_g8jqh = preg_replace('/<style>(.*)<\/style>/imU', '', $m4is_g8jqh);
 } if ($m4is_qnjfv['form_id'] > '') { $m4is_g8jqh = str_replace('id="orderForm"', 'id="' . $m4is_xi5w . '"  ', $m4is_g8jqh);
 } if ($m4is_qnjfv['autofill'] == 'y') { foreach ($_GET as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_g8jqh = str_replace('name=\'' . $m4is_s2ge5 . '\' value=\'\'', 'name="' . $m4is_s2ge5 . '" value="' . $m4is_w_o7al . '"', $m4is_g8jqh);
 } } if ($m4is_qnjfv['button_url'] > '') { $m4is_mvg23 = '<input type="image" value="Order" id="Order" class="default-input sale-orderbutton np inf-button" name="Order" src="' . $m4is_qnjfv['button_url'] . '" style="width:auto;overflow:visible;"/>';
 $m4is_g8jqh = preg_replace('/<input(.*)id="Order"(.*)>/iU', $m4is_mvg23, $m4is_g8jqh);
 } if ($m4is_qnjfv['branding'] == 'n') { $m4is_g8jqh = str_replace('Powered By Keap', '', $m4is_g8jqh);
 } if ($m4is_qnjfv['capture'] > '') { $m4is_g8jqh = m4is_crqo::m4is_uyv45q($m4is_g8jqh, $m4is_qnjfv['capture']);
 } return $m4is_g8jqh;
 } static 
function m4is_u_1iv3($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'autorun' => 'no', 'button_name' => 'order_button', 'button_text' => '', 'bypass_commissions' => 'no', 'delete_failed' => 'yes', 'fail_action' => '', 'fail_goals' => '', 'fail_tags' => '', 'fail_url' => '', 'lead_affiliate_id' => 0, 'merchant_id' => (int) self::$m4is_bnd6ti->m4is_oiewvu('settings', 'merchant_account_id'), 'prod_description' => '', 'prod_id' => 0, 'prod_name' => '', 'prod_price' => '', 'prod_type' => 4, 'qty' => 1, 'sales_affiliate_id' => 0, 'success_action' => '', 'success_goals' => '', 'success_tags' => '', 'success_url' => '', 'taxable' => 'no', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! self::$m4is_e2kg ) { return;
 } static $m4is_su4qk = 0;
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['autorun'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['autorun'], false);
 $m4is_qnjfv['bypass_commissions'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['bypass_commissions'], false);
 $m4is_qnjfv['delete_failed'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['delete_failed'], true);
 $m4is_qnjfv['taxable'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['taxable'], false);
 $m4is_qnjfv['button_text'] = $m4is_qnjfv['button_text'] > '' ? $m4is_qnjfv['button_text'] : 'Buy Now' . $price;
  $m4is_i3aq = m4is_akcfiz::m4is_ms5b( self::$m4is_e2kg );
 if (is_array($m4is_i3aq) && count($m4is_i3aq) > 0) { $m4is_l2waj = end($m4is_i3aq);
 $m4is__4en6o = (int) $m4is_l2waj['Id'];
 unset($m4is_l2waj, $m4is_i3aq);
 } else { return;
 } foreach($m4is_r6nh_b as $m4is_s2ge5 => $m4is_w_o7al) { $m4is_qnjfv[$m4is_s2ge5] = trim($m4is_qnjfv[$m4is_s2ge5]);
 } $m4is_negcx = [ 'has_payment_plan' => false, 'autorun' => (bool) $m4is_qnjfv['autorun'], 'bypass_commissions' => (bool) $m4is_qnjfv['bypass_commissions'], 'delete_failed' => (bool) $m4is_qnjfv['delete_failed'], 'taxable' => (bool) $m4is_qnjfv['taxable'], 'product_price' => (float) $m4is_qnjfv['prod_price'], 'creditcard_id' => (int) $m4is__4en6o, 'lead_affiliate_id' => (int) $m4is_qnjfv['lead_affiliate_id'], 'merchant_id' => (int) $m4is_qnjfv['merchant_id'], 'product_id' => (int) $m4is_qnjfv['prod_id'], 'product_type' => (int) $m4is_qnjfv['prod_type'], 'quantity' => (int) $m4is_qnjfv['qty'], 'sales_affiliate_id' => (int) $m4is_qnjfv['sales_affiliate_id'], 'fail_action' => $m4is_qnjfv['fail_action'], 'fail_goals' => $m4is_qnjfv['fail_goals'], 'fail_tags' => $m4is_qnjfv['fail_tags'], 'fail_url' => $m4is_qnjfv['fail_url'], 'product_description' => $m4is_qnjfv['prod_description'], 'product_name' => $m4is_qnjfv['prod_name'], 'success_action' => $m4is_qnjfv['success_action'], 'success_goals' => $m4is_qnjfv['success_goals'], 'success_tags' => $m4is_qnjfv['success_tags'], 'success_url' => $m4is_qnjfv['success_url'], ];
 if ($m4is_qnjfv['autorun']) { $m4is_c4lk = (int) self::$m4is_bnd6ti->m4is_yep9($m4is_negcx);
 if ($m4is_c4lk) { if ($m4is_qnjfv['success_url'] > '') { $m4is_b5kaz0 = $m4is_qnjfv['success_url'];
 } } else { if ($m4is_qnjfv['fail_url'] > '') { $m4is_b5kaz0 = $m4is_qnjfv['fail_url'];
 } } self::$m4is_bnd6ti->m4is_m3vz( self::$m4is_e2kg );
 m4is_aoxw::m4is_g7bv();
 wp_redirect($m4is_b5kaz0, 302);
 exit;
 } else { $m4is_su4qk++;
 $m4is_negcx = base64_encode(serialize($m4is_negcx) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_negcx);
 $form_name = 'place_order_button-' . $m4is_su4qk;
 $m4is_qnjfv['button_name'] = 'place_order_button_' . $m4is_su4qk;
 $m4is_tjg_9 = '';
 $m4is_tjg_9 .= "<form name=\"{$form_name}\" id=\"{$form_name}\" method=\"post\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"memb_form_type\" value=\"memb_place_order\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"form_id\" value=\"{$m4is_su4qk}\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"order_settings\" value=\"{$m4is_negcx}\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"digital_signature\" value=\"{$m4is_k1k7oj}\">";
 $m4is_tjg_9 .= wp_nonce_field('place_order_button-' . $m4is_su4qk, '_wpnonce', true, false);
 if ($button_url == '') { $m4is_tjg_9 .= "<input type=\"submit\" class=\"{$css_class}\" id=\"{$m4is_qnjfv['button_name']}\" value=\"{$m4is_qnjfv['button_text']}\">";
 } else { $m4is_tjg_9 .= "<input type=\"image\" src=\"{$button_url}\" class=\"{$css_class}\" id=\"{$m4is_qnjfv['button_name']}\" >";
 } $m4is_tjg_9 .= "</form>";
 return $m4is_tjg_9;
 } }   static 
function m4is_cs8dxu($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') {   if ( self::$m4is_o3m_c5 ) { return '';
 } global $wpdb;
 $m4is_r6nh_b = [ 'action_id' => 0, 'button_url' => 0, 'css_class' => '', 'error_url' => '', 'success_url' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! self::$m4is_e2kg ) { return;
 } static $m4is_su4qk = 1001;
 $m4is_uxc7v = _x('Submit', 'memb_one_click_sale', 'memberium');
 if (isset($m4is_qnjfv['unavailable_text']) ) { $m4is_d54p8 = $m4is_qnjfv['unavailable_text'];
 } else { $m4is_d54p8 = _x('This offer is only available with a qualifying purchase.', 'memb_one_click_sale', 'memberium');
 } if (isset($_SESSION['is4wp_purchase_session']['contactId']) ) { $m4is_e2kg = $_SESSION['is4wp_purchase_session']['contactId'];
 } else { return $m4is_d54p8;
 } if (isset($_SESSION['is4wp_purchase_session']['orderId']) ) { $m4is_ae8w = $_SESSION['is4wp_purchase_session']['orderId'];
 } else { return $m4is_d54p8;
 }  if ($m4is_su4qk == 0) { $m4is_su4qk = 1001;
 } $m4is__c1d = $m4is_qnjfv['action_id'];
 $m4is_bbjlns = $m4is_qnjfv['button_url'];
 $m4is_b5kaz0 = $m4is_qnjfv['success_url'];
 $m4is_sp2a3 = $m4is_qnjfv['error_url'];
 $m4is_bxz0o = $m4is_qnjfv['css_class'];
 $m4is_d54p8 = '<span class="is4wp_client_error">' . $m4is_d54p8 . '</span>';
 if (isset($m4is_qnjfv['button_text']) && $m4is_qnjfv['button_text' > '']) $m4is_uxc7v = $m4is_qnjfv['button_text'];
 if ( self::$m4is_e2kg == 0 || $m4is__c1d == 0 || $m4is_ae8w == 0 || ! isset($_GET['infusion_xid']) || ! isset($_GET['infusion_type']) || ! ($_GET['infusion_type'] == 'CustomFormSale') ) { return $m4is_d54p8;
 }  $m4is_w_8g = [ 'Id' ];
 $m4is_jo8fb = [ 'Id' => $m4is_ae8w, 'ContactId' => self::$m4is_e2kg, ];
 $m4is_auoz = self::$m4is_j_xo4w->dsLoad('Job', intval($m4is_ae8w), $m4is_w_8g);
 if ($m4is_auoz['Id'] <> $m4is_ae8w) { return $m4is_d54p8;
 } $m4is_w_8g = [ 'Id', 'Last4', 'CardType', 'Status', 'ContactId' ];
 $m4is_jo8fb = [ 'ContactId' => $m4is_e2kg, ];
 $m4is_jo8fb = [ 'ContactId' => $m4is_e2kg, 'CardType' => $_GET['CreditCard0CardType'], 'ExpirationYear' => $_GET['CreditCard0ExpirationYear'], 'ExpirationMonth' => $_GET['CreditCard0ExpirationMonth'], ];
 $m4is_ufc7 = m4is_ho3l::m4is_mg4uyc('CreditCard', 1, 0, $m4is_jo8fb, $m4is_w_8g);
 if (count($m4is_ufc7) == 0) { return $m4is_d54p8;
 }  $m4is_su4qk++;
 $m4is_npof41 = 'is4wp_oneclick_sale_form_' . $m4is_su4qk;
 $m4is__0dt14 = 'is4wp_oneclick_sale_button_' . $m4is_su4qk;
 $m4is_rbwn1z = base64_encode(serialize([ 'action_id' => $m4is__c1d, 'Contact0Email' => $_GET['Contact0Email'], 'contact_id' => $m4is_e2kg, 'order_id' => $m4is_ae8w, '$elv_redirect_url' => $m4is_b5kaz0, ]) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is_tjg_9 = '';
 $m4is_tjg_9 .= "<form name=\"{$m4is_npof41}\" id=\"{$m4is_npof41}\" method=\"post\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"is4wp_form_type\" value=\"is4wp_oneclick_sale\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"form_id\" value=\"{$m4is_su4qk}\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"parameters\" value=\"{$m4is_rbwn1z}\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"digital_signature\" value=\"{$m4is_k1k7oj}\">";
 $m4is_tjg_9 .= wp_nonce_field('oneclick_sale_' . $m4is_su4qk, '_wpnonce', true, false);
 if ($m4is_bbjlns == '') { $m4is_tjg_9 .= "<input type=\"submit\" class=\"{$m4is_bxz0o}\" id=\"{$m4is__0dt14}\" value=\"{$m4is_uxc7v}\">";
 } else { $m4is_tjg_9 .= "<input type=\"image\" src=\"{$m4is_bbjlns}\" class=\"{$m4is_bxz0o}\" id=\"{$m4is__0dt14}\" >";
 } $m4is_tjg_9 .= "</form>";
 return $m4is_tjg_9;
 } static 
function m4is_cdyo($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'autorun' => 'y',  'bypass_commissions' => 'n', 'debug' => 'n',  'description' => '',  'has_all_tags' => '',  'has_any_tag' => '',  'failure_action' => '', 'failure_goal' => '', 'failure_tag' => '', 'failure_url' => '', 'id' => 0,  'keep_failed' => 'n',  'lead_affiliate_id' => isset($_SESSION['infusionsoft_affiliate']) ? (int) $_SESSION['infusionsoft_affiliate'] : 0, 'merchant_id' => self::$m4is_bnd6ti->m4is_oiewvu('settings', 'merchant_account_id'),  'name' => '',  'order_title' => '', 'payment_description' => 'Memberium Online Purchase', 'plan_autocharge' => 'n',  'plan_initial_payment' => -1,  'plan_max_retries' => 3,  'plan_payment_count' => 1,  'plan_payment_interval' => 30,  'plan_retry_days' => 2,  'plan_start_date' => 'now',  'price' => -1,  'quantity' => 1, 'sale_affiliate_id' => isset($_SESSION['infusionsoft_affiliate']) ? (int) $_SESSION['infusionsoft_affiliate'] : 0, 'success_action' => '', 'success_goal' => '', 'success_tag' => '', 'success_url' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($defaults, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['autorun'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['autorun'], true);
 $m4is_qnjfv['bypass_commissions'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['bypass_commissions'], false);
 $m4is_qnjfv['id'] = (int) $m4is_qnjfv['id'];
 $m4is_qnjfv['keep_failed'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['keep_failed'], false);
 $m4is_qnjfv['lead_affiliate_id'] = (int) $m4is_qnjfv['lead_affiliate_id'];
 $m4is_qnjfv['merchant_id'] = (int) $m4is_qnjfv['merchant_id'];
 $m4is_qnjfv['name'] = trim($m4is_qnjfv['name']);
 $m4is_qnjfv['price'] = (double) $m4is_qnjfv['price'];
 $m4is_qnjfv['quantity'] = (int) $m4is_qnjfv['quantity'];
 $m4is_qnjfv['sale_affiliate_id'] = (int) $m4is_qnjfv['sale_affiliate_id'];
 if (! empty($m4is_qnjfv['m4is_v1dwme']) ) { if (! self::$m4is_bnd6ti->m4is_sjmzx($m4is_qnjfv['has_any_tag']) ) { return;
 } } if (! empty($m4is_qnjfv['m4is_mhx6']) ) { if (! self::$m4is_bnd6ti->m4is_mhx6($m4is_qnjfv['has_all_tags']) ) { return;
 } } $m4is_e2kg = (int) self::$m4is_hiwyd;
 $m4is__4en6o = 0;
 $m4is_ae8w = 0;
 $m4is_z8sd = m4is_untczd::m4is_j68se();
 $m4is_haon5 = true;
  $m4is_v6fdv4 = $m4is_qnjfv['failure_action'];
 $m4is_xf9b = $m4is_qnjfv['failure_goal'];
 $m4is_mpia = $m4is_qnjfv['failure_tag'];
 $m4is_imdo6 = $m4is_qnjfv['failure_url'];
 if (isset($m4is_z8sd[$m4is_qnjfv['id']]) ) { $m4is_si73 = $m4is_z8sd[$m4is_qnjfv['id']];
 } elseif ($m4is_qnjfv['name'] > '') { $m4is_qnjfv['id'] = 0;
 foreach($m4is_z8sd as $m4is_si73) { if (0 === strcasecmp ($m4is_si73['ProductName'] , $m4is_qnjfv['name']) && $m4is_si73['Status'] == 1) { $m4is_qnjfv['id'] = (int) $m4is_si73['Id'];
 break;
 } } } unset($m4is_z8sd);
  if ($m4is_qnjfv['id'] < 1) { $m4is_haon5 = false;
 } if ($m4is_qnjfv['quantity'] < 1) { $m4is_haon5 = false;
 } if ($m4is_haon5 && $m4is_qnjfv['merchant_id'] < 0) { $m4is_haon5 = false;
 } if ($m4is_haon5 && $m4is_qnjfv['price'] < 0) { $m4is_qnjfv['price'] = (double) $m4is_si73['ProductPrice'];
 }   if ($m4is_haon5) { if (! ( (int) $m4is__4en6o) ) { $m4is_i3aq = m4is_akcfiz::m4is_ms5b( $m4is_e2kg );
 $m4is_i3aq = m4is_akcfiz::m4is_l9v0jb( $m4is_i3aq );
 $m4is__4en6o = (int) $m4is_i3aq['Id'];
 } }  if ($m4is_haon5) { $m4is_qnjfv['order_title'] = empty($m4is_qnjfv['order_title']) ? $m4is_si73['ProductName'] : $m4is_qnjfv['order_title'];
 $m4is_grodai = date_default_timezone_get();
 date_default_timezone_set ('America/New_York');
 $m4is_jl7j9 = date('Ymd\TH:i:s');
 $m4is_c4lk = self::$m4is_j_xo4w->blankOrder($m4is_e2kg, $m4is_qnjfv['order_title'], $m4is_jl7j9, $m4is_qnjfv['lead_affiliate_id'], $m4is_qnjfv['sale_affiliate_id']);
 if ($m4is_c4lk > 0) { $m4is_c4lk = (int) $m4is_c4lk;
 $m4is_oa_z = self::$m4is_j_xo4w->addOrderItem($m4is_c4lk, $m4is_qnjfv['id'], 4, $m4is_qnjfv['price'], $m4is_qnjfv['quantity'], $m4is_si73['ProductName'], $m4is_qnjfv['description']);
 if ($m4is_si73['Taxable'] || $m4is_si73['CountryTaxable'] || $m4is_si73['StateTaxable'] || $m4is_si73['CityTaxable']) { self::$m4is_j_xo4w->recalculateTax($m4is_c4lk);
 } $m4is_q5lyu0 = self::$m4is_j_xo4w->chargeInvoice($m4is_c4lk, $m4is_qnjfv['payment_description'], $m4is__4en6o, $m4is_qnjfv['merchant_id'], (bool) $m4is_qnjfv['bypass_commissions']);
 if (! in_array(strtolower($m4is_q5lyu0['Code']), ['declined', 'error'] ) ) {  $m4is_v6fdv4 = $success_action;
 $m4is_xf9b = $success_goal;
 $m4is_mpia = $success_tag;
 $m4is_imdo6 = $success_url;
 } else {  if (! $m4is_qnjfv['keep_failed']) { self::$m4is_j_xo4w->deleteInvoice($m4is_c4lk);
 } } } date_default_timezone_set ($m4is_grodai);
 } if (! empty($m4is_v6fdv4) ) { self::$m4is_bnd6ti->m4is_u86vzq($m4is_v6fdv4, $m4is_e2kg);
 } if (! empty($m4is_xf9b) ) { self::$m4is_bnd6ti->m4is_cqe6_($m4is_xf9b, $m4is_e2kg);
 } if (! empty($m4is_mpia) ) { self::$m4is_bnd6ti->m4is_tcle75($m4is_mpia, $m4is_e2kg);
 } self::$m4is_bnd6ti->m4is_leu58($m4is_e2kg);
 if (! empty($m4is_imdo6) ) {  echo '<script type="text/javascript"> window.location.replace("', $m4is_imdo6, '"); </script>';
 exit;
 } } static 
function m4is_ak52t8($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_c_8n = false;
 $m4is_r6nh_b = [ 'affiliate_id' => 0, 'allow_dupe' => 'n', 'autorun' => 'y',  'debug' => 'n', 'delay_days' => 0, 'dupe_action' => '', 'dupe_goal' => '', 'dupe_tag' => '', 'dupe_url' => '', 'failure_action' => '', 'failure_goal' => '', 'failure_tag' => '', 'failure_url' => '', 'first_only' => 'y', 'm4is_mhx6' => '', 'm4is_v1dwme' => '', 'id' => 0, 'keep_failed' => 'n', 'merchant_id' => self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'merchant_account_id' ), 'price' => -1, 'quantity' => 1, 'success_action' => '', 'success_goal' => '', 'success_tag' => '', 'success_url' => '', 'taxable' => 'n', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, 'memberium' );
 $m4is_qnjfv['m4is_v1dwme'] = trim( $m4is_qnjfv['m4is_v1dwme'] );
 $m4is_qnjfv['m4is_mhx6'] = trim( $m4is_qnjfv['m4is_mhx6'] );
 if ( ! empty( $m4is_qnjfv['m4is_v1dwme'] ) ) { if ( ! self::$m4is_bnd6ti->m4is_sjmzx( $m4is_qnjfv['m4is_v1dwme'] ) ) { return;
 } } if ( ! empty( $m4is_qnjfv['m4is_mhx6'] ) ) { if ( ! self::$m4is_bnd6ti->m4is_mhx6($m4is_qnjfv['m4is_mhx6'] ) ) { return;
 } } $m4is__4en6o = 0;
 $m4is_d9ybqg = 0;
 $m4is_haon5 = true;
 $m4is_e2kg = self::$m4is_e2kg;
 $m4is_wb9f = self::$m4is_bnd6ti->m4is_nign();
 $m4is_qnjfv['allow_dupe'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['allow_dupe'], false );
 $m4is_qnjfv['autorun'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['autorun'], true );
 $m4is_qnjfv['debug'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['debug'], true );
 $m4is_qnjfv['first_only'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['first_only'], true );
 $m4is_qnjfv['keep_failed'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['keep_failed'], false );
 $m4is_qnjfv['taxable'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['taxable'], false );
 $m4is_qnjfv['delay_days'] = (int) $m4is_qnjfv['delay_days'];
 $m4is_qnjfv['id'] = (int) $m4is_qnjfv['id'];
 $m4is_qnjfv['merchant_id'] = (int) $m4is_qnjfv['merchant_id'];
 $m4is_qnjfv['quantity'] = (int) $m4is_qnjfv['quantity'];
 if ( empty( $m4is_qnjfv['affiliate_id'] ) ) { $m4is_qnjfv['affiliate_id'] = self::$m4is_bnd6ti->m4is_q9of8a( $m4is_e2kg );
 } if ( $m4is_qnjfv['first_only'] && $m4is_c_8n ) { if ( $m4is_qnjfv['debug'] ) echo 'Already Executed.  Stopping.<br>';
 return '';
 } $m4is_c_8n = true;
  if (! isset($m4is_wb9f[$m4is_qnjfv['id']]) || $m4is_wb9f[$m4is_qnjfv['id']]['Active'] == 0) { $m4is_haon5 = false;
 } if ($m4is_qnjfv['delay_days'] < 0) { $m4is_haon5 = false;
 } if ($m4is_qnjfv['id'] < 0) { $m4is_haon5 = false;
 } if ($m4is_qnjfv['merchant_id'] < 0) { $m4is_haon5 = false;
 } if ($m4is_qnjfv['price'] < 0) { if (isset($m4is_wb9f[$m4is_qnjfv['id']]['PlanPrice']) ) { $m4is_qnjfv['price'] = (double) $m4is_wb9f[$m4is_qnjfv['id']]['PlanPrice'];
 } else { $m4is_haon5 = false;
 } } $m4is_qnjfv['price'] = (double) $m4is_qnjfv['price'];
 if ($m4is_qnjfv['quantity'] < 1) { $m4is_haon5 = false;
 } if ($m4is_haon5) {  if (! ( (int) $m4is__4en6o) ) { $m4is_i3aq = m4is_akcfiz::m4is_ms5b( $m4is_e2kg );
 $m4is_i3aq = m4is_akcfiz::m4is_l9v0jb( $m4is_i3aq );
 $m4is__4en6o = (int) $m4is_i3aq['Id'];
 if ($m4is_qnjfv['debug']) echo 'Credit Card ID = ', $m4is__4en6o, '<br>';
 } } if ( ! $m4is__4en6o ) { $m4is_haon5 = false;
 } $m4is_v6fdv4 = $m4is_qnjfv['failure_action'];
 $m4is_xf9b = $m4is_qnjfv['failure_goal'];
 $m4is_mpia = $m4is_qnjfv['failure_tag'];
 $m4is_imdo6 = $m4is_qnjfv['failure_url'];
 if ($m4is_haon5) { $m4is_c_8n = true;
 $m4is_d9ybqg = self::$m4is_j_xo4w->addRecurringAdv($m4is_e2kg, $m4is_qnjfv['allow_dupe'], $m4is_qnjfv['id'], $m4is_qnjfv['quantity'], $m4is_qnjfv['price'], $m4is_qnjfv['taxable'], $m4is_qnjfv['merchant_id'], $m4is__4en6o, $m4is_qnjfv['affiliate_id'], $m4is_qnjfv['delay_days']);
 if ($m4is_qnjfv['debug']) echo 'Subscription ID  = ', $m4is_d9ybqg, '<br>';
 if ( (int) $m4is_d9ybqg > 0) { $m4is_c4lk = self::$m4is_j_xo4w->recurringInvoice($m4is_d9ybqg);
 $m4is_oa_z = self::$m4is_j_xo4w->chargeInvoice($m4is_c4lk, _x('Memberium Subscription Purchase', 'memb_order_subscription', 'memberium'), $m4is__4en6o, $m4is_qnjfv['merchant_id'], false);
 if (! in_array($m4is_oa_z['Code'], ['Declined', 'Error']) ) { $m4is_v6fdv4 = $m4is_qnjfv['success_action'];
 $m4is_xf9b = $m4is_qnjfv['success_goal'];
 $m4is_mpia = $m4is_qnjfv['success_tag'];
 $m4is_imdo6 = $m4is_qnjfv['success_url'];
 } else { if (! $m4is_qnjfv['keep_failed']) { self::$m4is_j_xo4w->deleteSubscription($m4is_d9ybqg);
 } } } else { if (stripos($m4is_d9ybqg, 'Duplicate order') ) { if ($m4is_qnjfv['debug']) echo 'Duplicate Order Detected<br>';
 $m4is_v6fdv4 = $m4is_qnjfv['dupe_action'];
 $m4is_xf9b = $m4is_qnjfv['dupe_goal'];
 $m4is_mpia = $m4is_qnjfv['dupe_tag'];
 $m4is_imdo6 = $m4is_qnjfv['dupe_url'];
 } } } if (! empty($m4is_v6fdv4) ) { if ($m4is_qnjfv['debug']) echo 'Running Actionsets = ', $m4is_v6fdv4, '<br>';
 self::$m4is_bnd6ti->m4is_u86vzq($m4is_v6fdv4, $m4is_e2kg);
 } if (! empty($m4is_xf9b) ) { if ($m4is_qnjfv['debug']) echo 'Running Goals = ', $m4is_xf9b, '<br>';
 self::$m4is_bnd6ti->m4is_cqe6_($m4is_xf9b, $m4is_e2kg);
 } if (! empty($m4is_mpia) ) { if ($m4is_qnjfv['debug']) echo 'Adding/Removing Tags = ', $m4is_mpia, '<br>';
 self::$m4is_bnd6ti->m4is_tcle75($m4is_mpia, $m4is_e2kg);
 } if ($m4is_qnjfv['debug']) echo 'Syncing Contact = ', $m4is_mpia, '<br>';
 self::$m4is_bnd6ti->m4is_leu58($m4is_e2kg);
 if ($m4is_qnjfv['debug']) echo 'Redirect URL = ', $m4is_imdo6, '<br>';
 if ($m4is_qnjfv['debug']) return;
 if ($m4is_qnjfv['first_only'] && ! empty($m4is_imdo6) ) { echo '<script type="text/javascript"> window.location.replace("', $m4is_imdo6, '"); </script>';
 exit;
 } } static 
function m4is_ax0y($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_su4qk = 1;
 m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'autorun' => 0, 'button_text' => 'Buy Now', 'button_url' => '', 'clicked_button_text' => 'Processing Order', 'contact_id' => self::$m4is_e2kg, 'creditcard_id' => 0, 'css_class' => '', 'debug' => 0, 'delete_failed' => 1, 'failure_actionset' => 0, 'failure_goal' => '', 'failure_tag' => 0, 'failure_url' => '', 'lead_affiliate_id' => 0, 'nojs' => 0, 'order_title' => 'Memberium 1 Click Order', 'plan_id' => 0, 'process_specials' => true, 'product_ids' => '', 'promo_codes' => '', 'sale_affiliate_id' => 0, 'subscription_ids' => '', 'success_actionset' => 0, 'success_goal' => '', 'success_tag' => 0, 'success_url' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['nojs'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['nojs'], false);
 $m4is_qnjfv['debug'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['debug'], false);
 if ($m4is_qnjfv['contact_id'] < 1) { if ($m4is_qnjfv['debug']) { echo '<p style="font-weight:bold;color:red">No contact specified.</p>';
 } return '';
 } if ( empty( $m4is_qnjfv['product_ids']) ) { $m4is_ycbge = 0;
 } if ( empty( $m4is_qnjfv['product_ids'] ) && empty( $m4is_qnjfv['subscrption_ids'] ) ) { return;
 } if ($m4is_qnjfv['creditcard_id'] == 0) { $m4is_i3aq = m4is_akcfiz::m4is_ms5b($m4is_qnjfv['contact_id']);
 if (is_array($m4is_i3aq) && ! empty($m4is_i3aq)) { $m4is_l2waj = m4is_akcfiz::m4is_l9v0jb( $m4is_i3aq );
 $m4is_qnjfv['creditcard_id'] = $m4is_l2waj['Id'];
 } else { return '';
 } } if ( ! empty( $_COOKIE['infusionsoft_affiliate'] ) ) { $m4is_qnjfv['sale_affiliate_id'] = empty( $m4is_qnjfv['sale_affiliate_id'] ) ? (int) $_COOKIE['infusionsoft_affiliate'] : $m4is_qnjfv['sale_affiliate_id'];
 $m4is_qnjfv['lead_affiliate_id'] = empty( $m4is_qnjfv['lead_affiliate_id'] ) ? (int) $_COOKIE['infusionsoft_affiliate'] : $m4is_qnjfv['lead_affiliate_id'];
 } $m4is_ycbge = (int) $m4is_qnjfv['plan_id'];
 $m4is_qnjfv['process_specials'] = (boolean) $m4is_qnjfv['process_specials'];
 $m4is_qnjfv['product_ids'] = array_filter(array_map('trim', explode(',', $m4is_qnjfv['product_ids']) ) );
 $m4is_qnjfv['product_ids'] = array_filter(array_map('intval', $m4is_qnjfv['product_ids']) );
 $m4is_qnjfv['promo_codes'] = array_filter(array_map('trim', explode(',', $m4is_qnjfv['promo_codes']) ) );
 $m4is_qnjfv['subscription_ids'] = array_filter(array_map('trim', explode(',', $m4is_qnjfv['subscription_ids']) ) );
 $m4is_qnjfv['subscription_ids'] = array_filter(array_map('intval', $m4is_qnjfv['subscription_ids']) );
 $m4is_gqid = [ 'contact_id' => $m4is_qnjfv['contact_id'], 'creditcard_id' => $m4is_qnjfv['creditcard_id'], 'debug' => $m4is_qnjfv['debug'], 'delete_failed' => $m4is_qnjfv['delete_failed'], 'failure_actionset' => $m4is_qnjfv['failure_actionset'], 'failure_goal' => $m4is_qnjfv['failure_goal'], 'failure_tag' => $m4is_qnjfv['failure_tag'], 'failure_url' => $m4is_qnjfv['failure_url'], 'lead_affiliate_id' => $m4is_qnjfv['lead_affiliate_id'], 'order_title' => $m4is_qnjfv['order_title'], 'payplan_id' => $m4is_ycbge, 'process_specials' => $m4is_qnjfv['process_specials'], 'product_ids' => $m4is_qnjfv['product_ids'], 'promo_codes' => $m4is_qnjfv['promo_codes'], 'sale_affiliate_id' => $m4is_qnjfv['sale_affiliate_id'], 'subscription_ids' => $m4is_qnjfv['subscription_ids'], 'success_actionset' => $m4is_qnjfv['success_actionset'], 'success_goal' => $m4is_qnjfv['success_goal'], 'success_tag' => $m4is_qnjfv['success_tag'], 'success_url' => $m4is_qnjfv['success_url'], ];
 $m4is_gqid = base64_encode(serialize($m4is_gqid) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_gqid);
 $m4is_npof41 = 'memb_placeorder_form-' . $m4is_su4qk;
 $m4is__0dt14 = 'memb_placeorder_button_' . $m4is_su4qk;
  $m4is_tjg_9 = '';
 $m4is_tjg_9 .= "<form name='{$m4is_npof41}' id='{$m4is_npof41}' method='post'>";
 $m4is_tjg_9 .= "<input type='hidden' name='memb_form_type' value='memb_placeorder_button'>";
 $m4is_tjg_9 .= "<input type='hidden' name='params' value='{$m4is_gqid}'>";
 $m4is_tjg_9 .= "<input type='hidden' name='form_id' value='{$m4is_su4qk}'>";
 $m4is_tjg_9 .= "<input type='hidden' name='digital_signature' value='{$m4is_k1k7oj}'>";
 $m4is_tjg_9 .= wp_nonce_field('memb_placeorder_' . $m4is_su4qk, '_wpnonce', true, false);
 if (empty($m4is_qnjfv['button_url']) ) { $m4is_tjg_9 .= "<input type='submit' class='{$m4is_qnjfv['css_class']}' id='{$m4is__0dt14}' value='{$m4is_qnjfv['button_text']}'>";
 } else { $m4is_tjg_9 .= "<input type='image' src='{$m4is_qnjfv['button_url']}' class='{$m4is_qnjfv['css_class']}' id='{$m4is__0dt14}'>";
 } $m4is_tjg_9 .= "</form>";
 if (! $m4is_qnjfv['nojs']) { $m4is_tjg_9 .= "
			<script>
			jQuery(document).ready(function() {
				jQuery('#{$m4is__0dt14}').on('click', function() {
					jQuery('#{$m4is__0dt14}').prop('value', '{$m4is_qnjfv['clicked_button_text']}');
					jQuery('#{$m4is__0dt14}').attr('disabled', 'disabled');
					jQuery('#{$m4is_npof41}').submit();
					return true;
				});
			});
			</script>
			";
 } $m4is_su4qk++;
 return $m4is_tjg_9;
 } static 
function m4is_jtm6($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } if (is_feed() ) { return;
 }  $m4is_r6nh_b = [ 'field' => 'invoicetotal', 'order_id' => isset($_GET['orderId']) ? $_GET['orderId'] : 0, 'refresh' => false, ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['refresh'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['refresh'], false);
 $m4is_qnjfv['field'] = strtolower(trim($m4is_qnjfv['field']) );
  if (! $m4is_qnjfv['refresh']) { if (empty($m4is_qnjfv['order_id']) ) { return;
 } }  $m4is_onu8_4 = [ 'Contact0Email', 'inf_field_Email', ];
 foreach($m4is_onu8_4 as $m4is_yxwn) { if (empty($m4is_fliw) ) { $m4is_fliw = empty($_GET[$m4is_yxwn]) ? '' : $_GET[$m4is_yxwn];
 } } if (empty($m4is_fliw) ) { $m4is_fliw = isset($_SESSION['keap']['contact']['email']) ? $_SESSION['keap']['contact']['email'] : '';
 } if (empty($m4is_fliw) ) { return 0;
 } $m4is_e2kg = self::$m4is_bnd6ti->m4is_gz8a($m4is_fliw);
 if (empty($m4is_e2kg) ) { return 0;
 } if ($m4is_qnjfv['refresh']) { if (! $m4is_e2kg) { return;
 } } if ($m4is_qnjfv['refresh'] || ( self::$m4is_bnd6ti->m4is_g43l() < $m4is_qnjfv['order_id']) ) { m4is_untczd::m4is_ypsh6m();
 } if ($m4is_qnjfv['refresh']) { $m4is_qnjfv['order_id'] = self::$m4is_bnd6ti->m4is_lf3ds2($m4is_e2kg);
 } $m4is_craco = self::$m4is_bnd6ti->m4is_ow9yjk($m4is_e2kg);
 $m4is_kmtfz4 = [ 'invoicetotal' => 0, 'totaldue' => 0, 'totalpaid' => 0, ];
 if (is_array($m4is_craco) ) { foreach($m4is_craco as $m4is_etwy_q) { if ($m4is_etwy_q['JobId'] == $m4is_qnjfv['order_id']) { $m4is_kmtfz4['invoicetotal'] = $m4is_kmtfz4['invoicetotal'] + $m4is_etwy_q['InvoiceTotal'];
 $m4is_kmtfz4['totaldue'] = $m4is_kmtfz4['totaldue'] + $m4is_etwy_q['TotalDue'];
 $m4is_kmtfz4['totalpaid'] = $m4is_kmtfz4['totalpaid'] + $m4is_etwy_q['TotalPaid'];
 } } } return isset($m4is_kmtfz4[$m4is_qnjfv['field']]) ? $m4is_kmtfz4[$m4is_qnjfv['field']] : 0;
 } static 
function m4is_lt2q($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } if (! is_user_logged_in() ) { return;
 } if (is_feed() ) { return;
 } $m4is_fliw = m4is_wbc8os::m4is_sfnmc('email');
 $m4is_j485e = m4is_wbc8os::m4is_sfnmc('password');
 $m4is_r6nh_b = [ 'css_id' => '', 'height' => 720, 'mode' => 'url',  'width' => 540, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } if (empty($m4is_fliw) || empty($m4is_j485e) ) { return;
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['mode'] = strtolower(trim($m4is_qnjfv['mode']));
  $m4is_zq0k = self::$m4is_zq0k;
 $m4is_o9fyz = (int) $m4is_qnjfv['height'];
 $m4is_x4ma = (int) $m4is_qnjfv['width'];
 $m4is_fliw = urlencode($m4is_fliw);
 $m4is_j485e = urlencode($m4is_j485e);
 $m4is_uzfw8j = '';
 if ($m4is_qnjfv['mode'] == 'iframe') { $m4is_uzfw8j = '<iframe src="https://' . $m4is_zq0k . '.infusionsoft.com/ClientLogin/loginProcess.jsp?email=' . $m4is_fliw . '&amp;password=' . $m4is_j485e . '&amp;Login=Login" width="720" height="540" frameborder="0" scrolling="auto"></iframe>';
 } elseif ($m4is_qnjfv['mode'] == 'url') { $m4is_uzfw8j = 'https://' . $m4is_zq0k . '.infusionsoft.com/ClientLogin/loginProcess.jsp?email=' . $m4is_fliw . '&password=' . $m4is_j485e . '&Login=Login';
 } elseif ($m4is_qnjfv['mode'] == 'link') { $m4is_uzfw8j = '<a target="clientlogin" href="https://' . $m4is_zq0k . '.infusionsoft.com/ClientLogin/loginProcess.jsp?email=' . $m4is_fliw . '&password=' . $m4is_j485e . '&Login=Login">Click Me</a>';
 } elseif ($m4is_qnjfv['mode'] == 'redirect') { } return $m4is_uzfw8j;
 }    }

