<?php
/**
 * Copyright (c) 2017-2022 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists('m4is_pms8y') || die();
 m4is_a0qko::m4is_x6wv();
 final 
class m4is_a0qko { private static $m4is_bnd6ti, $m4is_e2kg, $m4is_bh12zy, $m4is_o3m_c5, $m4is_n3zlk;
 static 
function m4is_x6wv() { self::$m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 self::$m4is_e2kg = (int) self::$m4is_bnd6ti->m4is_dpuy9();
 self::$m4is_o3m_c5 = ! m4is_u68pu::m4is_u6mkaw();
 self::$m4is_bh12zy = m4is_w0enbm::m4is_e5l8a9();
 self::$m4is_n3zlk = 'memberium';
 } static 
function m4is_cayi( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'fields' => '', 'htmlattr' => '', 'separator' => ' ', 'txtfmt' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_h_iu0 = array_filter( explode( ',', trim( $m4is_qnjfv['fields'] ) ) );
 $m4is_a7dk0 = '';
 if ( empty( $m4is_h_iu0 ) ) { return '';
 } foreach ( $m4is_h_iu0 as $m4is_yxwn ) { $m4is_yxwn = strtolower( trim( $m4is_yxwn ) );
 $m4is_uzfw8j .= htmlspecialchars( m4is_wbc8os::m4is_u3dzkp( $m4is_yxwn ) );
 if ( count( $m4is_h_iu0 ) > 1 ) { $m4is_uzfw8j .= $m4is_qnjfv['separator'];
 } } return m4is_crqo::m4is__go6j( false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after'] );
 } static 
function m4is_mits_f( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } $m4is_r6nh_b = [ 'includepassword' => false, 'name' => 'membsession', 'omit' => '',  ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ', ', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_gltsw6 = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['includepassword'], false );
 $m4is_x5wxyr = array_filter( explode( ',', $m4is_qnjfv['omit'] ) );
 $m4is_dcf_7 = strtolower( self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'password_field' ) );
 $session = $_SESSION;
 if ( ! $m4is_gltsw6 ) { unset( $session['keap']['contact'][$m4is_dcf_7] );
 } foreach ( $m4is_x5wxyr as $m4is_g1ei) { unset( $session['memb_user'][$m4is_g1ei], $session['keap']['contact'][$m4is_g1ei], $session['keap']['affiliate'][$m4is_g1ei] );
 } $m4is_uzfw8j = '<script type="text/javascript">' . "\n";
 $m4is_uzfw8j .= 'var ' . $m4is_qnjfv['name'] . ' = ' . json_encode( $session, JSON_PRETTY_PRINT) . ";\n";
 $m4is_uzfw8j .= '</script>' . "\n";
 return $m4is_uzfw8j;
 } static 
function m4is_i8is( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_aocm8x = '';
 static $m4is_su4qk = 0;
 $m4is_su4qk++;
 $m4is_r6nh_b = [ 'actionset_id' => 0, 'buttontext' => 'Change Email', 'email1label' => 'Email Address:', 'email2label' => 'Repeat Email Address:', 'failure_url' => '', 'form_name' => 'change_email_' . $m4is_su4qk, 'goal' => '', 'success_url' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } $m4is_fliw = m4is_wbc8os::m4is_sfnmc( 'email' );
 $m4is_ig9p6 = (int) get_current_user_id();
 if ( empty( $m4is_fliw ) || empty( $m4is_ig9p6 ) || empty( self::$m4is_e2kg ) ) { return '';
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, 'memberium' );
 $m4is_zs6o = 'memb_email_change_' . $m4is_su4qk;
 $m4is_twsa = '';
 $m4is_rbwn1z = base64_encode( serialize( [ 'actionset_id' => $m4is_qnjfv['actionset_id'], 'goal' => $m4is_qnjfv['goal'], 'failure_url' => $m4is_qnjfv['failure_url'], 'success_url' => $m4is_qnjfv['success_url'], ]) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6( $m4is_rbwn1z );
 if ( ! empty( $_SESSION['memb_flash']['email_change_message'] ) ) { $m4is_twsa = $_SESSION['memb_flash']['email_change_message'];
 unset( $_SESSION['memb_flash']['email_change_message'], $_SESSION['memb_flash']['email_change_result'] );
 } $m4is_etj2 = new stdClass;
 $m4is_etj2->form_name = $m4is_qnjfv['form_name'];
 $m4is_etj2->nonce = wp_nonce_field( 'memb_email_change_' . $m4is_su4qk, '_wpnonce', true, false );
 $m4is_etj2->signature = self::$m4is_bnd6ti->m4is_nbmk6( $m4is_rbwn1z );
 $m4is_etj2->parameters = $m4is_rbwn1z;
 $m4is_etj2->form_id = $m4is_su4qk;
 $m4is_etj2->email = $m4is_fliw;
 $m4is_etj2->email1_label = $m4is_qnjfv['email1label'];
 $m4is_etj2->email2_label = $m4is_qnjfv['email2label'];
 $m4is_etj2->button_text = $m4is_qnjfv['buttontext'];
 $m4is_etj2->message = $m4is_twsa;
 return m4is_crqo::m4is_yu7b1r( $m4is_carw7y, $m4is_qnjfv, $m4is_z50f, $m4is_carw7y, $m4is_etj2 );
 }     static 
function m4is_qnpto($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_su4qk = 0;
 $m4is_su4qk++;
 $m4is_dcf_7 = self::$m4is_bnd6ti->m4is_oiewvu('settings', 'password_field');
 $m4is_jianh = ($m4is_dcf_7 == 'Password') ? 20 : 256;
 $m4is_r6nh_b = [ 'actionset_id' => 0, 'buttontext' => 'Change Password', 'confirm_template_id' => 0, 'goal' => '', 'maxlength' => $m4is_jianh, 'password1label' => 'New Password:', 'password2label' => 'Repeat Password:', 'redirect_url' => '',  'success_message' => _x('Password Changed Successfully.', 'memb_change_password', 'memberium'), 'success_url' => '', 'tagids' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if ( self::$m4is_bnd6ti->m4is_lvmz1b() || is_archive() || is_feed() || is_search() ) { return;
 } if (! self::$m4is_e2kg ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['maxlength'] = abs( intval( $m4is_qnjfv['maxlength'] ) );
 $m4is_rbwn1z = base64_encode(serialize([ 'confirm_template_id' => (int) trim($m4is_qnjfv['confirm_template_id']), 'goal' => trim($m4is_qnjfv['goal']), 'actionset_id' => trim($m4is_qnjfv['actionset_id']), 'redirect_url' => trim($m4is_qnjfv['redirect_url']), 'tagids' => trim($m4is_qnjfv['tagids']), 'successurl' => trim($m4is_qnjfv['success_url']), 'contact_id' => self::$m4is_e2kg, ] ) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is_npof41 = 'memb_password_change-' . $m4is_su4qk;
 $m4is_g5whlt = 'password_change_' . $m4is_su4qk;
 $m4is_tjg_9 = '';
 $m4is_mx6z7s = remove_query_arg(['passwordchange'], $_SERVER['REQUEST_URI']);
 $m4is_aj49 = self::$m4is_bh12zy->m4is_ix1iy();
 $m4is_etj2 = new stdClass;
 $m4is_etj2->form_name = $m4is_npof41;
 $m4is_etj2->form_action = $m4is_mx6z7s;
 $m4is_etj2->form_id = $m4is_su4qk;
 $m4is_etj2->nonce = wp_nonce_field($m4is_g5whlt. $m4is_rbwn1z, '_wpnonce', true, false);
;
 $m4is_etj2->parameters = $m4is_rbwn1z;
 $m4is_etj2->signature = $m4is_k1k7oj;
 $m4is_etj2->max_length = $m4is_qnjfv['maxlength'];
 $m4is_etj2->min_length = self::$m4is_bnd6ti->m4is_oiewvu('settings', 'min_password_length');
 $m4is_etj2->password1_label = $m4is_qnjfv['password1label'];
 $m4is_etj2->password2_label = $m4is_qnjfv['password2label'];
 $m4is_etj2->button_text = $m4is_qnjfv['buttontext'];
 $m4is_etj2->messages = '';
 if (! empty($m4is_aj49) ) { $m4is_etj2->messages = $m4is_aj49;
 self::$m4is_bh12zy->m4is_mhea('');
 } else { if (! empty($_GET['passwordchange']) && $_GET['passwordchange'] == 'success' ) { $m4is_etj2->messages = $m4is_qnjfv['success_message'];
 unset($_GET['passwordchange']);
 } } return m4is_crqo::m4is_yu7b1r($m4is_carw7y, $m4is_qnjfv, $m4is_z50f, $m4is_carw7y, $m4is_etj2);
 } static 
function m4is_x9vim1($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_su4qk = 1;
 $m4is_r6nh_b = [ 'buttontext' => 'Send Password', 'emailtext' => 'Email Address', 'successurl' => '',  'failureurl' => '',  'template_id' => 0, 'tag_id' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! empty( self::$m4is_bnd6ti->m4is_oiewvu('settings', 'local_auth_only') ) ) { if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '<p style="color:red;font-weight:bold;">Send Password Form disabled by secure password storage.</p>';
 } return;
 } if (is_user_logged_in() ){ if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '<p style="color:red;font-weight:bold;">Send Password Form not visible to logged in users.</p>';
 } return;
 } if (is_feed() ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_npof41 = 'memb_password_send-' . $m4is_su4qk;
 $m4is_tjg_9 = '';
 $m4is_qnjfv['template_id'] = (int) $m4is_qnjfv['template_id'];
 $m4is_qnjfv['tag_id'] = abs( intval( $m4is_qnjfv['tag_id'] ) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_qnjfv['template_id'] . $m4is_qnjfv['tag_id']);
 if (! empty( self::$m4is_bh12zy->m4is_ix1iy() ) ) { $m4is_tjg_9 .= '<div class="password_send_message">' . self::$m4is_bh12zy->m4is_ix1iy() . '</div>';
 } $m4is_tjg_9 .= "<form name=\"{$m4is_npof41}\" id=\"{$m4is_npof41}\" method=\"post\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"form_id\" value=\"{$m4is_su4qk}\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"template_id\" value=\"{$m4is_qnjfv['template_id']}\">";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"signature\" value=\"{$m4is_k1k7oj}\">";
 $m4is_tjg_9 .= '<input type="hidden" name="successurl" value="' . base64_encode($m4is_qnjfv['successurl']) . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="failureurl" value="' . base64_encode($m4is_qnjfv['failureurl']) . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="tag_id" value="' . base64_encode($m4is_qnjfv['tag_id']) . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="memb_form_type" value="memb_send_password">';
 $m4is_tjg_9 .= '<div id="' . $m4is_npof41 . '-block1">';
 $m4is_tjg_9 .= '<label id="' . $m4is_npof41 . '-email-label">' . $m4is_qnjfv['emailtext'] . ':</label>';
 $m4is_tjg_9 .= '<input id="' . $m4is_npof41 . '-email-input" name="email" type="email" required value="">';
 $m4is_tjg_9 .= '</div>';
 $m4is_tjg_9 .= '<div id="' . $m4is_npof41 . '-block2">';
 $m4is_tjg_9 .= '<input type="submit" value="' . $m4is_qnjfv['buttontext'] . '" name="submit">';
 $m4is_tjg_9 .= '</div>';
 $m4is_tjg_9 .= "</form>";
 self::$m4is_bh12zy->m4is_mhea('');
 $m4is_su4qk++;
 return $m4is_tjg_9;
 } static 
function m4is_w02w54($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_isu2kc = 1;
 $m4is_r6nh_b = [ 'date_fields' => '', 'failure_url' => '', 'form_id' => 'registration_form_' . $m4is_isu2kc, 'goal' => '', 'pass_fields' => true, 'pass_password' => false, 'remove_accents' => 'y', 'required_fields' => '', 'success_url' => '', 'tagids' => '',  ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (empty( self::$m4is_e2kg ) ) { return;
 } m4is_aoxw::m4is_djr4nd();
        $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_sfcd = base64_encode(serialize([ 'contact_id' => self::$m4is_e2kg, 'date_fields' => $m4is_qnjfv['date_fields'], 'failure_url' => $m4is_qnjfv['failure_url'], 'form_id' => $m4is_qnjfv['form_id'], 'goal' => $m4is_qnjfv['goal'], 'pass_fields' => $m4is_qnjfv['pass_fields'], 'pass_password' => $m4is_qnjfv['pass_password'], 'remove_accents' => $m4is_qnjfv['remove_accents'], 'required_fields' => $m4is_qnjfv['required_fields'], 'success_url' => $m4is_qnjfv['success_url'], 'tagids' => $m4is_qnjfv['tagids'],  ]) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_sfcd);
 $m4is_tjg_9 = '';
 if (isset($_SESSION['error_message']) && is_array($_SESSION['error_message']) ) { foreach ($_SESSION['error_message'] as $m4is_aocm8x) { $m4is_tjg_9 .= '<p class="memb_registration_error"> ' . $m4is_aocm8x . '</p>';
 } unset($_SESSION['error_message']);
 } $m4is_tjg_9 .= '<form method="post" action="" id="' . $m4is_qnjfv['form_id'] . '" name="">';
 $m4is_tjg_9 .= wp_nonce_field($m4is_sfcd, '_wpnonce', true, false);
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"memb_form_type\" value=\"memb_update_contact_form\">";
 $m4is_tjg_9 .= '<input type="hidden" name="params" value="' . $m4is_sfcd . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="signature" value="' . $m4is_k1k7oj . '">';
 $m4is_tjg_9 .= do_shortcode($m4is_z50f);
 $m4is_tjg_9 .= '</form>';
 $m4is_isu2kc++;
 return $m4is_tjg_9;
 }  static 
function m4is_i5_0p($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'cache' => HOUR_IN_SECONDS, 'capture' => '', 'mode' => 'text', 'htmlattr' => '', 'txtfmt' => '', ];
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_uzfw8j = '';
 if (isset($_SESSION['memb_user']['email']) ) { $m4is_zg8z = self::$m4is_bh12zy->m4is_x3yw9r($_SESSION['memb_user']['email']);
 if ($m4is_qnjfv['mode'] == 'text') { switch ($m4is_zg8z) { case 1: $m4is_uzfw8j = _x('Single Opted In', 'memb_optin_status', 'memberium');
 break;
 case 2: $m4is_uzfw8j = _x('Double Opted In', 'memb_optin_status', 'memberium');
 break;
 default: $m4is_uzfw8j = _x('Not Opted In', 'memb_optin_status', 'memberium');
 break;
 } } else { $m4is_uzfw8j = $m4is_zg8z;
 } } return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_tqz7($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'capture' => '', 'contact_id' => self::$m4is_e2kg, 'date_format' => '', 'default' => '', 'fields' => '', 'htmlattr' => '', 'owner_id' => 0, 'separator' => ' ', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['fields'] = trim($m4is_qnjfv['fields']);
 $m4is_qnjfv['contact_id'] = (int) $m4is_qnjfv['contact_id'];
 $m4is_qnjfv['fields'] = array_filter(explode(',', $m4is_qnjfv['fields']) );
 if (empty($m4is_qnjfv['fields']) ) { return;
 }  if ($m4is_qnjfv['owner_id'] > 0) { $m4is_qnjfv['owner_id'] = (int) $m4is_qnjfv['owner_id'];
 } else { if ($m4is_qnjfv['contact_id'] <> self::$m4is_e2kg ) { $m4is_ereh = m4is_bnrdbo::m4is_yvnol($m4is_qnjfv['contact_id'], true);
 $m4is_qnjfv['owner_id'] = (int) $m4is_ereh['ownerid'];
 unset($m4is_ereh);
 } else { $m4is_qnjfv['owner_id'] = (int) m4is_wbc8os::m4is_sfnmc('ownerid', 0);
 } } $m4is_bspnm = m4is_dcig::m4is_ixm7_( $m4is_qnjfv['owner_id'], true );
 $m4is_h_iu0 = $m4is_qnjfv['fields'];
 $m4is_l436 = count($m4is_h_iu0);
 $m4is_i7j9_a = 0;
 $m4is_glto1 = 0;
 $m4is_uzfw8j = '';
 foreach($m4is_qnjfv['fields'] as $m4is_yxwn) { $m4is_glto1++;
 $m4is_yxwn = strtolower(trim($m4is_yxwn) );
 if (isset($m4is_bspnm[$m4is_yxwn]) ) { $m4is_mb6gy = strtotime($m4is_bspnm[$m4is_yxwn]);
 if ($m4is_qnjfv['date_format'] == '' || $m4is_mb6gy == 0) { $m4is_n6yjk9 = $m4is_bspnm[$m4is_yxwn];
 } else { $m4is_n6yjk9 = date($m4is_qnjfv['date_format'], strtotime($m4is_bspnm[$m4is_yxwn]) );
 } } else { $m4is_n6yjk9 = $m4is_qnjfv['default'];
 } $m4is_uzfw8j .= $m4is_n6yjk9;
 if ($m4is_glto1 < $m4is_l436) { $m4is_uzfw8j .= $m4is_qnjfv['separator'];
 } } return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr']);
 } static 
function m4is_oehku($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } if (is_feed() ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'actionset_id' => '', 'contact_id' => self::$m4is_e2kg, 'date_format' => '', 'fields' => '', 'goal' => '', 'tag_id' => '', 'txtfmt' => '', 'value' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['contact_id'] = (int) $m4is_qnjfv['contact_id'];
 $m4is_qnjfv['fields'] = array_filter(explode(',', $m4is_qnjfv['fields']) );
 $m4is_qnjfv['value'] = m4is_crqo::m4is_mq57($m4is_qnjfv['value'], $m4is_qnjfv['txtfmt']);
 if (empty($m4is_qnjfv['contact_id']) ) { return;
 } if (empty($m4is_qnjfv['fields']) ) { return;
 } if ($m4is_qnjfv['date_format'] > '') { if (strcasecmp($m4is_qnjfv['date_format'] , 'infusionsoft') == 0) { $m4is_qnjfv['date_format'] = 'Ymd\Th:i:s';
 } $m4is_qnjfv['value'] = date($m4is_qnjfv['date_format'], strtotime($m4is_qnjfv['value']) );
 } $m4is_qnjfv['value'] = trim($m4is_qnjfv['value']);
 $m4is_dbcyjz = m4is_ho3l::m4is_kjedy2('Contact');
 $m4is_yl3vb = [ 'CreatedBy', 'DateCreated', 'Groups', 'Id', 'LastUpdated', 'LastUpdatedBy', 'Validated', ];
  if (is_array($m4is_dbcyjz) ) { foreach ($m4is_dbcyjz as $valid_field) { $m4is_qnjfv['fields'] = str_ireplace($valid_field, $valid_field, $m4is_qnjfv['fields']);
 } } foreach ($m4is_qnjfv['fields'] as $m4is_s2ge5 => $m4is_g1ru50) { if (! in_array($m4is_g1ru50, $m4is_dbcyjz) || in_array($m4is_g1ru50, $m4is_yl3vb) ) { unset($m4is_qnjfv['fields'][$m4is_s2ge5]);
 } else { self::$m4is_bnd6ti->m4is_wzxl_1($m4is_g1ru50, $m4is_qnjfv['value'], $m4is_qnjfv['contact_id']);
 } } if ($m4is_qnjfv['contact_id'] == self::$m4is_e2kg ) { $_SESSION = self::$m4is_bnd6ti->m4is_akz3();
 } } static 
function m4is_lf_cgq( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_isu2kc = 1;
 if ( is_feed() ) { return '';
 } $m4is_r6nh_b = [ 'action_id' => '', 'autologin' => false, 'date_fields' => '', 'encoded' => true, 'failure_url' => '', 'form_id' => '', 'goal' => '', 'inf_fields' => false, 'membership_tags' => '',  'pass_fields' => false, 'pass_password' => false, 'recaptcha' => false, 'remove_accents' => 'n', 'required_fields' => 'FirstName,Email', 'secure' => true, 'success_url' => '', 'tagids' => '', 'unfriendly' => false, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } if ( is_user_logged_in() ) { if ( is_super_admin() ) { if ( empty( $m4is_z50f ) ) { return '<p style="color:red;"><strong>ERROR:</strong> No Form Specified</pre>';
 } if ( stripos( $m4is_z50f, '<input' ) === false || stripos( $m4is_z50f, 'FirstName' ) === false || stripos( $m4is_z50f, 'Email' ) === false ) { return '<p style="color:red;"><strong>ERROR:</strong>  Your form must include both the <strong>FirstName</strong>, and <strong>Email</strong> input fields in order to register a new contact.</p>';
 } return '<p style="color:red;"><strong>NOTE:</strong>  The registration form is only displayed when not logged in.</p>';
 } return '';
 } m4is_aoxw::m4is_djr4nd();
     $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, 'memberium' );
 $m4is_qnjfv['autologin'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['autologin'], false );
 $m4is_qnjfv['encoded'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['encoded'], false );
 $m4is_qnjfv['inf_fields'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['inf_fields'], false );
 $m4is_qnjfv['pass_fields'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['pass_fields'], false );
 $m4is_qnjfv['pass_password'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['pass_password'], false );
 $m4is_qnjfv['recaptcha'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['recaptcha'], false );
 $m4is_qnjfv['secure'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['secure'], false );
 $m4is_qnjfv['unfriendly'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['hostile'], false );
  if ( $m4is_qnjfv['recaptcha'] ) { $m4is_qnjfv['recaptcha_v2_secret_key'] = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'recaptcha_v2_secret_key', '' );
 $m4is_qnjfv['recaptcha_v2_site_key'] = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'recaptcha_v2_site_key', '' );
 if ( empty( $m4is_qnjfv['recaptcha_v2_secret_key'] ) || empty( $m4is_qnjfv['recaptcha_v2_site_key'] ) ) { $m4is_qnjfv['recaptcha'] = false;
 $m4is_qnjfv['recaptcha_v2_secret_key'] = '';
 $m4is_qnjfv['recaptcha_v2_site_key'] = '';
 } } if ( empty( trim( $m4is_qnjfv['form_id'] ) ) ) { $m4is_qnjfv['form_id'] = 'registration_form_' . $m4is_isu2kc;
 } $m4is_sfcd = base64_encode( serialize( [ 'action_id' => $m4is_qnjfv['action_id'], 'autologin' => $m4is_qnjfv['autologin'], 'date_fields' => $m4is_qnjfv['date_fields'], 'failure_url' => $m4is_qnjfv['failure_url'], 'form_id' => $m4is_qnjfv['form_id'], 'goal' => $m4is_qnjfv['goal'], 'membership_tags' => $m4is_qnjfv['membership_tags'], 'pass_fields' => $m4is_qnjfv['pass_fields'], 'pass_password' => $m4is_qnjfv['pass_password'], 'recaptcha' => $m4is_qnjfv['recaptcha'], 'remove_accents' => $m4is_qnjfv['remove_accents'], 'required_fields' => $m4is_qnjfv['required_fields'], 'success_url' => $m4is_qnjfv['success_url'], 'tagids' => $m4is_qnjfv['tagids'], 'unfriendly' => $m4is_qnjfv['unfriendly'], ] ) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6( $m4is_sfcd );
 $m4is_tjg_9 = '';
 if ( ! empty( $_SESSION['error_message'] ) ) { foreach ( $_SESSION['error_message'] as $m4is_aocm8x ) { $m4is_tjg_9 .= '<p class="memb_registration_error"> ' . $m4is_aocm8x . '</p>';
 } } $m4is_etj2 = new stdClass;
 $m4is_etj2->recaptcha_html = $m4is_qnjfv['recaptcha'] ? '<div class="g-recaptcha" data-sitekey="' . $m4is_qnjfv['recaptcha_v2_site_key'] . '"></div>' : '';
 if ( $m4is_qnjfv['recaptcha'] ) { wp_enqueue_script( 'google-recaptcha', 'https://www.google.com/recaptcha/api.js', [], null, true );
 } $m4is_tjg_9 .= '<form method="post" action="" id="' . $m4is_qnjfv['form_id'] . '" name="">' . "\n";
 $m4is_tjg_9 .= "<input type=\"hidden\" name=\"memb_form_type\" value=\"memb_registration\">" . "\n";
 $m4is_tjg_9 .= wp_nonce_field( $m4is_sfcd, '_wpnonce', true, false ) . "\n";
 $m4is_tjg_9 .= '<input type="hidden" name="params" value="' . $m4is_sfcd . '">' . "\n";
 $m4is_tjg_9 .= '<input type="hidden" name="signature" value="' . $m4is_k1k7oj . '">' . "\n";
 $m4is_tjg_9 .= $m4is_etj2->recaptcha_html . "\n";
 $m4is_tjg_9 .= do_shortcode( $m4is_z50f ) . "\n";
 $m4is_tjg_9 .= '</form>' . "\n\n";
 $m4is_tjg_9 = do_shortcode( $m4is_tjg_9 );
 if ( $m4is_qnjfv['encoded'] || $m4is_qnjfv['secure'] ) { $m4is_tjg_9 = m4is_crqo::m4is_sb62m9( $m4is_tjg_9 );
 } $m4is_isu2kc++;
 $_SESSION['error_message'] = null;
 return $m4is_tjg_9;
 } static 
function m4is_mi3n1y($m4is_qnjfv, $m4is_z50f = NULL, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'default' => '', 'fieldname' => '', 'htmlattr' => '', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 if (empty($m4is_qnjfv['fieldname']) ) { return;
 } $m4is_x0_hk = wp_get_current_user();
 $m4is_yxwn = $m4is_qnjfv['fieldname'];
 $m4is_uzfw8j = $m4is_x0_hk->$m4is_yxwn;
 $m4is_uzfw8j = empty($m4is_x0_hk->$m4is_yxwn) ? $m4is_qnjfv['default'] : $m4is_x0_hk->$m4is_yxwn;
 return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_l5mo($m4is_qnjfv, $m4is_z50f = NULL, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_su4qk = 0;
 m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'send_button_text' => 'Reset Password', 'template_id' => 0, 'update_button_text' => 'Update Password', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 }   if (is_user_logged_in() ) { return;
 } if (is_feed() ) { return;
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['template_id'] = (int) $m4is_qnjfv['template_id'];
 $m4is_su4qk = $m4is_su4qk + 1;
 $m4is_tjg_9 = '';
 if (isset($_GET['action']) && isset($_GET['key']) && isset($_GET['login']) ) { $m4is_x0_hk = check_password_reset_key($_GET['key'], $_GET['login']);
 if ('WP_User' == get_class($m4is_x0_hk) ) { $m4is_tjg_9 .= '<form method="post" action="./">';
 $m4is_tjg_9 .= wp_nonce_field('memb_reset_password_' . $m4is_su4qk, '_wpnonce', true, false);
 $m4is_tjg_9 .= '<input type="hidden" name="form_id" value="' . $m4is_su4qk . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="memb_form_type" value="memb_reset_password">';
 $m4is_tjg_9 .= '<input type="hidden" name="key" value="' . $_GET['key'] . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="login" value="' . $_GET['login'] . '">';
 $m4is_tjg_9 .= '<label>Enter Your New Password:</label><input type="password" name="password1" placeholder="New Password" size="30"><br />';
 $m4is_tjg_9 .= '<label>Confirm Your New Password:</label><input type="password" name="password2" placeholder="New Password" size="30"><br />';
 $m4is_tjg_9 .= '<input type="submit" value="' . $m4is_qnjfv['update_button_text'] . '">';
 $m4is_tjg_9 .= '</form>';
 } else { $m4is_tjg_9 .= '<p>Invalid / Expired Link</p>';
 } } else { $m4is_gqid = base64_encode(serialize(['template_id' => $m4is_qnjfv['template_id'] ]) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_gqid);
 $m4is_tjg_9 .= '<form method="post">';
 $m4is_tjg_9 .= wp_nonce_field('memb_reset_password_' . $m4is_su4qk, '_wpnonce', true, false);
 $m4is_tjg_9 .= '<input type="hidden" name="form_id" value="' . $m4is_su4qk . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="memb_form_type" value="memb_reset_password">';
 $m4is_tjg_9 .= '<input type="hidden" name="params" value="' . $m4is_gqid . '">';
 $m4is_tjg_9 .= '<input type="hidden" name="signature" value="' . $m4is_k1k7oj . '">';
 $m4is_tjg_9 .= '<label>Your Login Email:</label><input type="email" name="email" placeholder="Your Email Address" size="30"><br />';
 $m4is_tjg_9 .= '<input type="submit" value="' . $m4is_qnjfv['send_button_text'] . '">';
 $m4is_tjg_9 .= '</form>';
 } return $m4is_tjg_9;
 } static 
function m4is_bm16ek($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'alt' => '', 'capture' => '', 'class' => 'memberium-gravatar', 'default' => '', 'email' => m4is_wbc8os::m4is_sfnmc('email'), 'rating' => 'g', 'size' => 32, 'title' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['size'] = ( (int) $m4is_qnjfv['size'] < 1) ? 32 : (int) $m4is_qnjfv['size'];
 if ($m4is_qnjfv['size'] > 2048) { $m4is_qnjfv['size'] = 2048;
 } if (empty($m4is_qnjfv['email']) && is_user_logged_in() ) { $m4is_x0_hk = wp_get_current_user();
 $m4is_qnjfv['email'] = $m4is_x0_hk->user_email;
 } $m4is_qnjfv['email'] = strtolower(trim($m4is_qnjfv['email']) );
 $m4is_n0f5mx = '//www.gravatar.com/avatar/' . md5($m4is_qnjfv['email']) . '.jpg?s=' . (int) $m4is_qnjfv['size'];
 $m4is_n0f5mx .= ($m4is_qnjfv['default'] > '') ? '&d=' . urlencode($m4is_qnjfv['default']) : '';
 $m4is_n0f5mx .= ($m4is_qnjfv['rating'] > '') ? '&r=' . urlencode($m4is_qnjfv['rating']) : '';
 $m4is_z50f = '<img src="' . $m4is_n0f5mx . '" border="0" alt="' . esc_attr($m4is_qnjfv['alt']) . '" title="' . esc_attr($m4is_qnjfv['title']). '" height="' . esc_attr($m4is_qnjfv['size']) . '" width="' . esc_attr($m4is_qnjfv['size']) . '" class="' . $m4is_qnjfv['class'] . '"/>';
 return m4is_crqo::m4is__go6j(false, $m4is_z50f, '', $m4is_qnjfv['capture'], '', '', '');
 } static 
function m4is_ddup($m4is_qnjfv, $m4is_z50f = NULL, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'htmlattr' => '', 'name' => false, 'op' => 'show', 'txtfmt' => '', 'val' => 0, ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['name'] = strtolower(trim($m4is_qnjfv['name']) );
 if (empty($m4is_qnjfv['name']) ) { return;
 } $m4is_ig9p6 = get_current_user_id();
;
 if (! $m4is_ig9p6) { return;
 }  $m4is_uzfw8j = '';
 $m4is_glto1 = (int) self::$m4is_bh12zy->m4is_kxc1($m4is_qnjfv['name']);
 switch (strtolower($m4is_qnjfv['op']) ) { case 'decr': if ( (int) $m4is_qnjfv['val'] == 0) { $m4is_qnjfv['val'] = 1;
 } $m4is_glto1 = $m4is_glto1 - (int) $m4is_qnjfv['val'];
 break;
 case 'incr': if ( (int) $m4is_qnjfv['val'] == 0) { $m4is_qnjfv['val'] = 1;
 } $m4is_glto1 = $m4is_glto1 + (int) $m4is_qnjfv['val'];
 break;
 case 'set': $m4is_glto1 = (int) $m4is_qnjfv['val'];
 break;
 case 'show': case 'get': $m4is_uzfw8j = $m4is_glto1;
 break;
 } self::$m4is_bh12zy->m4is_qwkq($m4is_qnjfv['name'], $m4is_glto1);
 return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_nen10($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'after' => '', 'alt' => 'No membership levels found.', 'before' => '', 'capture' => '', 'format' => '<li>%%membershipname%% (%%tagid%%)</li>', 'htmlattr' => '', 'txtfmt' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_mdqgk = isset($_SESSION) ? $_SESSION : [];
 if (! empty($m4is_mdqgk['memb_user']['membership_tags']) ) { $m4is_at4xqr = explode(',', $m4is_mdqgk['memb_user']['membership_tags']);
 $m4is_uzfw8j = '';
 $m4is_iystd2 = m4is_pwtg7::m4is_i0au6j();
 $m4is_qh8p6 = self::$m4is_bnd6ti->m4is_oiewvu( 'memberships' );
 foreach ($m4is_at4xqr as $m4is_x84r) { $m4is_uzfw8j .= str_ireplace('%%tagid%%', $m4is_x84r, $m4is_qnjfv['format']);
 $m4is_uzfw8j = str_ireplace('%%tagname%%', $m4is_iystd2['mc'][$m4is_x84r], $m4is_uzfw8j);
 $m4is_uzfw8j = str_ireplace('%%membershiplevel%%', $m4is_qh8p6[$m4is_x84r]['level'], $m4is_uzfw8j);
 $m4is_uzfw8j = str_ireplace('%%membershipname%%', $m4is_qh8p6[$m4is_x84r]['name'], $m4is_uzfw8j);
 } } else { $m4is_uzfw8j = $m4is_qnjfv['alt'];
 } return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_i7hm($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'mode' => 'plain', 'style' => 'color:#000;', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is__9814c = m4is_bea_0::m4is_f5sc();
 if ($m4is__9814c) { $m4is__w09i = add_query_arg('rss_user', $m4is__9814c, get_feed_link() );
 } else { $m4is__w09i = get_feed_link();
 } if ($m4is_qnjfv['mode'] == 'input') { $m4is_tiq5k6 = strlen($m4is__w09i);
 $m4is__w09i = '<input class="memberium_feed_url" style="' . $m4is_qnjfv['style'] . '" value="' . $m4is__w09i . '" disabled="disabled" size="' . $m4is_tiq5k6 * 0.9 . '">';
 } elseif ($m4is_qnjfv['mode'] == 'key') { $m4is__w09i = $m4is__9814c;
 } return $m4is__w09i;
 } static 
function m4is_h6adyc($m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '') { if ( self::$m4is_o3m_c5 ) { return '';
 } if (is_feed() ) { return;
 } m4is_aoxw::m4is_djr4nd();
 static $m4is_su4qk = 0;
 $m4is_r6nh_b = [ 'css_class' => '', 'style' => '', 'button_text' => 'Get New RSS URL', 'button_url' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $m4is_su4qk++;
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_npof41 = 'memb_resetfeedurl_button-' . $m4is_su4qk;
 $m4is__0dt14 = 'memb_resetfeedurl_button_' . $m4is_su4qk;
 $m4is_tjg_9 = '<form method="post" action="">';
 $m4is_tjg_9 .= "<input type='hidden' name='memb_form_type' value='memb_resetfeedurl_button'>";
 $m4is_tjg_9 .= "<input type='hidden' name='form_id' value='{$m4is_su4qk}'>";
 $m4is_tjg_9 .= wp_nonce_field("memb_resetfeedurl_{$m4is_su4qk}", '_wpnonce', true, false);
 if (empty($m4is_qnjfv['button_url']) ) { $m4is_tjg_9 .= "<input type=\"submit\" class=\"{$m4is_qnjfv['css_class']}\" id=\"{$m4is__0dt14}\" value=\"{$m4is_qnjfv['button_text']}\">";
 } else { $m4is_tjg_9 .= "<input type=\"image\" src=\"{$m4is_qnjfv['button_url']}\" class=\"{$m4is_qnjfv['css_class']}\" id=\"{$m4is__0dt14}\" >";
 } $m4is_tjg_9 .= '</form>';
 return $m4is_tjg_9;
 } static 
function m4is_mdqf6( $m4is_qnjfv = [], string $m4is_z50f = '', string $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return '';
 }  $m4is_r6nh_b = [ 'after' => '', 'before' => '', 'capture' => '', 'contact_id' => self::$m4is_e2kg, 'date_format' => '', 'default' => '', 'fields' => '', 'field_filter' => '', 'htmlattr' => '', 'separator' => ' ', 'txtfmt' => '', ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, 'memberium' );
 $m4is_e2kg = (int) $m4is_qnjfv['contact_id'];
  if ( empty( $m4is_qnjfv['fields'] ) ) { return;
 } m4is_aoxw::m4is_djr4nd();
 if ($m4is_e2kg <> self::$m4is_e2kg ) { $m4is_ereh = m4is_bnrdbo::m4is_yvnol( $m4is_e2kg, true );
 } else { $m4is_ereh = isset($_SESSION['keap']['contact']) ? $_SESSION['keap']['contact'] : [];
 } $m4is_h_iu0 = array_filter( explode( ',', $m4is_qnjfv['fields'] ) );
 $m4is_l436 = count( $m4is_h_iu0 );
 $m4is_i7j9_a = 0;
 $m4is_uzfw8j = '';
 $m4is_zts3 = $m4is_e2kg ? false : is_super_admin();
  foreach ( $m4is_h_iu0 as $m4is_yxwn ) { if ( $m4is_zts3 ) { $m4is_wuh95 = 'Admin';
 } else { $m4is_yxwn = strtolower( trim( $m4is_yxwn ) );
 if ( isset( $m4is_ereh[$m4is_yxwn] ) ) { $m4is_mb6gy = strtotime( $m4is_ereh[$m4is_yxwn] );
 if ( $m4is_qnjfv['date_format'] == '' || $m4is_mb6gy == 0 ) { $m4is_wuh95 = isset( $m4is_ereh[$m4is_yxwn] ) ? htmlspecialchars( $m4is_ereh[$m4is_yxwn] ) : '';
 } else { $m4is_wuh95 = date( $m4is_qnjfv['date_format'], $m4is_mb6gy );
 } } else { $m4is_wuh95 = $m4is_qnjfv['default'];
 } } if ( $m4is_qnjfv['field_filter'] ) { $m4is_wuh95 = apply_filters( "memberium/shortcodes/memb_contact/{$m4is_qnjfv['field_filter']}", $m4is_wuh95, $m4is_yxwn );
 } $m4is_uzfw8j .= $m4is_wuh95;
 if ($m4is_l436 > 1) { $m4is_uzfw8j .= $m4is_qnjfv['separator'];
 } } if ( $m4is_l436 > 1 && strlen( $m4is_qnjfv['separator'] ) > 0 ) { $m4is_uzfw8j = substr( $m4is_uzfw8j, 0, -strlen( $m4is_qnjfv['separator'] ) );
 } return m4is_crqo::m4is__go6j(false, $m4is_uzfw8j, $m4is_qnjfv['txtfmt'], $m4is_qnjfv['capture'], $m4is_qnjfv['htmlattr'], $m4is_qnjfv['before'], $m4is_qnjfv['after']);
 } static 
function m4is_x4o8n( $m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return '';
 } global $wpdb;
 $m4is_r6nh_b = [ 'count' => 10, 'date_format' => 'F d, Y', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if (! is_user_logged_in() ) { return;
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['count'] = empty($m4is_qnjfv['count']) ? 10 : (int) $m4is_qnjfv['count'];
 $m4is_x0_hk = wp_get_current_user();
 $m4is_gai6k = $m4is_x0_hk->user_login;
 $m4is_zq0k = self::$m4is_bnd6ti->m4is_d14zr('appname');
 $m4is_uzfw8j = '';
 if (empty($m4is_z50f) ) { $m4is_z50f = '%%logintime%% - %%ipaddress%%<br />';
 } $m4is_tovizk = "SELECT `logintime`, `ipaddress` FROM `" . m4is_ypvg9::m4is_hjqcz2() . "` WHERE `username` = '{$m4is_gai6k}' AND `appname` = '{$m4is_zq0k}' ORDER BY `logintime` DESC ";
 if ($m4is_qnjfv['count']) { $m4is_tovizk .= ' LIMIT '. $m4is_qnjfv['count'];
 } $m4is_hpn9y = $wpdb->get_results($m4is_tovizk, ARRAY_A);
 if (is_array($m4is_hpn9y) ) { foreach($m4is_hpn9y as $m4is_ke_fr) { $m4is_pv4alu = $m4is_z50f;
 $m4is_pv4alu = str_ireplace('%%logintime%%', date($m4is_qnjfv['date_format'], $m4is_ke_fr['logintime']), $m4is_pv4alu);
 $m4is_pv4alu = str_ireplace('%%ipaddress%%', $m4is_ke_fr['ipaddress'], $m4is_pv4alu);
 $m4is_uzfw8j .= $m4is_pv4alu;
 } } m4is_aoxw::m4is_djr4nd();
 return $m4is_uzfw8j;
 } static 
function m4is_m9pxk( $m4is_qnjfv = [], $m4is_z50f = null, $m4is_carw7y = '' ) : string { if ( self::$m4is_o3m_c5 ) { return '';
 } if ( is_feed() ) { return '';
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'count' => 10, 'id' => '', 'offset' => 0, 'order_by' => 'display_name', 'order_by' => 'memb_email', 'order' => 'ASC', 'roles' => 'subscriber', 'tag_id' => '', ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, 'memberium' );
 $m4is_uzfw8j = '';
 $m4is_qnjfv['order'] = strtoupper( trim( $m4is_qnjfv['order'] ) );
 $m4is_qnjfv['order_by'] = strtolower( trim( $m4is_qnjfv['order_by'] ) );
 if ( empty( $m4is_z50f ) ) { } $m4is_qnjfv['roles'] = trim( $m4is_qnjfv['roles'] );
 if ( ! empty( $m4is_qnjfv['roles'] ) ) { $m4is_qnjfv['roles'] = explode( ',', $m4is_qnjfv['roles'] );
 $m4is_qnjfv['roles'] = array_map( 'trim', $m4is_qnjfv['roles'] );
 $m4is_qnjfv['roles'] = array_map( 'strtolower', $m4is_qnjfv['roles'] );
 $m4is_qnjfv['roles'] = array_filter( $m4is_qnjfv['roles'] );
 } else { $m4is_qnjfv['roles'] = [];
 } $m4is_iystd2 = trim( $m4is_qnjfv['tag_id'] );
 if ( ! empty( $m4is_iystd2 ) ) { $m4is_iystd2 = explode( ',', $m4is_iystd2 );
 $m4is_iystd2 = array_map( 'trim', $m4is_iystd2 );
 $m4is_iystd2 = array_map( 'strtolower', $m4is_iystd2 );
 $m4is_iystd2 = array_filter( $m4is_iystd2 );
 $m4is_da5n = implode( '|', $m4is_iystd2 );
 } else { $m4is_da5n = '';
 }  $m4is_xgyid = [ [ [ 'key' => 'memb_Groups', 'compare' => 'REGEXP', 'value' => "[^0-9]*({$m4is_da5n})[^0-9]*",  ], ], ];
 if ( ! empty( $m4is_qnjfv['id'] ) ) { $m4is_xgyid[] = [ 'key' => 'infusionsoft_user_id', 'compare' => '=', 'value' => empty( $m4is_qnjfv['id'] ) ? 0 : $m4is_qnjfv['id'], ];
 } else { $m4is_xgyid[] = [ 'key' => 'infusionsoft_user_id', 'compare' => '>', 'value' => 0, ];
 } $m4is_k4yeul = [ 'fields' => 'all', 'meta_key' => $m4is_qnjfv['order_by'], 'meta_query' => $m4is_xgyid, 'order' => $m4is_qnjfv['order'], 'orderby' => 'meta_value', 'orderby' => $m4is_qnjfv['order_by'], 'number' => (int) $m4is_qnjfv['count'], 'offset' => (int) $m4is_qnjfv['offset'], ];
 if ( ! empty( $m4is_qnjfv['roles'] ) ) { $m4is_k4yeul['role__in'] = $m4is_qnjfv['roles'];
 } $m4is_jfds = get_users( $m4is_k4yeul );
 $m4is_wfczrg = count( $m4is_jfds );
 $m4is_h358 = [];
 foreach($m4is_jfds as $m4is_j5sy07 => $m4is_x0_hk) { $m4is_ig9p6 = $m4is_x0_hk->data->ID;
 $m4is_e2kg = $m4is_x0_hk->infusionsoft_user_id;
 $m4is_h358[$m4is_j5sy07] = $m4is_x0_hk;
 $m4is_h358[$m4is_j5sy07]->contact_fields = m4is_bnrdbo::m4is_yvnol($m4is_e2kg, true);
 } $m4is_jfds = $m4is_h358;
 $m4is_ubvq = false !== stripos( $m4is_z50f, '%%contact.' );
 $m4is_xg78yx = false !== stripos( $m4is_z50f, '%%role.' );
 $m4is_fzyu3t = false !== stripos( $m4is_z50f, '%%user.' );
 $m4is_l9cr = false !== stripos( $m4is_z50f, '%%meta.' );
 $m4is_nfvr = false !== stripos( $m4is_z50f, '%%capability.' );
 $m4is_onxrbm = [ 'ID', 'user_nicename', 'user_url', 'user_registered', 'user_status', 'display_name' ];
 if ( isset( $m4is_jfds[0]->data->contact_fields[$m4is_qnjfv['order_by']] ) ) { usort($m4is_jfds, function($u1, $u2) use ($m4is_qnjfv) { $v1 = $u1->data->contact_fields[$m4is_qnjfv['order_by']];
 $v2 = $u2->data->contact_fields[$m4is_qnjfv['order_by']];
 return ($m4is_qnjfv['order'] == 'ASC') ? strnatcasecmp( $v1, $v2 ) : strnatcasecmp( $v2, $v1 );
 });
 } if ( is_array( $m4is_jfds ) ) { $m4is_yf71nc = 0;
 foreach( $m4is_jfds as $m4is_x0_hk ) { $m4is_ks1fj2 = $m4is_z50f;
 $m4is_e2kg = $m4is_x0_hk->infusionsoft_user_id;
 $m4is_p9r_8e = m4is_bnrdbo::m4is_yvnol( $m4is_e2kg );
 if ( is_array( $m4is_p9r_8e ) && ! empty( $m4is_p9r_8e['Email'] ) ) { $m4is_yf71nc++;
 if ( $m4is_ubvq ) { foreach( $m4is_p9r_8e as $m4is_s2ge5 => $m4is_w_o7al ) { $m4is_ks1fj2 = str_ireplace( '%%contact.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_ks1fj2 );
 } } if ( $m4is_xg78yx ) { foreach( $m4is_x0_hk->roles as $m4is_s2ge5 => $m4is_w_o7al ) { $m4is_ks1fj2 = str_ireplace( '%%role.' . $m4is_s2ge5 . '%%', $m4is_w_o7al, $m4is_ks1fj2 );
 } } if ( $m4is_l9cr ) { $m4is_ks1fj2 = str_ireplace( '%%meta.ipaddress%%', $m4is_x0_hk->login_ip_address, $m4is_ks1fj2 );
 $m4is_ks1fj2 = str_ireplace( '%%meta.login_count%%', (int) $m4is_x0_hk->login_count, $m4is_ks1fj2 );
 } if ( $m4is_fzyu3t ) { foreach( $m4is_onxrbm as $m4is_s2ge5 ) { $m4is_ks1fj2 = str_ireplace( '%%user.' . $m4is_s2ge5 . '%%', $m4is_x0_hk->data->$m4is_s2ge5, $m4is_ks1fj2 );
 } } $m4is_uzfw8j = preg_replace( '/(%%\S+%%)/', '', $m4is_uzfw8j );
 $m4is_uzfw8j .= $m4is_ks1fj2;
 } } }  $m4is_uzfw8j = do_shortcode($m4is_uzfw8j);
 return $m4is_uzfw8j;
 } static 
function m4is_x9k5( $m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return '';
 } if (is_feed() ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'tokens' => '', ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } $user_id = get_current_user_id();
 if (! $user_id) { return;
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 self::$m4is_bnd6ti->m4is_lrtqe8($m4is_qnjfv['tokens']);
 } static 
function m4is_b61c( $m4is_qnjfv, $m4is_z50f = null, $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_su4qk = 0;
 m4is_aoxw::m4is_djr4nd();
 $m4is_r6nh_b = [ 'actionset' => '', 'button_text' => 'Get New Password', 'email_label' => 'Username or Email', 'form_name' => 'lostpasswordform', 'goal' => '', 'redirect' => '', 'redirect' => '', 'tag_id' => 0, ];
 if (isset($m4is_qnjfv[0]) && $m4is_qnjfv[0] == 'showatts') { return implode(',', array_keys($m4is_r6nh_b) );
 } if ( self::$m4is_bnd6ti->m4is_oiewvu('settings', 'disable_lost_password') ) { if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '<p><strong style="color:red;">Admin Notice:</strong>  Lost password feature disabled in Site Security settings.</p>';
 } return '';
 } if (is_user_logged_in() ) { if (is_super_admin() ) { return '<p><strong style="color:red;">Admin Notice:</strong>  You are already logged in.</p>';
 } return '';
 } if (is_feed() ) { return '';
 } $m4is_su4qk++;
 $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['form_name'] = '_' . $m4is_su4qk;
 $m4is_qnjfv['redirect'] = empty($m4is_qnjfv['redirect']) ? get_site_url() : $m4is_qnjfv['redirect'];
 $m4is_etj2 = [ 'actionset' => $m4is_qnjfv['actionset'], 'goal' => $m4is_qnjfv['goal'], 'redirect' => $m4is_qnjfv['redirect'], 'tag_id' => $m4is_qnjfv['tag_id'], ];
 $m4is_rbwn1z = base64_encode(serialize($m4is_etj2) );
 $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6($m4is_rbwn1z);
 $m4is_tjg_9 = '';
 $m4is_etj2 = new stdclass;
 $m4is_etj2->goal = $m4is_qnjfv['goal'];
 $m4is_etj2->actionset = $m4is_qnjfv['actionset'];
 $m4is_etj2->button_text = $m4is_qnjfv['button_text'];
 $m4is_etj2->email_label = $m4is_qnjfv['email_label'];
 $m4is_etj2->form_id = $m4is_su4qk;
 $m4is_etj2->form_name = $m4is_qnjfv['form_name'];
 $m4is_etj2->message = '';
 $m4is_etj2->parameters = $m4is_rbwn1z;
 $m4is_etj2->redirect = $m4is_qnjfv['redirect'];
 $m4is_etj2->signature = $m4is_k1k7oj;
 $m4is_etj2->tag_id = $m4is_qnjfv['tag_id'];
 if (isset($_SESSION['flash']['lost_password_message']) ) { $m4is_etj2->message = $_SESSION['flash']['lost_password_message'];
 unset($_SESSION['flash']['lost_password_message']);
 } return m4is_crqo::m4is_yu7b1r($m4is_carw7y, $m4is_qnjfv, $m4is_z50f, $m4is_carw7y, $m4is_etj2);
 } static 
function m4is_e9m0g( $m4is_qnjfv = [], $m4is_z50f = null, $m4is_carw7y = '' ) { if ( self::$m4is_o3m_c5 ) { return '';
 } static $m4is_j485e = '';
 $m4is_r6nh_b = [ 'length' => self::$m4is_bnd6ti->m4is_oiewvu('settings', 'min_password_length'), 'strength' => self::$m4is_bnd6ti->m4is_oiewvu('settings', 'password_strength'), 'repeat' => true, ];
 if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 } $m4is_qnjfv = shortcode_atts($m4is_r6nh_b, $m4is_qnjfv, 'memberium');
 $m4is_qnjfv['repeat'] = m4is_crqo::m4is_c0cy5i($m4is_qnjfv['repeat'], true);
 if ( empty($m4is_j485e) || $m4is_qnjfv['repeat'] === false ) { $m4is_j485e = self::$m4is_bnd6ti->m4is_e9m0g( $m4is_qnjfv['length'], $m4is_qnjfv['strength'] );
 } return $m4is_j485e;
 } }

