<?php
define( 'DP_INTRO_TOURS_DP_BUILD_TYPE', 'PRO' );
define( 'DP_INTRO_TOURS_ADMINATOR', 'DEEP_PRESENTATION' );
define( 'DP_INTRO_TOURS_DP_DEBUG_EN', false );
define( 'DP_INTRO_TOURS_DP_ADMIN_DEBUG_EN', false );
define( 'DP_INTRO_TOURS_VERSION', '4.4.0' );
define( 'DP_INTRO_TOURS_NAME', 'Intro Tour Tutorial PRO' );
define( 'DP_INTRO_TOURS_PREFIX', 'dp_intro_tours' );
define( 'DP_INTRO_TOURS_PRODUCT_UPDATE_KEY', '' );
define( 'DP_INTRO_TOURS_PRODUCT_ADMINATOR_END_POINT', 'https://www.deeppresentation.com/wp-json/lmfwc/v2/licenses/' );
define( 'DP_INTRO_TOURS_TRACKING_ENABLED', false );
define( 'DP_INTRO_TOURS_TRACKING_CLIENT_ID', 'ykwxd4gvdw4ampj9' );
define( 'DP_INTRO_TOURS_TRACKING_CLIENT_SECRET', '803fcffcb44e71480157619dbe993f70f9812c59' );
define( 'DP_INTRO_TOURS_PRODUCT_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_FEATURES_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_DEMO_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_KEY_BUY_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_ASK_FOR_RATING_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_RATING_FEEDBACK_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_TITLE_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_LINK_PRO', 'https://deeppresentation.com/plugins/dp-intro-tours' );
define( 'DP_INTRO_TOURS_PRODUCT_FEATURES_LINK_PRO', 'https://deeppresentation.com/plugins/dp-intro-tours#pro-features' );
define( 'DP_INTRO_TOURS_PRODUCT_DEMO_LINK_PRO', 'https://demo.deeppresentation.com/' );
define( 'DP_INTRO_TOURS_PRODUCT_KEY_BUY_LINK_PRO', 'https://deeppresentation.com/product/intro-tour-tutorial-pro-plugin-for-wordpress/' );
define( 'DP_INTRO_TOURS_PRODUCT_ASK_FOR_RATING_LINK_PRO', 'https://deeppresentation.com/product/intro-tour-tutorial-pro-plugin-for-wordpress/#reviews' );
define( 'DP_INTRO_TOURS_PRODUCT_RATING_FEEDBACK_LINK_PRO', '' );
define( 'DP_INTRO_TOURS_PRODUCT_TITLE_PRO', 'Intro Tour Tutorial PRO' );
