<?php
/**
 * Copyright (c) 2012-2024 David J Bullock
 * Web Power and Light
 */

 class_exists( 'm4is_pms8y' ) || die();
 m4is_efy76::m4is_x6wv();
 
class m4is_efy76 { private static $m4is_bnd6ti, $m4is_qf47, $m4is_n3zlk, $m4is_p12f4o;
  private 
function __construct() {  }  static 
function m4is_x6wv() {  self::$m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
  self::$m4is_qf47 = m4is_sljnt::m4is_e5l8a9();
  self::$m4is_n3zlk = 'memberium';
  self::$m4is_p12f4o = self::$m4is_qf47->m4is__vjw4('parent_tags');
 }  static 
function m4is_s6j1g( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  m4is_aoxw::m4is_djr4nd();
  $m4is_r6nh_b = [ 'text' => '<p>%d of %d</p>', ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
  if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '';
 }  if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 }  $m4is_h8ys7j = self::$m4is_qf47->m4is_gbkvj();
 $m4is_xeh2s = self::$m4is_qf47->m4is_npoh1();
  $m4is_uzfw8j = sprintf( _x( $m4is_qnjfv['text'], self::$m4is_n3zlk ), $m4is_h8ys7j, $m4is_xeh2s );
  $m4is_uzfw8j = apply_filters( 'memberium/shortcodes/' . $m4is_carw7y, $m4is_uzfw8j );
  return $m4is_uzfw8j;
 }  static 
function m4is_nf10c( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  m4is_aoxw::m4is_djr4nd();
  $m4is_r6nh_b = [ 'button_text' => 'Download CSV', 'button_class' => '', 'filter_name' => '', ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  if ( ( $m4is_e2kg = m4is_wbc8os::m4is_jjgo() ) == 0) { return '';
 }  if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
  $m4is_gqid = [ 'filter_name' => $m4is_qnjfv['filter_name'], ];
  $m4is_gqid = base64_encode( serialize( $m4is_gqid ) );
  $m4is_uzfw8j = '';
  $m4is_uzfw8j .= '<form method=post>';
  $m4is_uzfw8j .= wp_nonce_field( -1, 'umbrella_download_csv_wpnonce', true, false );
  $m4is_uzfw8j .= "<input type=hidden name='params' value='{$m4is_gqid}'>";
 $m4is_uzfw8j .= "<input type=hidden name='formtype' value='umbrella_csv_download'>";
  $m4is_uzfw8j .= "<input type=submit class='' name='' value='{$m4is_qnjfv['button_text']}'>";
  $m4is_uzfw8j .= '</form>';
  return $m4is_uzfw8j;
 }  static 
function m4is_nsi2( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  global $memb_messages;
  m4is_aoxw::m4is_djr4nd();
  $m4is_r6nh_b = [ 'button_text' => 'Add Account',  'form_id' => '',  'overwrite' => false, ];
 if ( $m4is_nehd = m4is_crqo::m4is_mzob( $m4is_qnjfv, $m4is_r6nh_b ) ) { return $m4is_nehd;
 };
  if ( self::$m4is_bnd6ti->m4is_lvmz1b() ) { return '';
 }  if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 } $m4is_uzfw8j = '';
 $m4is_yer1mp = self::$m4is_qf47->m4is_gbkvj();
 $m4is_wnj5zq = self::$m4is_qf47->m4is_npoh1();
   if ( $m4is_yer1mp >= $m4is_wnj5zq ) { $m4is_uzfw8j = sprintf( '<p style="subacct_maxed">%s</p>', _x( 'All sub accounts Are Assigned.', 'umbrella_enroll_child', self::$m4is_n3zlk ) );
 return $m4is_uzfw8j;
 }  foreach( $m4is_qnjfv as $m4is_c5zg => $m4is_g0wy ) {   if ( ! array_key_exists( $m4is_c5zg, $m4is_r6nh_b ) ) { $m4is_r6nh_b[$m4is_c5zg] = $m4is_g0wy;
 } }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_qnjfv['overwrite'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['overwrite'], false );
  $m4is_yukjn_ = [];
  $m4is_loxs = '<select name="actions">';
  $m4is_oa_j2 = [];
  if ( is_array( $m4is_qnjfv ) ) { foreach( $m4is_qnjfv as $m4is_s2ge5 => $m4is_w_o7al ) {  $m4is_s2ge5 = substr( $m4is_s2ge5, 1 );
   if ( $m4is_s2ge5 > 0 || $m4is_s2ge5 === '0' ) { $m4is_loxs .= sprintf( '<option value="%s">%s</option>', $m4is_s2ge5, $m4is_w_o7al );
 $m4is_oa_j2[] = $m4is_s2ge5;
 } } }  $m4is_loxs .= '</select>';
  $m4is_yukjn_ = is_array( $m4is_oa_j2 ) ? implode( ',', $m4is_oa_j2 ) : '';
  if ( empty( $m4is_oa_j2 ) ) { $m4is_loxs .= '';
 }  if ( ! empty( $m4is_z50f ) ) { $m4is_z50f = str_ireplace( '%%action.dropdown%%', $m4is_loxs, $m4is_z50f );
 }  $m4is_gqid = base64_encode( serialize( [ 'allowed_actions' => $m4is_yukjn_, 'custom' => ! empty( $m4is_z50f ), 'overwrite' => $m4is_qnjfv['overwrite'], 'contact_id' => self::$m4is_bnd6ti->m4is_dpuy9(), ]) );
  $m4is_k1k7oj = self::$m4is_bnd6ti->m4is_nbmk6( $m4is_gqid );
  if (! empty( $memb_messages['flash']['create_child_result'] ) ) { $m4is_uzfw8j .= $memb_messages['flash']['create_child_result'];
 }  $m4is_uzfw8j .= '<form method="POST" action="" id="' . $m4is_qnjfv['form_id'] . '">';
  $m4is_uzfw8j .= '<input type="hidden" name="formtype" value="childenroll">';
 $m4is_uzfw8j .= "<input type=\"hidden\" name=\"params\" value=\"{$m4is_gqid}\">";
 $m4is_uzfw8j .= "<input type=\"hidden\" name=\"digital_signature\" value=\"{$m4is_k1k7oj}\">";
  $m4is_uzfw8j .= wp_nonce_field( 'memb_childenroll', '_wpnonce', true, false );
  if ( empty( $m4is_z50f ) ) { $m4is_uzfw8j .= sprintf( '<label>%s</label><input name="FirstName" type="text" value="" required="required"> *<br />', _x( 'First Name:', 'umbrella_enroll_child', self::$m4is_n3zlk ) );
 $m4is_uzfw8j .= sprintf( '<label>%s</label><input name="LastName" type="text" value="" required="required"> *<br />', _x( 'Last Name:', 'umbrella_enroll_child', self::$m4is_n3zlk ) );
 $m4is_uzfw8j .= sprintf( '<label>%s</label><input type="email" value="" name="Email" required="required"> *<br />', _x( 'Email Address:', 'umbrella_enroll_child', self::$m4is_n3zlk ) );
 $m4is_uzfw8j .= sprintf( '<label>%s</label><input type="tel" value="" name="Phone3"><br />', _x( 'Mobile Number:', 'umbrella_enroll_child', self::$m4is_n3zlk ) );
 }  else { $m4is_uzfw8j .= do_shortcode( $m4is_z50f );
 }  $m4is_uzfw8j .= sprintf( '<label></label><input type="submit" value="%s" name=""><br />', $m4is_qnjfv['button_text'] );
  $m4is_uzfw8j .= '</form>';
  $memb_messages['flash']['create_child_result'] = '';
  return $m4is_uzfw8j;
 }  static 
function m4is_zirlbp( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  m4is_aoxw::m4is_djr4nd();
 if ( ! class_exists( 'SFWD_LMS' ) || ! method_exists( 'SFWD_LMS', 'get_course_info' ) ) { if ( is_super_admin() ) { return '<p>LearnDash SFWD_LMS::get_course_info() method is missing.</p>';
 } return '';
 }  $m4is_r6nh_b = [ 'contact_id' => isset( $_GET['contact_id'] ) ? $_GET['contact_id'] : m4is_wbc8os::m4is_jjgo(), ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  if ( ! is_user_logged_in() ) { return '';
 }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
  $m4is_qnjfv['contact_id'] = (int) $m4is_qnjfv['contact_id'];
  if ( ! $m4is_qnjfv['contact_id'] ) { return '<p>No valid user to display.</p>';
 }  $m4is_w1j6q = self::$m4is_bnd6ti->m4is_lvmz1b();
  if ( ! $m4is_w1j6q ) { $m4is_l3cr0 = self::$m4is_qf47->m4is_drbm_5();
 $m4is_w1j6q = in_array( $m4is_qnjfv['contact_id'], $m4is_l3cr0 );
 }  if ( ! $m4is_w1j6q ) { $m4is_w1j6q = ( $m4is_qnjfv['contact_id'] == $_SESSION['keap']['contact']['id'] );
 }  if ( $m4is_w1j6q ) { $m4is_ig9p6 = m4is_bnrdbo::m4is_d3na( $m4is_qnjfv['contact_id'] );
  if ( $m4is_ig9p6 ) { $m4is_qnjfv = [ 'registered_show_thumbnail' => 'false', 'user_id' => $m4is_ig9p6 ];
 return SFWD_LMS::get_course_info( $m4is_ig9p6, $m4is_qnjfv );
 } else { $m4is_w1j6q = false;
 } }  if ( ! $m4is_w1j6q ) { return "<p>Access not permitted to this user's course records</p>";
 } }  static 
function m4is_m5a6r( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  m4is_aoxw::m4is_djr4nd();
  $m4is_r6nh_b = [ 'limit' => isset( $_GET['limit'] ) ? (int) $_GET['limit'] : 0,  'page' => isset( $_GET['pg'] ) ? (int) $_GET['pg'] : 1,  'parent_id' => m4is_wbc8os::m4is_jjgo(),  ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
  if ( $m4is_qnjfv['limit'] == 0 ) { return '';
 }  $m4is_qnjfv['count'] = self::$m4is_qf47->m4is_eqph9();
  $m4is_qnjfv['page'] = $m4is_qnjfv['page'] < 1 ? 1 : $m4is_qnjfv['page'];
  $m4is_afnh = $m4is_qnjfv['count'] > 0 ? (int) ceil( $m4is_qnjfv['count'] / $m4is_qnjfv['limit'] ) : 1;
  if ( $m4is_afnh < 2 ) { return '';
 }  $m4is_je134n = add_query_arg( 'pg', ( $m4is_qnjfv['page'] - 1) );
 $m4is_swda = add_query_arg( 'pg', ( $m4is_qnjfv['page'] + 1 ) );
  $m4is_qnjfv['page'] = ( $m4is_qnjfv['page'] < 1 ) ? 1 : $m4is_qnjfv['page'];
  $m4is_uzfw8j = '<div class="memberium_umbrella_nav" style="width:100%;">';
  if ( $m4is_qnjfv['page'] > 1 ) { $m4is_uzfw8j .= '<span class="memberium_umbrella_nav_previous" style="margin-left:30px;margin-right:30px;"><a href="' . $m4is_je134n . '">&lt;Previous&gt;</a></span>';
 }  $m4is_uzfw8j .= '<span class="">Page ' . ( $m4is_qnjfv['page'] ) . ' of ' . ( $m4is_afnh ) . '</span>';
  if ( $m4is_qnjfv['page'] < $m4is_afnh ) { $m4is_uzfw8j .= '<span class="memberium_umbrella_nav_next" style="margin-left:30px;margin-right:30px;"><a href="' . $m4is_swda . '">&lt;Next&gt;</a></span>';
 }  $m4is_uzfw8j .= '</div>';
  return $m4is_uzfw8j;
 }  static 
function m4is_low0ts( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  $m4is_r6nh_b = [ 'can_disconnect' => 'y',  'limit' => isset( $_GET['limit'] ) ? (int) $_GET['limit'] : 0,  'page' => isset( $_GET['pg'] ) ? (int) $_GET['pg'] : 1,  'parent_id' => m4is_wbc8os::m4is_jjgo(),  ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 }  m4is_aoxw::m4is_djr4nd();
  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
  $m4is_qnjfv['can_disconnect'] = m4is_crqo::m4is_c0cy5i( $m4is_qnjfv['can_disconnect'], true );
  $m4is_qnjfv['page'] = $m4is_qnjfv['page'] > 0 ? $m4is_qnjfv['page'] : 1;
 $m4is_qnjfv['page'] = $m4is_qnjfv['page'] < 1 ? 1 : $m4is_qnjfv['page'];
  $m4is_qnjfv['parent_id'] = (int) $m4is_qnjfv['parent_id'];
  $m4is_we6z87 = ( $m4is_qnjfv['page'] - 1 ) * $m4is_qnjfv['limit'];
  $m4is_uzfw8j = '';
  if ( empty( $m4is_qnjfv['parent_id'] ) ) { return '';
 }  if ( $m4is_qnjfv['limit'] ) {  $m4is_k4yeul = [ 'contact_id' => $m4is_qnjfv['parent_id'],  'limit' => $m4is_qnjfv['limit'],  'offset' => $m4is_we6z87  ];
  $m4is_z59dj = self::$m4is_qf47->m4is_drbm_5($m4is_k4yeul);
 } else {  $m4is_z59dj = self::$m4is_qf47->m4is_drbm_5();
 }  if ( ! empty( $m4is_z50f ) ) {  foreach( $m4is_z59dj as $m4is_e2kg ) {  $m4is_ks1fj2 = $m4is_z50f;
  $m4is_ygd826 = '<form method="post">';
 $m4is_ygd826 .= '<input type="hidden" name="formtype" value="childdisconnect">';
  $m4is_ygd826 .= '<input type="hidden" name="contact_id" value="' . $m4is_e2kg . '">';
  $m4is_ygd826 .= '<input type="hidden" name="signature" value="' . md5( wp_salt( 'nonce' ) . $m4is_e2kg) . '">';
  $m4is_ygd826 .= '<input type="submit" value="Disconnect">';
  $m4is_ygd826 .= '</form>';
  $m4is_ks1fj2 = str_ireplace( '%%contact.id%%', $m4is_e2kg, $m4is_ks1fj2 );
  $m4is_ks1fj2 = str_ireplace( '{{contact.id}}', $m4is_e2kg, $m4is_ks1fj2 );
  $m4is_ks1fj2 = str_ireplace( '%%disconnect.button%%', $m4is_ygd826, $m4is_ks1fj2 );
  $m4is_uzfw8j .= $m4is_ks1fj2;
 }  $m4is_uzfw8j = do_shortcode( $m4is_uzfw8j );
 }  else {  $m4is_uzfw8j = "<table style='width:100%;'>";
 $m4is_uzfw8j .= "<tr>";
  $m4is_uzfw8j .= '<td>First Name</td>';
 $m4is_uzfw8j .= '<td>Last Name</td>';
 $m4is_uzfw8j .= '<td>Email</td>';
 $m4is_uzfw8j .= '<td>Mobile Phone</td>';
 $m4is_uzfw8j .= '<td></td>';
  $m4is_uzfw8j .= "</tr>";
  if ( count( $m4is_z59dj ) ) {  foreach( $m4is_z59dj as $m4is_e2kg ) {  $m4is_p9r_8e = m4is_bnrdbo::m4is_yvnol( $m4is_e2kg );
  $m4is_uzfw8j .= '<tr>';
  $m4is_uzfw8j .= sprintf( '<td>%s</td>', $m4is_p9r_8e['FirstName'] );
 $m4is_uzfw8j .= sprintf( '<td>%s</td>', $m4is_p9r_8e['LastName'] );
 $m4is_uzfw8j .= sprintf( '<td><a href="mailto:%s">%s</a></td>', $m4is_p9r_8e['Email'], $m4is_p9r_8e['Email'] );
 $m4is_uzfw8j .= sprintf( '<td>%s</td>', $m4is_p9r_8e['Phone3'] );
 $m4is_uzfw8j .= '<td>';
  if ( $m4is_qnjfv['can_disconnect'] ) {  $m4is_uzfw8j .= '<form method="post">';
 $m4is_uzfw8j .= '<input type="hidden" name="formtype" value="childdisconnect">';
  $m4is_uzfw8j .= '<input type="hidden" name="contact_id" value="' . $m4is_p9r_8e['Id'] . '">';
  $m4is_uzfw8j .= '<input type="hidden" name="signature" value="' . md5( wp_salt( 'nonce' ) . $m4is_p9r_8e['Id'] ) . '">';
  $m4is_uzfw8j .= '<input type="submit" value="Disconnect">';
  $m4is_uzfw8j .= '</form>';
 }  $m4is_uzfw8j .= '</td>';
 $m4is_uzfw8j .= '</tr>';
 } } else {  }  $m4is_uzfw8j .= "</table>";
 }  return $m4is_uzfw8j;
 }  static 
function m4is_f7pog( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  m4is_aoxw::m4is_djr4nd();
  $m4is_r6nh_b = [ 'course_class' => 'umbrella_lms_dashboard_course',  'course_style' => 'margin-bottom:6px;padding:20px 10px 20px 10px;background-color:#eee;',  'date_format' => 'F j, Y',  'template' => $m4is_carw7y,  'user_class' => 'umbrella_lms_dashboard_user',  'user_style' => 'margin-bottom:12px;padding:20px 10px 20px 10px;background-color:#eee;',  ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_jfds = [];
  $m4is_d6w3io = [];
  $m4is_l3cr0 = self::$m4is_qf47->m4is_xxks();
   if ( count( $m4is_l3cr0 ) ) {  $m4is_k4yeul = [ 'fields' => [ 'ID',  'display_name',  'user_email'  ], 'include' => $m4is_l3cr0,  'order' => 'ASC',  'orderby' => 'display_name',  ];
  $m4is_tjidk = new WP_User_Query( $m4is_k4yeul );
  $m4is_jfds = $m4is_tjidk->results;
 }  foreach( $m4is_jfds as $m4is_s2ge5 => $m4is_x0_hk ) {  $m4is_nsjf = $m4is_x0_hk->ID;
  if ( function_exists( 'learndash_user_get_enrolled_courses' ) ) {  $m4is_v948s = learndash_user_get_enrolled_courses( $m4is_nsjf );
  sort( $m4is_v948s );
  $m4is_cbqkda = get_user_meta( $m4is_nsjf, '_sfwd-course_progress', true );
  $m4is_jfds[$m4is_s2ge5]->courses = [];
  foreach( $m4is_v948s as $m4is_vcqzl ) {  if ( get_post_status( $m4is_vcqzl ) == 'publish' && get_post_type( $m4is_vcqzl ) == 'sfwd-courses' ) {  $m4is_c2ah = get_post( $m4is_vcqzl );
  $m4is_hzew8 = learndash_get_course_steps_count( $m4is_vcqzl );
  $m4is_a03tz4 = isset( $m4is_cbqkda[$m4is_vcqzl]['last_id'] ) ? $m4is_cbqkda[$m4is_vcqzl]['last_id'] : 0;
  $m4is_xo0j = learndash_course_get_completed_steps( $m4is_nsjf, $m4is_vcqzl );
  $m4is_x2l6gf = empty( $m4is_hzew8 ) ? 0 : (int) ( $m4is_xo0j / $m4is_hzew8 * 100 );
  $m4is_lq7v = function_exists( 'learndash_user_get_course_completed_date' ) ? (int) learndash_user_get_course_completed_date( $m4is_nsjf, $m4is_vcqzl ) : 0;
  $m4is_hfq4i = empty( $m4is_a03tz4 ) ? 'None' : get_the_title( $m4is_a03tz4 );
  $m4is_yy6bl = new stdclass;
 $m4is_yy6bl->course_title = $m4is_c2ah->post_title;
 $m4is_yy6bl->completed_timestamp = $m4is_lq7v;
 $m4is_yy6bl->course_steps = $m4is_hzew8;
 $m4is_yy6bl->completed_steps = $m4is_xo0j;
 $m4is_yy6bl->step_title = $m4is_hfq4i;
 $m4is_yy6bl->percentage = $m4is_x2l6gf;
 $m4is_yy6bl->access_expired = (int) ld_course_access_expired( $m4is_vcqzl, $m4is_nsjf );
 $m4is_yy6bl->expiration_timestamp = (int) ld_course_access_expires_on( $m4is_vcqzl, $m4is_nsjf );
  $m4is_jfds[$m4is_s2ge5]->courses[$m4is_vcqzl] = $m4is_yy6bl;
 } } }  }   return m4is_crqo::m4is_yu7b1r( $m4is_carw7y, $m4is_qnjfv, $m4is_z50f, $m4is_carw7y, $m4is_jfds );
 }  static 
function m4is_eyvtk( $m4is_qnjfv = [], $m4is_z50f = '', $m4is_carw7y = '' ) : string {  m4is_aoxw::m4is_djr4nd();
  $m4is_r6nh_b = [ 'button_class' => '', 'button_text' => 'Transfer Points', 'field' => '', 'max' => 0, 'min' => 1, 'redirect' => '', ];
  if ( isset( $m4is_qnjfv[0] ) && $m4is_qnjfv[0] == 'showatts' ) { return implode( ',', array_keys( $m4is_r6nh_b ) );
 }  if ( m4is_wbc8os::m4is_jjgo() == 0 ) { return '';
 } if ( ! self::$m4is_bnd6ti->m4is_sjmzx( self::$m4is_p12f4o ) ) { return '';
 }  $m4is_qnjfv = shortcode_atts( $m4is_r6nh_b, $m4is_qnjfv, self::$m4is_n3zlk );
 $m4is_qnjfv['field'] = strtolower( trim( $m4is_qnjfv['field'] ) );
  if ( empty( $m4is_qnjfv['field'] ) ) { return '';
 }  $m4is_zua17 = (float) $_SESSION['keap']['contact'][$m4is_qnjfv['field']];
 $child_ids = self::$m4is_qf47->m4is_xxks();
  $m4is_y0ky5n = [];
 $params = [ 'field' => $m4is_qnjfv['field'], 'max_points' => $m4is_zua17, 'pcid' => $contact_id, 'redirect' => $m4is_qnjfv['redirect'], ];
  if ( count( $child_ids ) ) { $m4is_k4yeul = [ 'fields' => [ 'ID', 'display_name', 'user_email' ], 'include' => $child_ids, 'order' => 'ASC', 'orderby' => 'display_name', ];
 $m4is_tjidk = new WP_User_Query( $m4is_k4yeul );
 $m4is_y0ky5n = $m4is_tjidk->results;
 }  $m4is_etj2 = new stdclass;
 $m4is_etj2->params = base64_encode( serialize( $params ) );
 $m4is_etj2->users = $m4is_y0ky5n;
 $m4is_etj2->points = $m4is_zua17;
 $m4is_etj2->headers = wp_nonce_field( $m4is_etj2->params, 'umbrella_transfer_points_wpnonce', true, false );
 $m4is_etj2->headers .= "<input type='hidden' name='signature' value='{$m4is_etj2->params}'>";
 $m4is_etj2->headers .= "<input type='hidden' name='formtype' value='umbrella_points_transfer'>";
 $m4is_etj2->redirect = $m4is_qnjfv['redirect'];
  return m4is_crqo::m4is_yu7b1r( $m4is_carw7y, $m4is_qnjfv, $m4is_z50f, $m4is_carw7y, $m4is_etj2 );
 } }

