<?php
/**
 * Copyright (c) 2012-2024 David J Bullock
 * Web Power and Light, LLC
 * https://webpowerandlight.com
 * support@webpowerandlight.com
 *
 */

 class_exists('m4is_pms8y') || die();
 m4is_kfea::m4is_x6wv();
 final 
class m4is_kfea { private static $m4is_bnd6ti, $m4is_zq0k, $m4is_bh12zy, $m4is_j_xo4w, $m4is_i0hu7m, $m4is_n3zlk;
 static 
function m4is_x6wv() { self::$m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 self::$m4is_zq0k = self::$m4is_bnd6ti->m4is_d14zr( 'appname' );
 self::$m4is_bh12zy = m4is_w0enbm::m4is_e5l8a9();
 self::$m4is_j_xo4w = self::$m4is_bnd6ti->m4is_zw_n();
 self::$m4is_i0hu7m = ! m4is_u68pu::m4is_u6mkaw();
 self::$m4is_n3zlk = 'memberium';
 }  static 
function m4is_ndgebf() { if ( self::$m4is_i0hu7m) { return;
 } m4is_aoxw::m4is_djr4nd();
 if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'place_order_button-' . $_POST['form_id'] ) ) { wp_die( 'Security Check Failed - Nonce Validation Error' );
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['digital_signature'], $_POST['order_settings'] ) ) { wp_die( 'Security Check Failed - Signature Validation Error' );
 } $m4is_e2kg = (int) self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_su4qk = (int) $_POST['form_id'];
 $m4is_negcx = unserialize( base64_decode( $_POST['order_settings'] ) );
 $m4is_c4lk = self::$m4is_bnd6ti->m4is_yep9( $m4is_negcx );
 if ( $m4is_c4lk ) { if ( $m4is_negcx['success_url'] > '' ) { $m4is_b5kaz0 = $m4is_negcx['success_url'];
 } } else { if ( $m4is_negcx['fail_url'] > '' ) { $m4is_b5kaz0 = $m4is_negcx['fail_url'];
 } } self::$m4is_bnd6ti->m4is_leu58( $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_m3vz( $m4is_e2kg );
 if ( $m4is_b5kaz0 > '' ) { m4is_aoxw::m4is_g7bv();
 wp_redirect( $m4is_b5kaz0, 302, 'Memberium - Order Catcher' );
 exit;
 } }  static 
function m4is_lqok_z() { if ( self::$m4is_i0hu7m) { return;
 } if ( ! self::$m4is_bnd6ti->m4is_dpuy9() ) { return;
 } $m4is_l6tf_ = 'memb_actionset_button';
 m4is_aoxw::m4is_djr4nd();
 if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'memb_actionset_' . $_POST['form_id'] ) ) { wp_die( _x( 'Security Check Failed - Nonce Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['action'] ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 } $m4is_v6fdv4 = unserialize( base64_decode( $_POST['action'] ) );
 $m4is_e2kg = isset( $m4is_v6fdv4['contact_id'] ) ? $m4is_v6fdv4['contact_id'] : self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_su4qk = isset( $_POST['form_id'] ) ? (int) $_POST['form_id'] : 0;
 $m4is_ae8w = isset( $_POST['order_id'] ) ? (int) $_POST['order_id'] : 0;
 $m4is_b5kaz0 = isset( $m4is_v6fdv4['redirect'] ) ? $m4is_v6fdv4['redirect'] : '';
 if ( empty( $m4is_b5kaz0 ) ) { $m4is_b5kaz0 = isset( $_SERVER['HTTP_REFERER'] ) ? $_SERVER['HTTP_REFERER'] : $_SERVER['REQUEST_URI'];
 } if ( $m4is_e2kg > 0 ) { self::$m4is_bnd6ti->m4is_lrtqe8( $m4is_v6fdv4['tokens'] );
 self::$m4is_bnd6ti->m4is_rldxj3( $m4is_v6fdv4['fus'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_cqe6_( $m4is_v6fdv4['goals'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_v6fdv4['tags'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_u86vzq( $m4is_v6fdv4['action_id'], $m4is_e2kg) ;
 } $m4is_k4yeul = [ 'action_id' => $m4is_v6fdv4['action_id'], 'contact_id' => $m4is_v6fdv4['contact_id'], 'fus' => $m4is_v6fdv4['fus'], 'goals' => $m4is_v6fdv4['goals'], 'tags' => $m4is_v6fdv4['tags'], 'redirect' => $m4is_b5kaz0, ];
 do_action( 'memberium/actionset_button/clicked', $m4is_k4yeul );
 if ( $m4is_v6fdv4['debug'] ) { echo '<pre>';
 echo __LINE__, " - Set ActionSet = {$m4is_v6fdv4['action_id']}<br />";
 echo __LINE__, " - Set ContactId = {$m4is_v6fdv4['contact_id']}<br />";
 echo __LINE__, " - Set FUS       = {$m4is_v6fdv4['fus']}<br />";
 echo __LINE__, " - Set Goals     = {$m4is_v6fdv4['goals']}<br />";
 echo __LINE__, " - Set Tags      = {$m4is_v6fdv4['tags']}<br />";
 echo __LINE__, " - Set Tokens    = {$m4is_v6fdv4['tokens']}<br />";
 echo __LINE__, " - Set Redirect  = {$m4is_b5kaz0}<br />";
 echo '</pre>';
 echo '<a href="', $m4is_b5kaz0, '">', _x('Continue...', $m4is_l6tf_, self::$m4is_n3zlk ), '</a>';
 exit;
 } if ( $m4is_b5kaz0 > '' ) { m4is_aoxw::m4is_g7bv();
 wp_redirect( $m4is_b5kaz0, 302, 'Memberium Actionset Button' );
 exit;
 } }  static 
function m4is_fj9mzr() { if ( empty( $_FILES['uploadedfiles'] ) ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_l6tf_ = 'memb_filebox_upload';
 $m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['params'] ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 exit;
 } $m4is_gqid = unserialize( base64_decode( $_POST['params'] ) );
 $m4is_e2kg = (int) $m4is_gqid['contact_id'];
 $m4is_y8_12 = $m4is_gqid['rename'];
 $m4is_vxvnk = count( $_FILES['uploadedfiles']['name'] );
 $m4is_u902dl = 0;
 $m4is_lu0vp = '';
 $m4is_p1ihx = [];
 for ( $m4is_tiq5k6 = 0;
 $m4is_tiq5k6 < $m4is_vxvnk;
 $m4is_tiq5k6++ ) { $m4is_t5ot4 = $_FILES['uploadedfiles']['name'][$m4is_tiq5k6];
 $m4is_u23rl = $_FILES['uploadedfiles']['type'][$m4is_tiq5k6];
 $m4is_ncu_mz = $_FILES['uploadedfiles']['tmp_name'][$m4is_tiq5k6];
 $m4is_jadl06 = $_FILES['uploadedfiles']['error'][$m4is_tiq5k6];
 $m4is_iqyv = $_FILES['uploadedfiles']['size'][$m4is_tiq5k6];
 if ( $m4is_iqyv > $m4is_gqid['maxsize'] || $m4is_jadl06 == 2 ) { $m4is_u902dl++;
 $m4is_lu0vp .= sprintf( '<p class="filebox_upload_error">File size of "%s" exceeded the %s limit.</p>', $m4is_t5ot4, size_format( $m4is_gqid['maxsize'] ) );
 continue;
 } if (! empty($m4is_jadl06) ) { $m4is_u902dl++;
 $m4is_lu0vp .= sprintf( '<p class="filebox_upload_error">Upload of %s failed (%s).</p>', $m4is_t5ot4, $m4is_jadl06 );
 continue;
 } $m4is_p1ihx[] = [ 'name' => $m4is_t5ot4, 'type' => $m4is_u23rl, 'size' => $m4is_iqyv, 'error' => $m4is_jadl06, 'tmp_name' => $m4is_ncu_mz, ];
 } if ($m4is_gqid['no_errors'] && $m4is_u902dl) { $m4is_lu0vp .= '<p class="filebox_upload_error">Some uploads failed.  No files saved.</p>';
 $m4is_u902dl++;
 } else { foreach($m4is_p1ihx as $m4is_m_mie7) {  if (! empty($m4is_y8_12) ) { $m4is_m_mie7['name'] = $m4is_y8_12 . '.' . pathinfo( $m4is_m_mie7['name'], PATHINFO_EXTENSION );
 }  $m4is_tc3h = base64_encode( file_get_contents( $m4is_m_mie7['tmp_name'] ) );
 $m4is_oa_z = self::$m4is_j_xo4w->uploadFile( $m4is_m_mie7['name'], $m4is_tc3h, $m4is_e2kg );
 if ( $m4is_oa_z < 1 ) { $m4is_lu0vp .= substr( $m4is_oa_z, strpos($m4is_oa_z, ']') + 1, -1 ) . ' for ' . $m4is_m_mie7['name'];
 } unset($m4is_tc3h);
 unlink($m4is_m_mie7['tmp_name']);
 if (! (int) $m4is_oa_z) { $m4is_u902dl++;
 } } m4is_ru7njr::m4is_x29z( $m4is_e2kg, true );
 } $m4is_s2ge5 = 'memberium::file_upload_msg::' . get_current_user_id();
 if ( $m4is_u902dl ) {   $m4is_oa_z = set_transient( $m4is_s2ge5, $m4is_lu0vp, 3600 );
 self::$m4is_bh12zy->m4is_c043n( $m4is_lu0vp );
 self::$m4is_bnd6ti->m4is_cqe6_( $m4is_gqid['failure_goals'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_u86vzq( $m4is_gqid['failure_actionsets'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_gqid['failure_tags'], $m4is_e2kg );
 if ( ! empty( $m4is_gqid['failure_url'] ) ) { wp_redirect( $m4is_gqid['failure_url'], 302 );
 die();
 } } else {   $m4is_oa_z = set_transient( $m4is_s2ge5, $m4is_gqid['success_msg'], 3600 );
 self::$m4is_bh12zy->m4is_c043n( $m4is_gqid['success_msg'] );
 self::$m4is_bnd6ti->m4is_cqe6_( $m4is_gqid['success_goals'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_u86vzq( $m4is_gqid['success_actionsets'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_gqid['success_tags'], $m4is_e2kg );
 if ( ! empty( $m4is_gqid['success_url'] ) ) { wp_redirect( $m4is_gqid['success_url'], 302 );
 die();
 } } }  static 
function m4is_z9pmy() { m4is_aoxw::m4is_djr4nd();
 $m4is_su4qk = $_POST['form_id'];
 if (! wp_verify_nonce($_POST['_wpnonce'], 'memb_placeorder_' . $m4is_su4qk) ) { wp_die( 'Security Check Failed - Nonce Validation Error' );
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['digital_signature'], $_POST['params'] ) ) { wp_die( 'Security Check Failed - Signature Validation Error' );
 } $m4is_cwkrz = unserialize( base64_decode( $_POST['params'] ) );
 if ( empty( $m4is_cwkrz['lead_affiliate_id'] ) || empty( $m4is_cwkrz['sale_affiliate_id'] ) ) {  $m4is_dj_2 = 'Invoice';
 $m4is_w_8g = [ 'AffiliateId', 'LeadAffiliateId' ];
 $m4is_jo8fb = [ 'ContactId' => (int) $m4is_cwkrz['contact_id'] ];
 $m4is_qrgskj = 'Id';
 $m4is_f8qb1a = false;
 $m4is_craco = m4is_ho3l::m4is_mlhu4( $m4is_dj_2, 1, 0, $m4is_jo8fb, $m4is_w_8g, $m4is_qrgskj, $m4is_f8qb1a );
 if ( count( $m4is_craco ) ) { if ( empty( $m4is_cwkrz['lead_affiliate_id'] ) ) { $m4is_cwkrz['lead_affiliate_id'] = isset( $invoice[0]['LeadAffiliateId'] ) ? $invoice[0]['LeadAffiliateId'] : 0;
 } if (empty($m4is_cwkrz['sale_affiliate_id']) ) { $m4is_cwkrz['sale_affiliate_id'] = isset( $invoice[0]['AffiliateId'] ) ? $invoice[0]['AffiliateId'] : 0;
 } } } $m4is_wdjmn = self::$m4is_j_xo4w->placeOrder( (int) $m4is_cwkrz['contact_id'], (int) $m4is_cwkrz['creditcard_id'], (int) $m4is_cwkrz['payplan_id'], (array) $m4is_cwkrz['product_ids'], (array) $m4is_cwkrz['subscription_ids'], (bool) $m4is_cwkrz['process_specials'], (array) $m4is_cwkrz['promo_codes'], (int) $m4is_cwkrz['lead_affiliate_id'], (int) $m4is_cwkrz['sale_affiliate_id'] );
  $m4is_c4lk = (int) $m4is_wdjmn['InvoiceId'];
 $m4is_jwfnh = (int) $m4is_wdjmn['OrderId'];
 if ( $m4is_wdjmn['Successful'] == 'true' ) { $m4is_a2ko04 = $m4is_cwkrz['success_actionset'];
 $m4is_xf9b = $m4is_cwkrz['success_goal'];
 $m4is_mpia = $m4is_cwkrz['success_tag'];
 $m4is_imdo6 = $m4is_cwkrz['success_url'];
 if ( ! empty( $m4is_cwkrz['order_title'] ) ) { m4is_ho3l::m4is_btu_( 'Job', $m4is_jwfnh, ['JobTitle' => $m4is_cwkrz['order_title']] );
 } } else { $m4is_a2ko04 = $m4is_cwkrz['failure_actionset'];
 $m4is_xf9b = $m4is_cwkrz['failure_goal'];
 $m4is_mpia = $m4is_cwkrz['failure_tag'];
 $m4is_imdo6 = $m4is_cwkrz['failure_url'];
 if ( $m4is_cwkrz['delete_failed'] ) { self::$m4is_j_xo4w->deleteInvoice( $m4is_c4lk );
 if ( ! empty( $m4is_cwkrz['subscription_ids'] ) ) { m4is_untczd::m4is_q2dtc( $m4is_jwfnh );
 } } } self::$m4is_bnd6ti->m4is_lmbz( $m4is_cwkrz['contact_id'], $m4is_mpia, $m4is_a2ko04, $m4is_xf9b );
 if ( ! empty( $m4is_imdo6 ) ) { m4is_aoxw::m4is_g7bv();
 $m4is_gqid = [ 'orderId' => rawurlencode( $m4is_jwfnh ), 'invoiceId' => rawurlencode( $m4is_c4lk ), ];
 $m4is_imdo6 = add_query_arg( $m4is_gqid, $m4is_imdo6 );
 wp_redirect( $m4is_imdo6, 302 );
 exit;
 } } static 
function m4is_ni87f6() {  $m4is_l6tf_ = 'memb_resetfeedurl_button';
 m4is_aoxw::m4is_djr4nd();
 if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'memb_resetfeedurl_' . $_POST['form_id'] ) ) { wp_die( _x('Security Check Failed - Nonce Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 exit;
 } m4is_bea_0::m4is_f5y2();
 return;
 } static 
function m4is_orwh3() { if ( self::$m4is_i0hu7m) { return;
 } if (! self::$m4is_bnd6ti->m4is_dpuy9() ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_l6tf_ = 'memb_list_subscriptions';
 $m4is_rbwn1z = unserialize( base64_decode( $_POST['parameters'] ) );
 if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'memb_cancelsubscription_' . $m4is_rbwn1z['recurringorder_id'] ) ) { wp_die( _x( 'Security Check Failed - Nonce Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 exit;
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['parameters'] ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 exit;
 } $m4is_e2kg = self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_wov2 = self::$m4is_bnd6ti->m4is_oiewvu();
 $m4is_hb67 = (int) $m4is_rbwn1z['recurringorder_id'];
 $m4is_n58no = (int) $m4is_rbwn1z['subscriptionplan_id'];
 $m4is_xfch = (bool) $m4is_rbwn1z['immediate'];
 $m4is_s1_6 = $m4is_rbwn1z['cancel_text'];
 $m4is_oa_j2 = isset( $m4is_wov2['ecommerce']['actions'][$m4is_n58no] ) ? $m4is_wov2['ecommerce']['actions'][$m4is_n58no] : [];
 $m4is_a7rbf5 = isset( $m4is_oa_j2['cancel_action'] ) ? $m4is_oa_j2['cancel_action'] : 0;
 $m4is_hmv6cu = isset( $m4is_oa_j2['cancel_goal'] ) ? $m4is_oa_j2['cancel_goal'] : '';
 $m4is_v31f = isset( $m4is_oa_j2['end_action'] ) ? $m4is_oa_j2['end_action'] : 0;
 $m4is_i_w8 = isset( $m4is_oa_j2['end_goal'] ) ? $m4is_oa_j2['end_goal'] : '';
 $m4is_jl7j9 = date( 'Ymd' );
 $m4is_fw0qk = date( 'Ymd', strtotime( $m4is_rbwn1z['next_bill_date'] . ' - 1 day' ) );
 $m4is_t43e2 = $m4is_xfch ? $m4is_jl7j9 : $m4is_fw0qk;
  $m4is__xn_jt = [ 'AutoCharge' => 0, 'ReasonStopped' => sprintf( _x( 'Cancelled through Memberium on %s.  Old End Date: %s, New End Date: %s', $m4is_l6tf_, self::$m4is_n3zlk ), date( 'Y-m-d' ), $m4is_fw0qk, $m4is_t43e2 ), 'EndDate' => $m4is_t43e2 . 'T23:59:59', ];
 if ( $m4is_t43e2 <= $m4is_jl7j9 ) { $m4is__xn_jt['Status'] = 'Inactive';
 } $m4is_oa_z = m4is_ho3l::m4is_btu_( 'RecurringOrder', $m4is_hb67, $m4is__xn_jt );
  if ( $m4is_a7rbf5 > 0 ) { m4is_tvc2xn::m4is_znq_1( $m4is_e2kg, (int) $m4is_a7rbf5 );
 } if ( $m4is_hmv6cu > '' ) { m4is_ho3l::m4is_xy3j( $m4is_e2kg, $m4is_hmv6cu, self::$m4is_zq0k );
 }  if ( $m4is_v31f > 0 || $m4is_i_w8 > '' ) { $m4is_etj2 = [ 'recurringorder_id' => $m4is_hb67, 'end_action' => $m4is_v31f, 'end_goal' => $m4is_i_w8, ];
 if ( $m4is_v31f > 0 ) { self::$m4is_bnd6ti->m4is_i7lmig( 'actionset', $m4is_fw0qk, $m4is_etj2 );
 } if ( $m4is_i_w8 > '' ) { self::$m4is_bnd6ti->m4is_i7lmig( 'achievegoal', $m4is_fw0qk, $m4is_etj2 );
 } }  self::$m4is_bnd6ti->m4is_ow9yjk( $m4is_e2kg );
 $m4is_wb9f = self::$m4is_bnd6ti->m4is_ts0h3x( $m4is_e2kg, true );
 $m4is_r90_ = [ 'action' => 'Cancel', 'subscription_id' => $m4is_hb67, 'end_date' => date( 'Y-m-d', strtotime( $m4is_fw0qk ) ), 'future_expiry' => date( 'Ymd' ) <= $m4is_t43e2 ? 0 : 1, ];
 $m4is_imdo6 = add_query_arg( $m4is_r90_, $_SERVER['REQUEST_URI'] );
 m4is_aoxw::m4is_g7bv();
 wp_redirect( $m4is_imdo6 );
 exit;
 } static 
function m4is_iu7hr3() { if ( self::$m4is_i0hu7m) { return;
 } if ( ! self::$m4is_bnd6ti->m4is_dpuy9() ) { return;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_l6tf_ = 'memb_add_creditcard';
  if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'creditcard_add_' . $_POST['form_id'] ) ) { wp_die( _x( 'Security Check Failed - Nonce Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['parameters'] ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 } $m4is_haon5 = true;
 $m4is_jrq3 = false;
 $m4is_su4qk = (int) $_POST['form_id'];
 $m4is_rbwn1z = unserialize( base64_decode( $_POST['parameters'] ) );
 $m4is_fd39g = (bool) $m4is_rbwn1z['backcharge'];
 $m4is__4en6o = (int) $m4is_rbwn1z['creditcard_id'];
 $m4is_way_oq = array_filter( explode( ',', $m4is_rbwn1z['plan_ids'] ) );
 $m4is_ay3s = (bool) $m4is_rbwn1z['set_default'];
 $m4is_e2kg = (int) $m4is_rbwn1z['contact_id'];
  $m4is_ipou = trim( $m4is_rbwn1z['successurl'] );
 $m4is_ab9c = trim( $m4is_rbwn1z['failureurl'] );
 $m4is_b5kaz0 = $m4is_ab9c;
 $m4is_yh5y = (bool) $m4is_rbwn1z['debug'];
 $m4is_fyf80 = $m4is_rbwn1z['debug_ip'] === m4is_vv5u::m4is_s15o8k();
 if ( $m4is_e2kg < 1 ) { $m4is_haon5 = false;
 $_SESSION['flash']['add_creditcard'] = _x( 'Invalid User ID', $m4is_l6tf_, self::$m4is_n3zlk );
 } $_SESSION['flash']['add_creditcard'] = $m4is_rbwn1z['success_msg'];
  if ( empty( $_POST['cardtype']) && ! empty( $_POST['cc-number'] ) ) { $_POST['cardtype'] = m4is_k78c::m4is_cdru( $_POST['cc-number'] );
 }  $m4is_w_8g = [ 'city', 'country', 'firstname', 'lastname', 'nameoncard', 'state', 'streetaddress1', 'streetaddress2', ];
 foreach($_POST as $m4is_s2ge5 => $m4is_w_o7al) { $_POST[$m4is_s2ge5] = stripslashes( $m4is_w_o7al );
 }   if ( ! $m4is__4en6o ) { $m4is_wk1bir = [ 'cardtype', 'cc-number', 'city', 'country', 'cvv2', 'expirationmonth', 'expirationyear', 'nameoncard', 'phonenumber', 'streetaddress1', ];
 } else { $m4is_wk1bir = [ 'city', 'country', 'cvv2', 'expirationmonth', 'expirationyear', 'nameoncard', 'phonenumber', 'streetaddress1', ];
 } if ( is_array( $m4is_wk1bir ) ) { foreach ($m4is_wk1bir as $m4is_g1ru50) { if ( empty( $_POST[$m4is_g1ru50] ) || trim( $_POST[$m4is_g1ru50] ) == '') { $_SESSION['flash']['add_creditcard'] = _x( 'You need to fill out all required fields.', $m4is_l6tf_, self::$m4is_n3zlk );
 $m4is_haon5 = false;
 break;
 } } }  if ( $m4is_haon5 ) { if ( ( date( 'Ym' ) > ( $_POST['expirationyear'] . $_POST['expirationmonth'] ) ) ) { $_SESSION['flash']['add_creditcard'] = _x( 'The credit card is expired.', $m4is_l6tf_, self::$m4is_n3zlk );
 $m4is_haon5 = false;
 } }  if ( $m4is__4en6o == 0 ) { if ( $m4is_haon5 ) { if ( ! m4is_k78c::m4is_neax( $_POST['cc-number'] ) ){ $_SESSION['flash']['add_creditcard'] = _x( 'The credit card number is invalid.', 'memb_add_creditcard', self::$m4is_n3zlk );
 $m4is_haon5 = false;
 } } }  if ( isset( $_POST['cc-number'] ) && $m4is_haon5 ) { $m4is_sgckmy = substr( $_POST['cc-number'], -4 );
 $alt_card_id = self::$m4is_j_xo4w->locateCard( $m4is_e2kg, $m4is_sgckmy );
 if ( $alt_card_id > 0 ) { $m4is_tkb7m = m4is_akcfiz::m4is_ms5b( $m4is_e2kg );
 if ( isset( $m4is_tkb7m[$alt_card_id] ) ) { $m4is__4en6o = (int) $alt_card_id;
 } } } if ( $m4is_haon5 ) { if ( $m4is__4en6o == 0 ) { $m4is_jbyo57 = [ 'ContactId' => $m4is_e2kg, 'BillName' => wp_strip_all_tags( $_POST['nameoncard'] ), 'BillAddress1' => wp_strip_all_tags( $_POST['streetaddress1'] ), 'BillAddress2' => wp_strip_all_tags( $_POST['streetaddress2'] ), 'BillCity' => wp_strip_all_tags( $_POST['city'] ), 'BillCountry' => wp_strip_all_tags( $_POST['country'] ), 'BillState' => wp_strip_all_tags( $_POST['state'] ), 'BillZip' => wp_strip_all_tags( $_POST['postalcode'] ), 'CardNumber' => wp_strip_all_tags( $_POST['cc-number'] ), 'CardType' => wp_strip_all_tags( $_POST['cardtype'] ), 'CVV2' => (string) $_POST['cvv2'],  'FirstName' => m4is_wbc8os::m4is_sfnmc( 'firstname' ), 'LastName' => m4is_wbc8os::m4is_sfnmc( 'lastname' ), 'ExpirationMonth' => wp_strip_all_tags( $_POST['expirationmonth'] ), 'ExpirationYear' => wp_strip_all_tags( $_POST['expirationyear'] ), 'NameOnCard' => wp_strip_all_tags( $_POST['nameoncard'] ), 'Email' => strtolower( m4is_wbc8os::m4is_sfnmc( 'email' ) ), 'PhoneNumber' => wp_strip_all_tags($_POST['phonenumber']), 'ShipAddress1' => m4is_wbc8os::m4is_sfnmc( 'address2street1' ), 'ShipAddress2' => m4is_wbc8os::m4is_sfnmc( 'address2street2' ), 'ShipCity' => m4is_wbc8os::m4is_sfnmc( 'city2' ), 'ShipCompanyName' => m4is_wbc8os::m4is_sfnmc( 'company' ), 'ShipCountry' => m4is_wbc8os::m4is_sfnmc( 'country2' ), 'ShipFirstName' => m4is_wbc8os::m4is_sfnmc( 'firstname' ), 'ShipLastName' => m4is_wbc8os::m4is_sfnmc( 'lastname' ), 'ShipMiddleName' => '', 'ShipName' => wp_strip_all_tags( $_POST['nameoncard'] ), 'ShipPhoneNumber' => wp_strip_all_tags( $_POST['phonenumber'] ), 'ShipState' => m4is_wbc8os::m4is_sfnmc( 'state2' ), 'ShipZip' => m4is_wbc8os::m4is_sfnmc( 'postalcode2' ), ];
 $m4is__4en6o = m4is_ho3l::m4is_l6wj( 'CreditCard', $m4is_jbyo57 );
 if ( $m4is__4en6o > 0 ) { $m4is_jrq3 = true;
 } } else { $m4is_mzcd = [ 'BillName' => wp_strip_all_tags( $_POST['nameoncard']), 'BillAddress1' => wp_strip_all_tags( $_POST['streetaddress1']), 'BillAddress2' => wp_strip_all_tags( $_POST['streetaddress2']), 'BillCity' => wp_strip_all_tags( $_POST['city']), 'BillCountry' => wp_strip_all_tags( $_POST['country']), 'BillState' => wp_strip_all_tags( $_POST['state'] ), 'BillZip' => wp_strip_all_tags( $_POST['postalcode'] ), 'ExpirationMonth' => wp_strip_all_tags( $_POST['expirationmonth'] ), 'ExpirationYear' => wp_strip_all_tags( $_POST['expirationyear'] ), 'NameOnCard' => wp_strip_all_tags( $_POST['nameoncard'] ), 'PhoneNumber' => wp_strip_all_tags( $_POST['phonenumber'] ), 'ShipName' => wp_strip_all_tags( $_POST['nameoncard'] ), 'ShipPhoneNumber' => wp_strip_all_tags( $_POST['phonenumber'] ), 'CVV2' => (string) trim( $_POST['cvv2'] ), 'Email' => strtolower( m4is_wbc8os::m4is_sfnmc( 'email' ) ), 'FirstName' => m4is_wbc8os::m4is_sfnmc( 'firstname' ), 'LastName' => m4is_wbc8os::m4is_sfnmc( 'lastname' ), 'ShipAddress1' => m4is_wbc8os::m4is_sfnmc( 'address2street1' ), 'ShipAddress2' => m4is_wbc8os::m4is_sfnmc( 'address2street2' ), 'ShipCity' => m4is_wbc8os::m4is_sfnmc( 'city2' ), 'ShipCompanyName' => m4is_wbc8os::m4is_sfnmc( 'company' ), 'ShipCountry' => m4is_wbc8os::m4is_sfnmc( 'country2' ), 'ShipFirstName' => m4is_wbc8os::m4is_sfnmc( 'firstname' ), 'ShipLastName' => m4is_wbc8os::m4is_sfnmc( 'lastname' ), 'ShipState' => m4is_wbc8os::m4is_sfnmc( 'state2' ), 'ShipZip' => m4is_wbc8os::m4is_sfnmc( 'postalcode2' ), 'MaestroIssueNumber' => '', 'ShipMiddleName' => '', ];
 $m4is__4en6o = (int) m4is_ho3l::m4is_btu_( 'CreditCard', (int) $m4is__4en6o, $m4is_mzcd );
 $m4is_jrq3 = (bool) ( $m4is__4en6o > 0 );
 } if ( $m4is__4en6o > 0 ) { self::$m4is_j_xo4w->validateCard( (int) $m4is__4en6o);
 } delete_transient( m4is_akcfiz::m4is_on_q( $m4is_e2kg ) );
 if ( $m4is__4en6o ) {  if ( $m4is_ay3s ) { $m4is__u5v = [ 'AutoCharge', 'CC1', 'ContactId', 'Id', 'MerchantAccountId', 'OriginatingOrderId', 'Status', 'SubscriptionPlanId', ];
 $m4is_jo8fb = [ 'ContactId' => $m4is_e2kg,   ];
 $m4is_y_38pw = 1000;
 $m4is_couz = 0;
 $m4is_hpn9y = m4is_ho3l::m4is_mlhu4( 'RecurringOrder', $m4is_y_38pw, $m4is_couz, $m4is_jo8fb, $m4is__u5v, 'Id', false );
 $m4is_wpvc = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'merchant_account_id' );
 foreach( $m4is_hpn9y as $m4is_ke_fr ) { if ( empty( $m4is_way_oq ) || in_array( $m4is_ke_fr['SubscriptionPlanId'], $m4is_way_oq ) ) { $m4is_yvy8[$m4is_ke_fr['Id']] = [ 'CC1' => isset( $m4is_ke_fr['CC1'] ) ? $m4is_ke_fr['CC1'] : 0, 'Id' => isset( $m4is_ke_fr['Id'] ) ? $m4is_ke_fr['Id'] : 0, 'MerchantAccountId' => empty( $m4is_ke_fr['MerchantAccountId'] ) ? $m4is_wpvc : $m4is_ke_fr['MerchantAccountId'], 'OriginatingOrderId' => isset( $m4is_ke_fr['OriginatingOrderId'] ) ? $m4is_ke_fr['OriginatingOrderId'] : 0, 'Status' => isset( $m4is_ke_fr['Status'] ) ? $m4is_ke_fr['Status'] : 0, 'ContactId' => isset( $m4is_ke_fr['ContactId'] ) ? $m4is_ke_fr['ContactId'] : 0, 'AutoCharge' => isset( $m4is_ke_fr['AutoCharge'] ) ? $m4is_ke_fr['AutoCharge'] : 0, ];
 } } unset($m4is_hpn9y, $m4is_ke_fr);
  if ( is_array( $m4is_yvy8 ) ) { foreach ( $m4is_yvy8 as $m4is_s2ge5 => $m4is_vky3j ) { $m4is_j4lxnf = false;
 $m4is_j4lxnf = $m4is_j4lxnf || $m4is_vky3j['Status'] !== 'Active';
 $m4is_j4lxnf = $m4is_j4lxnf || $m4is_vky3j['CC1'] == $m4is__4en6o;
 if ( ! $m4is_j4lxnf ) { $m4is_j5sy07 = (int) $m4is_vky3j['Id'];
 $m4is__xn_jt = [ 'CC1' => (int) $m4is__4en6o, 'MerchantAccountId' => (int) $m4is_vky3j['MerchantAccountId'],  'AutoCharge' => 1, ];
 m4is_ho3l::m4is_btu_( 'RecurringOrder', $m4is_j5sy07, $m4is__xn_jt );
 } } } unset($m4is_vky3j, $m4is__xn_jt, $m4is__u5v, $m4is_jo8fb, $m4is_s2ge5);
 }   if ( $m4is_fd39g ) { if ( $m4is_fyf80 ) echo 'Starting Backcharge<br>';
 $m4is_wpvc = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'merchant_account_id' );
 $m4is_craco = self::$m4is_bnd6ti->m4is_ow9yjk( $m4is_e2kg, false, true, true );
  $m4is_ocurf_ = is_array( $m4is_craco ) ? count( $m4is_craco ) : 0;
  $m4is__u5v = [ 'Id', 'JobRecurringId', ];
 $m4is_jo8fb = [ 'ContactId' => (int) $m4is_e2kg, ];
 $m4is_y_38pw = 1000;
 $m4is_couz = 0;
 $m4is_hpn9y = m4is_ho3l::m4is_mg4uyc( 'Job', $m4is_y_38pw, $m4is_couz, $m4is_jo8fb, $m4is__u5v );
 $m4is_yq74pt = [];
 if ( $m4is_yh5y ) { error_log( 'Memberium Credit Card Update - found ' . count($m4is_craco) . ' orders' );
 } foreach( $m4is_hpn9y as $m4is_ke_fr ) { $m4is_yq74pt[$m4is_ke_fr['Id']] = isset( $m4is_ke_fr['JobRecurringId'] ) ? $m4is_ke_fr['JobRecurringId'] : 0;
 } unset($m4is_hpn9y, $m4is_ke_fr);
 $m4is__ql9vk = [];
 $m4is_b7_n = count( $m4is_yq74pt );
 if ( $m4is_fyf80 ) { echo "Parameters: <pre>", print_r( $m4is_rbwn1z, true ), "</pre>";
 echo "Default Merchant ID: {$m4is_wpvc}<br>";
 echo "Unpaid Invoices Found: {$m4is_ocurf_}<br>";
 echo "Unpaid Jobs Found: {$m4is_b7_n}<br>";
 echo "Invoices: <pre>", print_r( $m4is_craco, true ), "</pre>";
 echo "Jobs: <pre>", print_r( $m4is_yq74pt, true ), "</pre>";
 } if ( $m4is_ocurf_ ) { foreach( $m4is_craco as $m4is_etwy_q ) { if ( $m4is_yh5y ) { } if ( ( $m4is_etwy_q['TotalPaid'] < $m4is_etwy_q['TotalDue'] ) and ( $m4is_etwy_q['PayStatus'] == '0' ) and ( $m4is_etwy_q['TotalDue'] > 0 ) ) { $m4is_izp89g = $m4is_etwy_q['Id'];
 $m4is_xsiutn = $m4is_etwy_q['JobId'];
 if ( isset( $m4is_yq74pt[$m4is_xsiutn] ) ) { $m4is_z6x4yi = $m4is_yq74pt[$m4is_xsiutn];
 if ( ! empty( $m4is_yvy8[$m4is_z6x4yi] ) && $m4is_yvy8[$m4is_z6x4yi]['Status'] == 'Active' ) { $m4is__ql9vk[$m4is_izp89g] = [ 'invoice_id' => (int) $m4is_izp89g, 'recurringorder_id' => (int) $m4is_z6x4yi, 'merchant_id' => $m4is_yvy8[$m4is_z6x4yi]['MerchantAccountId'] ? (int) $m4is_yvy8[$m4is_z6x4yi]['MerchantAccountId'] : 0, 'total_due' => $m4is_etwy_q['TotalDue'], ];
 } elseif ( isset( $m4is_yq74pt[$m4is_xsiutn] ) && $m4is_yq74pt[$m4is_xsiutn] == 0) { $m4is__ql9vk[$m4is_izp89g] = [ 'invoice_id' => (int) $m4is_izp89g, 'recurringorder_id' => 0, 'merchant_id' => $m4is_wpvc, 'total_due' => $m4is_etwy_q['TotalDue'], ];
 } } } } }  usort($m4is__ql9vk, function($a, $b) { if ( $a['total_due'] > $b['total_due'] ) return -1;
 if ( $a['total_due'] < $b['total_due'] ) return 1;
 if ( $a['invoice_id'] < $b['invoice_id'] ) return -1;
 if ( $a['invoice_id'] > $b['invoice_id'] ) return 1;
 return 0;
 });
 if ( $m4is_fyf80 ) { echo "elv_invoices: <pre>", print_r( $m4is_craco, true ), "</pre>";
 echo "elv_items: <pre>", print_r( $m4is__ql9vk, true ), "</pre>";
 }  foreach( $m4is__ql9vk as $m4is_f852 ) { if ( $m4is_f852['merchant_id'] ) { $m4is_oa_z = self::$m4is_j_xo4w->chargeInvoice( $m4is_f852['invoice_id'], 'Updated Credit Card Back Charge', (int) $m4is__4en6o, $m4is_f852['merchant_id'], false );
 if ( is_string( $m4is_oa_z ) ) { error_log( "Memberium (" . __LINE__ . ' ' . __FUNCTION__ . "):  Error Charging Invoice ID {$m4is_f852['invoice_id']} - {$m4is_oa_z}" );
 } } else { error_log( "Memberium (" . __LINE__ . ' ' . __FUNCTION__ . "):  Error Charging Invoice ID {$m4is_f852['invoice_id']} - No Merchant ID" );
 } } }  } } if ($m4is_jrq3) { self::$m4is_bnd6ti->m4is_u86vzq( $m4is_rbwn1z['action_ids'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_cqe6_( $m4is_rbwn1z['goals'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_rbwn1z['tag_ids'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_m3vz( $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_leu58( $m4is_e2kg );
 m4is_akcfiz::m4is__7phr_( $m4is_e2kg );
 $m4is_b5kaz0 = $m4is_ipou;
 } else { $m4is_b5kaz0 = $m4is_ab9c;
 } if (! empty( $m4is_b5kaz0 ) ) { m4is_aoxw::m4is_g7bv();
 wp_redirect( $m4is_b5kaz0 );
 exit;
 } } static 
function m4is_mq2r() { $m4is_l6tf_ = 'memb_registration_form';
 if ( ! wp_verify_nonce( $_POST['_wpnonce'], $_POST['params'] ) ) { wp_die( _x( 'Invalid Registration Submission', $m4is_l6tf_, self::$m4is_n3zlk ) );
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['params'] ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 } m4is_aoxw::m4is_djr4nd();
 global $wpdb;
  $m4is_x5wxyr = [ '_wp_http_referer', '_wpnonce', 'memb_form_type', 'params', 'signature' ];
 $m4is_jadl06 = false;
 $m4is_aocm8x = [];
 $m4is_vh8an = false;
 $m4is_i395rp = true;
 $m4is__8htld = false;
 $m4is_nv29_ = [];
 $m4is_dg3p95 = false;
 $m4is_dcf_7 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'password_field' );
 $m4is_kwrd = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'min_password_length' );
 $m4is_powbq2 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'username_field' );
 $m4is_r36qyu = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'local_auth_only' );
 $m4is_ahza8 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'recaptcha_v2' );
 $m4is_p_81 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'recaptcha_v2_secret_key', '' );
 $m4is_c2ah = apply_filters( 'memberium/registration_form/post/pre', $_POST );
 $m4is_gqid = unserialize( base64_decode( $m4is_c2ah['params'] ) );
 $m4is_r10h = array_filter( explode( ',', $m4is_gqid['date_fields'] ) );
 $m4is_wk1bir = array_filter( explode( ',', $m4is_gqid['required_fields'] ) );
 $m4is_v_g1v6 = ! $m4is_r36qyu;
 $m4is_xsocn = $m4is_dcf_7 . '_confirmation';
  if ( $m4is_gqid['remove_accents'] ) { foreach( $m4is_c2ah as $m4is_c5zg=>$m4is_g0wy ) { $m4is_c2ah[$m4is_c5zg] = trim( remove_accents( $m4is_g0wy ) );
 } }  if ( $m4is_gqid['recaptcha'] && isset( $m4is_c2ah['g-recaptcha-response'] ) && $m4is_ahza8 ) { $m4is__w0j4 = $m4is_c2ah['g-recaptcha-response'];
 $m4is_imdo6 = sprintf( 'https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s', $m4is_p_81, $m4is__w0j4 );
 $m4is_d71ub = wp_remote_get( $m4is_imdo6 );
 $m4is_d71ub = wp_remote_retrieve_body( $m4is_d71ub );
 $m4is_x1g6 = json_decode( $m4is_d71ub );
 if ( ! $m4is_x1g6->success ) { $m4is_jadl06 = true;
 $m4is_aocm8x[] = _x( 'You need to successfully pass the CAPTCHA Test to register.', 'memb_registration_form', self::$m4is_n3zlk );
 } }  if ( ! isset( $m4is_c2ah[$m4is_dcf_7] ) && ! isset( $m4is_c2ah[$m4is_xsocn] ) ) { $m4is_c2ah[$m4is_xsocn] = $m4is_c2ah[$m4is_dcf_7] = self::$m4is_bnd6ti->m4is_e9m0g();
 $m4is_v_g1v6 = true;
 $m4is_dg3p95 = true;
 }  if ( is_array( $m4is_wk1bir ) ) { foreach ( $m4is_wk1bir as $m4is_n9g7to ) { if ( ! isset( $m4is_c2ah[$m4is_n9g7to] ) ) { $m4is_i395rp = false;
 $m4is_jadl06 = true;
 $m4is_aocm8x[] = _x( 'You are missing required fields.', 'memb_registration_form', self::$m4is_n3zlk );
 } } }  if ( ! empty( $m4is_c2ah[$m4is_dcf_7] ) && strlen( $m4is_c2ah[$m4is_dcf_7]) < $m4is_kwrd ) { $m4is_jadl06 = true;
 $m4is_aocm8x[] = sprintf( _x( 'Your password must be at least %d characters long.', 'memb_registration_form', self::$m4is_n3zlk ), $m4is_kwrd );
 }  if ( strpos( $m4is_c2ah[$m4is_dcf_7], '\\' ) !== false ) { $m4is_jadl06 = true;
 $m4is_aocm8x[] = _x( 'You may not use the backslash (\\) character in passwords.', 'memb_registration_form', self::$m4is_n3zlk );
 }  if ( is_array( $m4is_c2ah ) ) { foreach ( $m4is_c2ah as $m4is_s2ge5 => $m4is_w_o7al ) { $m4is_omk1cu = $m4is_s2ge5 . '_confirmation';
 if ( isset( $m4is_c2ah[$m4is_omk1cu] ) && $m4is_c2ah[$m4is_s2ge5] <> $m4is_c2ah[$m4is_omk1cu] ) { $m4is_jadl06 = true;
 $m4is_aocm8x[] = _x( 'Your confirmed fields do not match.', 'memb_registration_form', self::$m4is_n3zlk );
 } } unset( $m4is_s2ge5, $m4is_w_o7al, $m4is_q3y8o1 );
 } $m4is_c2ah[$m4is_powbq2] = stripslashes( $m4is_c2ah[$m4is_powbq2] );
 $m4is_vh8an = self::m4is_q_e1z9( $m4is_c2ah[$m4is_powbq2] );
  if ( ! $m4is_vh8an ) { $m4is__u5v = [ $m4is_dcf_7, 'Groups' ];
 $m4is_jo8fb = [ $m4is_powbq2 => $m4is_c2ah[$m4is_powbq2] ];
 $m4is_zcy_g = m4is_ho3l::m4is_mg4uyc( 'Contact', 1000, 0, $m4is_jo8fb, $m4is__u5v );
 if ( is_array( $m4is_zcy_g ) ) { foreach ( $m4is_zcy_g as $m4is_p9r_8e ) { if ( ! empty( $m4is_p9r_8e[$m4is_dcf_7] ) ) { $m4is_vh8an = true;
 } } } }  if ( ! $m4is_vh8an && $m4is_powbq2 <> 'Email' && isset( $m4is_c2ah['Email'] ) ) { $m4is__u5v = [ $m4is_dcf_7, 'Groups', 'Id', 'Email' ];
 $m4is_jo8fb = [ 'Email' => $m4is_c2ah[$m4is_powbq2] ];
 $m4is_zcy_g = m4is_ho3l::m4is_mg4uyc( 'Contact', 1000, 0, $m4is_jo8fb, $m4is__u5v );
 if ( is_array( $m4is_zcy_g ) ) { foreach ( $m4is_zcy_g as $m4is_p9r_8e ) { if ( $m4is_p9r_8e[$m4is_dcf_7] > '' ) { $m4is_vh8an = true;
 } }  } }  if ( $m4is_vh8an ) { $m4is_jadl06 = true;
 $m4is_aocm8x[] = _x( 'That username is not available.', 'memb_registration_form', self::$m4is_n3zlk );
 }  if ( ! $m4is_jadl06 && ! $m4is_vh8an ) { if ( empty( $m4is_c2ah[$m4is_dcf_7] ) ) { $m4is_c2ah[$m4is_dcf_7] = self::$m4is_bnd6ti->m4is_e9m0g();
 $m4is_dg3p95 = true;
 $m4is_v_g1v6 = true;
 } $m4is_dbcyjz = m4is_ho3l::m4is_kjedy2('Contact', true);
 $m4is_p9r_8e = [];
 foreach ( $m4is_c2ah as $m4is_s2ge5 => $m4is_w_o7al ) { if ( in_array( $m4is_s2ge5, $m4is_r10h ) ) { $m4is_w_o7al = date( 'Ymd\Th:i:s', strtotime( $m4is_w_o7al ) );
 } if ( in_array( $m4is_s2ge5, $m4is_dbcyjz ) ) { $m4is_p9r_8e[$m4is_s2ge5] = $m4is_w_o7al;
 } }  if ( $m4is_r36qyu == true && $m4is_v_g1v6 == false ) { unset( $m4is_p9r_8e[$m4is_dcf_7] );
 } if ( $m4is_gqid['pass_password'] == false ) { $m4is_x5wxyr[] = $m4is_dcf_7;
 $m4is_x5wxyr[] = $m4is_xsocn;
 }  if ( is_array( $m4is_p9r_8e ) && ! empty( $m4is_p9r_8e ) && $m4is_gqid['pass_fields'] ) { foreach ( $m4is_p9r_8e as $m4is_s2ge5 => $m4is_w_o7al ) { if ( ! in_array( $m4is_s2ge5, $m4is_x5wxyr ) ) { $m4is_qqwj1c = '';
 if ( $m4is_gqid['inf_fields'] ) { $m4is_s2ge5 = substr( $m4is_s2ge5, 0, 1 ) == '_' ? 'inf_custom' . $m4is_s2ge5 : 'inf_field_' . $m4is_s2ge5;
 } $m4is_nv29_[$m4is_s2ge5] = urlencode( $m4is_w_o7al );
 } } foreach ( $m4is_c2ah as $m4is_s2ge5 => $m4is_w_o7al ) { if ( ! isset( $m4is_p9r_8e[$m4is_s2ge5] ) ) { if ( ! in_array( $m4is_s2ge5, $m4is_x5wxyr ) ) { $m4is_nv29_[$m4is_s2ge5] = urlencode( $m4is_w_o7al );
 } } } }  if ( ! empty( $m4is_p9r_8e ) ) {  $m4is_e2kg = m4is_bnrdbo::m4is_klk1gy( $m4is_p9r_8e );
 $m4is__g7jpz = _x( 'Membership Signup New User', 'memb_registration_form', self::$m4is_n3zlk );
 m4is_bnrdbo::m4is_cseh( $m4is_e2kg, $m4is_p9r_8e );
 $m4is_u374_ = ['Email', 'EmailAddress2', 'EmailAddress3'];
 foreach( $m4is_u374_ as $m4is_sd3n ) { if ( ! empty( $m4is_p9r_8e[$m4is_sd3n] ) ) { $m4is_p9r_8e[$m4is_sd3n] = sanitize_email( $m4is_p9r_8e[$m4is_sd3n] );
 m4is_bnrdbo::m4is_xj2eb( $m4is_p9r_8e[$m4is_sd3n], $m4is__g7jpz );
 } } if ( $m4is_e2kg ) { self::$m4is_bnd6ti->m4is_cqe6_( $m4is_gqid['goal'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_gqid['tagids'], $m4is_e2kg );
 self::$m4is_bnd6ti->m4is_u86vzq( $m4is_gqid['action_id'], $m4is_e2kg );
 $rows = self::$m4is_bnd6ti->m4is_leu58( $m4is_e2kg );
 $user_id = self::$m4is_bnd6ti->m4is_b34y( $m4is_e2kg, $m4is_c2ah[$m4is_dcf_7] );
  if ( $m4is_gqid['autologin'] ) { $m4is_x0_hk = get_user_by( 'id', $user_id );
 $m4is_euyfd = $m4is_p9r_8e[$m4is_powbq2];
 if ( ! empty( $m4is_gqid['success_url'] ) ) { self::$m4is_bh12zy->m4is_bs9z4( add_query_arg( $m4is_nv29_, $m4is_gqid['success_url'] ) );
 } wp_set_auth_cookie( $user_id );
 wp_set_current_user( $user_id );
 m4is_ypvg9::m4is__tje( $m4is_euyfd );
 do_action( 'wp_login', $m4is_euyfd, $m4is_x0_hk );
 self::$m4is_bh12zy->m4is_q06g4q( $m4is_p9r_8e, $user_id );
 self::$m4is_bh12zy->m4is_dnqd_();
 } } else { $m4is_jadl06 = true;
 } } }  if ( $m4is_jadl06 || $m4is_vh8an ) { $m4is_b5kaz0 = $m4is_gqid['failure_url'];
 } else { $m4is_b5kaz0 = $m4is_gqid['success_url'];
 }  if ( ! empty( $m4is_aocm8x ) ) { $_SESSION['error_message'] = $m4is_aocm8x;
 }  if ( ! empty( $m4is_b5kaz0 ) ) { m4is_aoxw::m4is_g7bv();
 $m4is_b5kaz0 = add_query_arg( $m4is_nv29_, $m4is_b5kaz0 ) ;
 wp_redirect( $m4is_b5kaz0 );
 exit;
 } } static 
function m4is_e0iq() { if ( ! m4is_u68pu::m4is_u6mkaw() ) { return;
 } $m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 $m4is_j_xo4w = self::$m4is_bnd6ti->m4is_zw_n();
 $m4is_bh12zy = m4is_w0enbm::m4is_e5l8a9();
 $m4is_ndufnm = base64_decode( $_POST['tag_id'] );
 m4is_aoxw::m4is_djr4nd();
 if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['template_id'] . $m4is_ndufnm ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', 'memb_send_password', self::$m4is_n3zlk ) );
 exit;
 } self::$m4is_bh12zy->m4is_mhea( 'There was an error Looking up that account.' );
 $m4is_haon5 = true;
 $m4is_su4qk = (int) $_POST['form_id'];
 $m4is_qhma = (int) $_POST['template_id'];
 $m4is_fliw = strtolower(trim($_POST['email']) );
 $m4is_h_9x = base64_decode($_POST['successurl']);
 $m4is_xy7m = base64_decode($_POST['failureurl']);
 $m4is_ndufnm = base64_decode($_POST['tag_id']);
 $m4is__8htld = false;
 $m4is_odlv = false;
 $m4is_dcf_7 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'password_field' );
 $m4is_r36qyu = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'local_auth_only' );
 if ( trim( $_POST['email'] ) == '' ) { self::$m4is_bh12zy->m4is_mhea('You must submit an email address.');
 return;
 } $m4is_x0_hk = get_user_by('email', $m4is_fliw);
 if ($m4is_x0_hk) { $m4is_e2kg = m4is_bnrdbo::m4is_ltwpgs($m4is_x0_hk->ID);
 if (! $m4is_e2kg) { self::$m4is_bnd6ti->m4is_j30vf1( $m4is_fliw );
 $m4is_e2kg = m4is_bnrdbo::m4is_ltwpgs($m4is_x0_hk->ID);
 } if ($m4is_e2kg) { $m4is_p9r_8e = m4is_bnrdbo::m4is_yvnol($m4is_e2kg);
 } } if (empty($m4is_p9r_8e) ) { self::$m4is_bnd6ti->m4is_j30vf1($m4is_fliw);
 $m4is_z59dj = m4is_bnrdbo::m4is_nsbvg($m4is_fliw);
 if (is_array($m4is_z59dj) ) { $m4is_e2kg = $m4is_z59dj[0];
 } } if ( empty( $m4is_r36qyu ) ) { if ($m4is_e2kg > 0) { if ( isset( $m4is_p9r_8e[$m4is_dcf_7] ) && $m4is_p9r_8e[$m4is_dcf_7] == 'PASSWORD_PLACEHOLDER') { $m4is_e82v = self::$m4is_bnd6ti->m4is_e9m0g();
 $m4is_p9r_8e[$m4is_dcf_7] = $m4is_e82v;
 self::$m4is_bnd6ti->m4is_dhpr($m4is_p9r_8e);
 m4is_bnrdbo::m4is_cseh($m4is_e2kg, [$m4is_dcf_7 => $m4is_e82v]);
 self::$m4is_bnd6ti->m4is_b34y( $m4is_e2kg );
 } } } if ( $m4is_e2kg > 0 ) { if ( $m4is_ndufnm > 0 ) { self::$m4is_bnd6ti->m4is_tcle75( $m4is_ndufnm, $m4is_e2kg );
 $m4is__8htld = true;
 $m4is_odlv = true;
 } } if ($m4is_qhma) { if ($m4is_e2kg > 0) { $m4is_smz4bo = [$m4is_e2kg];
 } if ( ! empty( $m4is_smz4bo) ) { $m4is_zg8z = $m4is_j_xo4w->sendTemplate( $m4is_smz4bo, $m4is_qhma );
 $m4is__8htld = true;
 } } else { if ( ! $m4is_odlv ) { if (! empty( $m4is_p9r_8e ) ) { $m4is_j485e = empty( $m4is_p9r_8e[$m4is_dcf_7] ) ? '' : $m4is_p9r_8e[$m4is_dcf_7];
 $m4is_ujq5r1 = empty( $m4is_p9r_8e['FirstName'] ) ? '' : $m4is_p9r_8e['FirstName'];
 $m4is_st5p4v = get_bloginfo( 'admin_email' );
 $m4is_ljt4ua = $m4is_fliw;
 $m4is_d6ts = sprintf( _x( 'Your Password for %s', 'memb_send_password', self::$m4is_n3zlk ), get_bloginfo( 'name' ) );
 $m4is_wbgl5s = sprintf( _x( "<html><body><p>Dear %s</p>\n\n<p>Your password is: %s\n\n</p><p>- %s\n</p></body></html>", 'memb_send_password', self::$m4is_n3zlk ), $m4is_ujq5r1, $m4is_j485e, get_bloginfo('name') );
 $m4is_d6ts = apply_filters( 'memberium/email/send_password/subject', $m4is_d6ts, $m4is_p9r_8e, $m4is_x0_hk );
 $m4is_wbgl5s = apply_filters( 'memberium/email/send_password/message', $m4is_wbgl5s, $m4is_p9r_8e, $m4is_j485e, $m4is_x0_hk );
 $m4is_ljt4ua = apply_filters( 'memberium/email/send_password/to', $m4is_ljt4ua );
 $m4is_st5p4v = apply_filters( 'memberium/email/send_password/from', $m4is_st5p4v );
 $m4is__8htld = true;
 $m4is_bvrdo = function() { return 'text/html';
 };
 add_filter( 'wp_mail_content_type', $m4is_bvrdo );
 wp_mail( $m4is_ljt4ua, $m4is_d6ts, $m4is_wbgl5s );
 remove_filter( 'wp_mail_content_type', $m4is_bvrdo );
 } else { self::$m4is_bh12zy->m4is_mhea('Account not found.');
 } } } if ($m4is__8htld) { $m4is_bh12zy->m4is_mhea(_x('Your password has been emailed to you.  Please be sure to check your spam folder.', 'memb_send_password', self::$m4is_n3zlk ) );
 if (! empty($m4is_h_9x) ) { m4is_aoxw::m4is_g7bv();
 wp_redirect($m4is_h_9x);
 exit;
 } } if ( ! $m4is__8htld ) { if ( ! empty( $m4is_xy7m ) ) { m4is_aoxw::m4is_g7bv();
 wp_redirect( $m4is_xy7m );
 exit;
 } } self::$m4is_bnd6ti->m4is_m3vz();
 } static 
function m4is_v2uwhg() { global $wpdb;
 $m4is_l6tf_ = 'memb_registration_form';
 if ( ! wp_verify_nonce( $_POST['_wpnonce'], $_POST['params'] ) ) { wp_die( 'Invalid Update Form Submission' );
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['params'] ) ) { wp_die( 'Security Check Failed - Signature Validation Error' );
 exit;
 } m4is_aoxw::m4is_djr4nd();
  $m4is_aocm8x = [];
 $m4is_jadl06 = false;
 $m4is_vh8an = false;
 $m4is_i395rp = true;
 $m4is__8htld = false;
 $m4is_dcf_7 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'password_field' );
 $m4is_powbq2 = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'username_field' );
 $m4is_gqid = unserialize( base64_decode( $_POST['params'] ) );
 $m4is_e2kg = (int) $m4is_gqid['contact_id'];
 $m4is_z5rzd = m4is_ho3l::m4is_o6zj4m( -1 );
 if ( self::$m4is_bnd6ti->m4is_dpuy9() <> $m4is_e2kg ) { wp_die('Security Check Failed - Signature Validation Error');
 exit;
 }  foreach( $m4is_z5rzd as $m4is_iqdn => $m4is_o0tyuw ) { if ( isset( $_POST[$m4is_iqdn] ) ) { $m4is_w_o7al = $_POST[$m4is_iqdn];
 if ( $m4is_o0tyuw == 5 ) {  if ( strlen( $m4is_w_o7al ) < 4 ) { $m4is_w_o7al = strtoupper( $m4is_w_o7al );
 } } elseif ( $m4is_o0tyuw == 13 || $m4is_o0tyuw == 14 ) {  $m4is_lq7v = strtotime( $m4is_w_o7al );
 if ( $m4is_lq7v > 0 ) { $m4is_w_o7al = date( 'Ymd\TH:i:s', strtotime( $m4is_w_o7al ) );
 } else { unset( $_POST[$m4is_iqdn] );
 } } elseif ( $m4is_o0tyuw == 17 || $m4is_o0tyuw == 20 || $m4is_o0tyuw == 23 ) {  if ( is_array( $m4is_w_o7al) ) { $m4is_w_o7al = implode( ',', $m4is_w_o7al );
 } } elseif ( $m4is_o0tyuw == 19 ) {  if ( strpos( $m4is_w_o7al, '@' ) !== false ) { $m4is_w_o7al = strtolower( trim( $m4is_w_o7al ) );
 } else { $m4is_w_o7al = '';
 } } $_POST[$m4is_iqdn] = stripslashes($m4is_w_o7al);
 } else { } }  if ( ! empty( $m4is_gqid['required_fields'] ) ) { $m4is_wk1bir = array_filter( explode( ',', $m4is_gqid['required_fields'] ) );
 if ( is_array( $m4is_wk1bir ) ) { foreach ( $m4is_wk1bir as $m4is_n9g7to ) { if ( ! isset( $_POST[$m4is_n9g7to] ) ) { $m4is_i395rp = false;
 $m4is_jadl06 = true;
 $m4is_aocm8x[] = 'You are missing required fields.';
 } } } }  foreach ($_POST as $m4is_s2ge5 => $m4is_w_o7al) { if (isset($_POST[$m4is_s2ge5 . '_confirmation']) && $_POST[$m4is_s2ge5] <> $_POST[$m4is_s2ge5 . '_confirmation']) { $m4is_jadl06 = true;
 $m4is_aocm8x[] = 'Your confirmed fields do not match.';
 } }  if (! empty($m4is_gqid['date_fields']) ) { $m4is_r10h = explode(',', $m4is_gqid['date_fields']);
 if (is_array($m4is_r10h) ) { foreach($m4is_r10h as $m4is_lugsa) { if (isset($_POST[$m4is_lugsa]) ) { $m4is_lq7v = strtotime($_POST[$m4is_lugsa]);
 $_POST[$m4is_lugsa] = date('Ymd\TH:i:s', $m4is_lq7v);
 } } } }  if (! $m4is_jadl06) { $m4is_dbcyjz = m4is_ho3l::m4is_kjedy2('Contact');
 $m4is_p9r_8e = [];
 foreach ($_POST as $m4is_s2ge5 => $m4is_w_o7al) { if (in_array($m4is_s2ge5, $m4is_dbcyjz) ) { $m4is_p9r_8e[$m4is_s2ge5] = $m4is_w_o7al;
 } } if (! empty($m4is_p9r_8e) ) { m4is_bnrdbo::m4is_cseh($m4is_e2kg, $m4is_p9r_8e);
  if ($m4is_e2kg > 0) { if (! empty($m4is_gqid['goal']) ) { self::$m4is_bnd6ti->m4is_cqe6_($m4is_gqid['goal'], $m4is_e2kg);
 } if (! empty($m4is_gqid['tagids']) ) { self::$m4is_bnd6ti->m4is_tcle75($m4is_gqid['tagids'], $m4is_e2kg);
 } self::$m4is_bnd6ti->m4is_leu58($m4is_e2kg);
 $_SESSION = self::$m4is_bnd6ti->m4is_akz3();
   $m4is_onu8_4 = m4is_a8iaym::m4is_e_prox( m4is_a8iaym::CONTACT_FIELDS, m4is_a8iaym::EMAIL_TYPE);
 $m4is_onu8_4[] = 'Email';
 $m4is_onu8_4[] = 'EmailAddress2';
 $m4is_onu8_4[] = 'EmailAddress3';
 $m4is_hy9k = [];
 foreach($m4is_p9r_8e as $m4is_yxwn => $m4is_n6yjk9) { if (in_array($m4is_yxwn, $m4is_onu8_4) ) { if (! empty($m4is_n6yjk9) ) { $m4is_hy9k[] = strtolower(trim($m4is_n6yjk9) );
 } } } $m4is_hy9k = array_unique($m4is_hy9k);
 foreach($m4is_hy9k as $m4is_fliw) { m4is_bnrdbo::m4is_xj2eb($m4is_fliw, 'Memberium Update Form');
 } } else { $m4is_jadl06 = true;
 } } }  if ($m4is_jadl06 || $m4is_vh8an) { $m4is_b5kaz0 = $m4is_gqid['failure_url'];
 } else { $m4is_b5kaz0 = $m4is_gqid['success_url'];
 }   if (! empty($m4is_p9r_8e) && $m4is_gqid['pass_fields']) { $m4is__71f = (strpos($m4is_b5kaz0, '?') === false) ? '?' : '&';
 if ($m4is_e2kg > 0) { $m4is__71f .= 'id=' . $m4is_e2kg . '&';
 } foreach ($m4is_p9r_8e as $m4is_s2ge5 => $m4is_w_o7al) { if ($m4is_s2ge5 <> $m4is_dcf_7 || $m4is_gqid['pass_password'] == true) { $m4is__71f .= $m4is_s2ge5 . '=' . urlencode($m4is_w_o7al) . '&';
 } } } $m4is_b5kaz0 = trim($m4is_b5kaz0 . $m4is__71f, '&');
  if (! empty($m4is_aocm8x) ) { $_SESSION['error_message'] = $m4is_aocm8x;
 } if (! empty($m4is_b5kaz0) ) { session_write_close();
 m4is_aoxw::m4is_g7bv();
 wp_redirect($m4is_b5kaz0, 302, 'Memberium Update Form Redirect');
 exit;
 } } static 
function m4is_vbfq() { $m4is_bnd6ti = m4is_pms8y::m4is_e5l8a9();
 $m4is_j_xo4w = self::$m4is_bnd6ti->m4is_zw_n();
 if (! m4is_u68pu::m4is_u6mkaw() ) { return;
 } if ( ! self::$m4is_bnd6ti->m4is_dpuy9()) { return;
 } m4is_aoxw::m4is_djr4nd();
 if ( ! self::$m4is_bnd6ti->m4is_tjozx($_POST['signature'], $_POST['parameters']) ) { wp_die(_x('Security Check Failed - Signature Validation Error', 'memb_list_invoices', self::$m4is_n3zlk ) );
 exit;
 } $m4is_rbwn1z = unserialize(base64_decode($_POST['parameters']) );
 $m4is_c4lk = (int) $m4is_rbwn1z['invoice_id'];
 if (! wp_verify_nonce($_POST['_wpnonce'], 'memb_payinvoice_' . $m4is_c4lk) ) { wp_die(_x('Security Check Failed - Nonce Validation Error', 'memb_list_invoices', self::$m4is_n3zlk ) );
 exit;
 } $m4is_e2kg = (int) self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is__4en6o = (int) $_POST['creditcard_id'];
 $m4is_c4lk = (int) $m4is_rbwn1z['invoice_id'];
 $m4is_cxre = (int) $m4is_rbwn1z['merchant_id'];
 $m4is_ndufnm = $m4is_rbwn1z['tag_id'];
 $m4is_xf9b = $m4is_rbwn1z['goal'];
 $m4is_kzkrv1 = '';
 $m4is_craco = self::$m4is_bnd6ti->m4is_ow9yjk($m4is_e2kg, false, true);
 $m4is_etwy_q = isset($m4is_craco[$m4is_c4lk]) ? $m4is_craco[$m4is_c4lk] : [];
 $m4is_swtl3 = [ 'pay_action' => '', 'pay_goal' => '', ];
 $m4is_oa_z = $m4is_j_xo4w->chargeInvoice( $m4is_c4lk, _x('Memberium Customer Care', 'memb_list_invoices', self::$m4is_n3zlk ), $m4is__4en6o, $m4is_cxre, false);
 if (isset($m4is_oa_z['Successful']) && $m4is_oa_z['Successful']) { $m4is_kwf563 = self::$m4is_bnd6ti->m4is_crewgb( (int) $m4is_etwy_q['JobId']);
 $m4is_e_3pmx = self::$m4is_bnd6ti->m4is_oiewvu('ecommerce', 'actions');
 foreach($m4is_kwf563 as $m4is_j5sy07 => $m4is_qqec2k) { $m4is_oa_j2 = isset($m4is_e_3pmx[$m4is_qqec2k['SubscriptionPlanId']]) ? $m4is_e_3pmx[$m4is_qqec2k['SubscriptionPlanId']] : false;
 if ($m4is_oa_j2) { $m4is_swtl3['pay_action'] .= empty($m4is_oa_j2['pay_action']) ? '' : ',' . $m4is_oa_j2['pay_action'];
 $m4is_swtl3['pay_goal'] .= empty($m4is_oa_j2['pay_goal']) ? '' : ',' . $m4is_oa_j2['pay_goal'];
 } } foreach($m4is_swtl3 as $m4is_c5zg => $m4is_g0wy) { $m4is_swtl3[$m4is_c5zg] = trim($m4is_swtl3[$m4is_c5zg], ',');
 } $m4is_kzkrv1 = trim($m4is_kzkrv1 . ',' . $m4is_swtl3['pay_action'], ',');
 $m4is_xf9b = trim($m4is_xf9b . ',' . $m4is_swtl3['pay_goal'], ',');
 self::$m4is_bnd6ti->m4is_tcle75($m4is_ndufnm, $m4is_e2kg);
 self::$m4is_bnd6ti->m4is_u86vzq($m4is_kzkrv1, $m4is_e2kg);
 self::$m4is_bnd6ti->m4is_cqe6_($m4is_xf9b, $m4is_e2kg);
  $_SESSION['flash']['invoice_payment'] = $m4is_rbwn1z['success_msg'];
  delete_transient('Memberium::' . self::$m4is_zq0k . '::Invoices::' . $m4is_e2kg);
 delete_transient('Memberium::' . self::$m4is_zq0k . '::PayPlans::' . $m4is_e2kg);
 delete_transient('Memberium::' . self::$m4is_zq0k . '::PayPlanItems::' . $m4is_e2kg);
 m4is_aoxw::m4is_g7bv();
 wp_redirect($m4is_rbwn1z['redirect_url']);
 exit;
 } else { $_SESSION['flash']['invoice_payment'] = _x('Payment failed.', 'memb_list_invoices', self::$m4is_n3zlk );
 } } static 
function m4is_zr6q() { if (! m4is_u68pu::m4is_u6mkaw() ) { return;
 } if (! wp_verify_nonce($_POST['_wpnonce'], 'oneclick_sale_' . $_POST['form_id']) ) { wp_die(_x('Security Check Failed - Nonce Validation Error', 'memb_one_click_sale', self::$m4is_n3zlk ) );
 exit;
 } if (! self::$m4is_bnd6ti->m4is_tjozx($_POST['digital_signature'], $_POST['parameters']) ) { wp_die(_x('Security Check Failed - Signature Validation Error', 'memb_one_click_sale', self::$m4is_n3zlk ) );
 exit;
 } m4is_aoxw::m4is_djr4nd();
 $m4is__c1d = $m4is_rbwn1z['action_id'];
 $m4is_e2kg = self::$m4is_bnd6ti->m4is_dpuy9();
 $m4is_rbwn1z = unserialize(base64_decode($_POST['parameters']) );
 $m4is_ae8w = (int) $m4is_rbwn1z['order_id'];
 if ($m4is__c1d > '') { self::$m4is_bnd6ti->m4is_u86vzq($m4is__c1d, $m4is_e2kg);
 } } static 
function m4is_s1cdt8() { $m4is_l6tf_ = 'memb_change_email';
 if (! wp_verify_nonce($_POST['_wpnonce'], 'memb_email_change_' . $_POST['form_id']) ) { wp_die(_x('Security Check Failed - Nonce Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 exit;
 } if (! self::$m4is_bnd6ti->m4is_tjozx($_POST['signature'], $_POST['actions']) ) { wp_die(_x('Security Check Failed - Signature Validation Error', $m4is_l6tf_, self::$m4is_n3zlk ) );
 exit;
 } m4is_aoxw::m4is_djr4nd();
 if ($_POST['email1'] <> $_POST['email2']) { $_SESSION['memb_flash']['email_change_message'] = '<p>' . _x("Your new email addresses don't match.", 'memb_change_email', self::$m4is_n3zlk ) . '</p>';
 return;
 } if ($_POST['email1'] == m4is_wbc8os::m4is_sfnmc('email') ) { $_SESSION['memb_flash']['email_change_message'] = '<p>' . _x('Your email address is already ', 'memb_change_email', self::$m4is_n3zlk ) . $_POST['email1'] . '</p>';
 return;
 } $_POST['email1'] = stripslashes($_POST['email1']);
 $m4is_oa_j2 = unserialize(base64_decode($_POST['actions']) );
 $m4is_ngaqxl = get_user_by('email', $_POST['email1']);
 if ($m4is_ngaqxl) { $_SESSION['memb_flash']['email_change_message'] = '<p>' . _x('That email address is already used on another member.', 'memb_change_email', self::$m4is_n3zlk ) . '</p>';
 return;
 }  $m4is_k4yeul = [ 'email' => $_POST['email1'], 'return' => 'contact_count', ];
 $m4is_k8uzp = self::$m4is_bnd6ti->m4is_j30vf1($m4is_k4yeul);
 if (! empty($m4is_k8uzp) ) { $_SESSION['memb_flash']['email_change_message'] = '<p>' . _x('That email address is already on our list.', 'memb_change_email', self::$m4is_n3zlk ) . '</p>';
 return;
 } $m4is_ig9p6 = (int) get_current_user_id();
 $m4is_e2kg = m4is_bnrdbo::m4is_ltwpgs($m4is_ig9p6);
 $m4is_oa_z = false;
 if ($m4is_e2kg) { $m4is_oa_z = self::$m4is_bnd6ti->m4is_az3tn8( $m4is_ig9p6, $_POST['email1'], $m4is_e2kg );
  } if ($m4is_oa_z) { $_SESSION['memb_flash']['email_change_message'] = '<p>' . _x('Your email address has been changed to', 'memb_change_email', self::$m4is_n3zlk ) . ' ' . $_POST['email1'] . '</p>';
  if (! empty($m4is_oa_j2['actionset_id']) ) { self::$m4is_bnd6ti->m4is_u86vzq( $m4is_oa_j2['actionset_id'] );
 } if (! empty($m4is_oa_j2['goal']) ) { self::$m4is_bnd6ti->m4is_cqe6_( $m4is_oa_j2['goal'] );
 } self::$m4is_bnd6ti->m4is_nekv();
 wp_clear_auth_cookie();
 $_SESSION = m4is_pms8y::m4is_e5l8a9()->m4is_akz3($m4is_ig9p6);
 wp_set_current_user($m4is_ig9p6);
 wp_set_auth_cookie($m4is_ig9p6, true, false);
 if (! empty($m4is_oa_j2['success_url']) ){ wp_redirect($m4is_oa_j2['success_url']);
 exit;
 } if ( ! empty($_SERVER['REQUEST_URI']) ) { wp_redirect( $_SERVER['REQUEST_URI'] );
 exit;
 } return;
 } else { $_SESSION['flash']['email_change_message'] = '<p>Your email address could not be changed to ' . $_POST['email1'] . '</p>';
 if (! empty($m4is_oa_j2['failure_url']) ){ wp_redirect($m4is_oa_j2['failure_url']);
 exit;
 } } } static 
function m4is_rhcrdb() { if ( self::$m4is_i0hu7m) { return;
 } if ( ! is_user_logged_in() ) { return;
 } if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'password_change_' . $_POST['form_id'] . $_POST['parameters'] ) ) { wp_die( _x( 'Security Check Failed - Nonce Validation Error', 'memb_change_password', self::$m4is_n3zlk ) );
 exit;
 } if ( ! self::$m4is_bnd6ti->m4is_tjozx( $_POST['signature'], $_POST['parameters'] ) ) { wp_die( _x( 'Security Check Failed - Signature Validation Error', 'memb_change_password', self::$m4is_n3zlk ) );
 exit;
 } m4is_aoxw::m4is_djr4nd();
 $m4is_ab0m = 'memb_change_password';
 $m4is_haon5 = true;
 $m4is_bh12zy = m4is_w0enbm::m4is_e5l8a9();
 $m4is_kwrd = self::$m4is_bnd6ti->m4is_oiewvu( 'settings', 'min_password_length' );
 $m4is_ig9p6 = get_current_user_id();
 $m4is_rbwn1z = unserialize( base64_decode( $_POST['parameters'] ) );
 $m4is_j485e = stripslashes( $_POST['password1'] );
 $m4is_su4qk = isset( $_POST['form_id'] ) ? (int) $_POST['form_id'] : 0;
 $m4is_xf9b = isset( $m4is_rbwn1z['goal'] ) ? $m4is_rbwn1z['goal'] : '';
 $m4is_x25z14 = isset( $m4is_rbwn1z['tagids'] ) ? $m4is_rbwn1z['tagids'] : '';
 $m4is_rrny = isset( $m4is_rbwn1z['actionset_id'] ) ? $m4is_rbwn1z['actionset_id'] : '';
 $m4is_b5kaz0 = isset( $m4is_rbwn1z['redirect_url'] ) ? $m4is_rbwn1z['redirect_url'] : '';
 $m4is_dudl27 = isset( $m4is_rbwn1z['confirm_template_id'] ) ? (int) $m4is_rbwn1z['confirm_template_id'] : 0;
 $m4is_h_9x = isset( $m4is_rbwn1z['successurl'] ) ? $m4is_rbwn1z['successurl'] : '';
 if ( ! $m4is_rbwn1z['contact_id']) { $m4is_bh12zy->m4is_mhea( _x( 'You are not an Keap User.', $m4is_ab0m, self::$m4is_n3zlk ) );
 return;
 } if ( empty( $m4is_j485e ) ) { $m4is_bh12zy->m4is_mhea( _x('You cannot set your password to an Empty Password.', $m4is_ab0m, self::$m4is_n3zlk ) );
 return;
 } if ( strpos( $m4is_j485e, '\\' ) !== false ) { $m4is_bh12zy->m4is_mhea( _x( 'The backslash character may not be used in passwords.', $m4is_ab0m, self::$m4is_n3zlk ) );
 return;
 } if (strlen($m4is_j485e) < $m4is_kwrd) { $m4is_bh12zy->m4is_mhea( sprintf( _x( 'Your password must be at least %d characters long.', $m4is_ab0m, self::$m4is_n3zlk ), $m4is_kwrd) );
 return;
 } if ( ! empty( $m4is_j485e ) && $m4is_j485e != $_POST['password2'] ) { $m4is_bh12zy->m4is_mhea( _x('The passwords entered do not match.', $m4is_ab0m, self::$m4is_n3zlk ) );
 return;
 } $m4is_b5kaz0 = empty( $m4is_b5kaz0 ) ? $_SERVER['REQUEST_URI'] : $m4is_b5kaz0;
 $m4is__8htld = self::$m4is_bnd6ti->m4is_a1w0q( $m4is_j485e );
 if ( $m4is__8htld ) { $m4is_bh12zy->m4is_mhea( _x( 'Password Changed Successfully.', $m4is_ab0m, self::$m4is_n3zlk ) );
 self::$m4is_bnd6ti->m4is_tcle75( $m4is_x25z14 );
 self::$m4is_bnd6ti->m4is_u86vzq( $m4is_rrny );
 self::$m4is_bnd6ti->m4is_cqe6_( $m4is_xf9b );
 $m4is_b5kaz0 = empty( $m4is_h_9x ) ? $m4is_b5kaz0 : $m4is_h_9x;
 $m4is_b5kaz0 = remove_query_arg( ['passwordchange'], $m4is_b5kaz0 );
 $m4is_b5kaz0 = add_query_arg( ['passwordchange' => 'success'], $m4is_b5kaz0 );
 if ( $m4is_dudl27 > 0 ) { self::$m4is_j_xo4w->sendTemplate( [$m4is_e2kg], $m4is_dudl27 );
 } if ( ! empty( $m4is_b5kaz0 ) ) { session_write_close();
 wp_redirect( $m4is_b5kaz0, 302, 'Memberium Password Change Redirect' );
 exit;
 } } else { self::$m4is_bh12zy->m4is_mhea( _x( 'Password Change Failed.', $m4is_ab0m, self::$m4is_n3zlk ) );
 $m4is_b5kaz0 = add_query_arg( ['passwordchange' => 'failed'], $m4is_b5kaz0 );
 } session_write_close();
 nocache_headers();
 if ( ! empty( $m4is_b5kaz0 ) ) { wp_redirect( $m4is_b5kaz0, 302, 'Memberium Password Change Redirect' );
 exit;
 } }  static 
function m4is_o73ps0() { if ( self::$m4is_i0hu7m ) { return;
 } m4is_aoxw::m4is_djr4nd();
 if ( is_user_logged_in() ) { return;
 } $m4is_fliw = sanitize_email( trim( wp_unslash( $_POST['user_login'] ) ) );
 if ( empty( $m4is_fliw ) ) { return;
 } $m4is_x0_hk = self::$m4is_bnd6ti->m4is_ku54f( $m4is_fliw );
 if ( ! is_a( $m4is_x0_hk, 'WP_User' ) ) { return;
 } $m4is_s2ge5 = get_password_reset_key( $m4is_x0_hk );
 $m4is_lg3b = $m4is_x0_hk->user_login;
 $m4is_imdo6 = site_url( 'wp-login.php?action=rp&key=' . rawurlencode( $m4is_s2ge5 ) . '&login=' . rawurlencode( $m4is_lg3b ) );
 $m4is_ash74 = is_multisite() ? get_network()->site_name : wp_specialchars_decode( get_option( 'blogname' ), ENT_QUOTES );
 $m4is_azd3gq = sprintf( __( 'Password Reset for %s' ), $m4is_ash74 );
 $m4is_wbgl5s = __( 'Someone has requested a password reset for the following account:' ) . "\r\n\r\n";
 $m4is_wbgl5s .= sprintf( __( 'Site Name: %s' ), $m4is_ash74 ) . "\r\n\r\n";
 $m4is_wbgl5s .= sprintf( __( 'Username: %s' ), $m4is_fliw ) . "\r\n\r\n";
 $m4is_wbgl5s .= __( 'If you did not request a new password, just ignore this email and nothing will happen.' ) . "\r\n\r\n";
 $m4is_wbgl5s .= __( 'To reset your password, please click the link below:') . "\r\n\r\n";
 $m4is_wbgl5s .= $m4is_imdo6 . "\r\n";
 $m4is_azd3gq = apply_filters( 'retrieve_password_title', $m4is_azd3gq, $m4is_x0_hk->user_login, $m4is_x0_hk );
 $m4is_wbgl5s = apply_filters( 'retrieve_password_message', $m4is_wbgl5s, $m4is_s2ge5, $m4is_x0_hk->user_login, $m4is_x0_hk );
 if ( $m4is_wbgl5s && ! wp_mail( $m4is_fliw, wp_specialchars_decode( $m4is_azd3gq), $m4is_wbgl5s ) ) { wp_die( __( 'The lost password email could not be sent.' ) . "<br />\n" );
 } }  private static 
function m4is_q_e1z9( string $m4is_fliw ) : bool { global $wpdb;
 $m4is_fliw = sanitize_email( $m4is_fliw );
 $m4is_tovizk = "SELECT COUNT(*) FROM `{$wpdb->users}` WHERE `user_login` = %s OR `user_email` = %s";
 $m4is_tovizk = $wpdb->prepare( $m4is_tovizk, $m4is_fliw, $m4is_fliw );
 $m4is_yer1mp = $wpdb->get_col( $m4is_tovizk, 0 );
 return (boolean) array_shift( $m4is_yer1mp );
 } }

