<?php
 class_exists('m4is_pms8y') || die();
 if (! current_user_can('manage_options') ) { wp_die(__('You do not have sufficient permissions to access this page.') );
 } if (! empty($m4is_q2icln) ) { echo "<style type=\"text/css\">{$m4is_q2icln}</style>";
 } echo '<div class="wrap marketplace-wrap memberium">';
  if( isset($m4is_rrm56) && ( ! empty($m4is_rrm56['title']) || ! empty($m4is_rrm56['desc']) ) ){ echo '<div class="marketplace-description marketplace-description-header">';
 echo ( ! empty($m4is_rrm56['title']) ) ? '<h3>'.$m4is_rrm56['title'].'</h3>' : '';
 echo ( ! empty($m4is_rrm56['desc']) ) ? '<p>'.$m4is_rrm56['desc'].'</p>' : '';
 echo '</div>';
 }  echo '<div class="wrap">';
 $m4is_mu0s = false;
  if($m4is_ucwz5e){ echo '<h4 class="nav-tab-wrapper">';
 foreach( $m4is_ejikr4 as $m4is_dc8t5 ) { $m4is_ldjf8y = $m4is_dc8t5['slug'];
 if( $m4is_ldjf8y > '' ){ if( $m4is_ldjf8y === $m4is_sm_wc ){ $m4is_mu0s = $m4is_dc8t5;
 echo '<span class="nav-tab nav-tab-active">';
 echo $m4is_dc8t5['title'];
 echo '</span>';
 } else{ echo '<a class="nav-tab" href="'.$m4is_ac3jkv.'&amp;tab='.$m4is_ldjf8y.'">';
 echo $m4is_dc8t5['title'];
 echo '</a>';
 } } }  echo '</h4>';
 }  if ( $m4is_mu0s ){ echo '<br class="clear">';
 if( ! empty($m4is_mu0s['desc']) ){ echo '<p class="memberium-marketplace-desc">'.$m4is_mu0s['desc'].'</p>';
 }  echo '<div class="wp-list-table widefat">';
 echo '<div id="the-list">';
  $m4is_qj8t9 = '<div class="memberium-marketplace-card %s %s"%s>';
 $m4is_qj8t9 .='<figure%s><img src="%s"/></figure>';
 $m4is_qj8t9 .='<div class="memberium-marketplace-content">';
 $m4is_qj8t9 .= '<h3> %s </h3>';
 $m4is_qj8t9 .='<p> %s </p>';
 $m4is_qj8t9 .='<div class="memberium-marketplace-buttons">';
 $m4is_qj8t9 .='<a class="button button-primary" href="%s" target="_blank">';
 $m4is_qj8t9 .= __('Learn More').'</a>';
 $m4is_qj8t9 .='</div>';
 $m4is_qj8t9 .='</div>';
 $m4is_qj8t9 .= '</div>';
  foreach ($m4is_mu0s['listings'] as $m4is_s2ge5 => $m4is_n0c7) { $m4is_ehym = ( $m4is_n0c7['style'] > '' ) ? " style=\"{$m4is_n0c7['style']}\"" : "";
  $m4is_f8x92 = '';
  if( $m4is_n0c7['border'] > '' ){ $m4is_ms90lx = "border-color:{$m4is_n0c7['border']};
";
 if( $m4is_n0c7['border'] === 'transparent' ){ $m4is_ms90lx .= ' border:none;';
 } $m4is_f8x92 = ( $m4is_ms90lx > '' ) ? " style=\"{$m4is_ms90lx}\"" : "";
 } echo sprintf( $m4is_qj8t9, sanitize_title_with_dashes($m4is_n0c7['title']), $m4is_n0c7['className'], $m4is_ehym, $m4is_f8x92, $m4is_n0c7['logo'], $m4is_n0c7['title'], $m4is_n0c7['desc'], $m4is_n0c7['link'] );
 }  echo '</div>';
  echo '</div>';
 }  if( $m4is_m_ig && ( (! empty($m4is_m_ig['title'])) || (! empty($m4is_m_ig['desc']) ) || ! empty($m4is_m_ig['link']) ) ){ echo '<div class="marketplace-description marketplace-description-footer">';
 echo ( ! empty($m4is_m_ig['title']) ) ? '<h3>'.$m4is_m_ig['title'].'</h3>' :'';
 echo ( ! empty($m4is_m_ig['desc']) ) ? '<p>'.$m4is_m_ig['desc'].'</p>' :'';
 if( ! empty($m4is_m_ig['link']) ){ if( ! empty($m4is_m_ig['link']['title']) && ! empty($m4is_m_ig['link']['url']) ){ echo sprintf('<a href="%s">%s</a>',$m4is_m_ig['link']['url'],$m4is_m_ig['link']['title']);
 } } echo '</div>';
 }  echo '</div>';
 echo '</div>';

